### ISSUE TITLE
Once deactivated, cannot activate

### ISSUE THREAD

**Issue by huskyskins** [ironmonk88/monks-active-tiles#1]
I am having difficulty setting active a tile that has used the trigger to deactivate itself.  I cannot manually set to active either by opening the tile menu, or by triggering it by another tile trigger.  After a single trigger, the tile is useless and must be deleted and replaced.  This is not the case if a different tile deactivates it.  In that case, the deactivated tile can be set to active.

What I'm trying to do is have the trigger run a macro that switches the light when entering a room.  I don't want each player to flip the lights on/off with each step, so I want to deactivate the trigger after the first instance.  However, after they leave, I want to reset the trigger to activate if they return.  I cannot reset (set active) the trigger.

**Comment by ironmonk88** [comment]
Are there any errors in the console?
I'm able to activate/deactivate a tile after it's deactivated itself.
Have you tried just deactivating the tile as the only trigger, just to rule out if it's another trigger causing an issue.
Also can you send a screen shot of the actions you've added and I'll try and replicate them.

**Comment by huskyskins** [comment]
No errors in the console.
Only trigger tile in the scene.
Screenshot before trigger:
![image](https://user-images.githubusercontent.com/86129117/122622304-1fd45380-d04d-11eb-811e-4e5afb7e7fee.png)
Screenshot after trigger:
![image](https://user-images.githubusercontent.com/86129117/122622377-5ad68700-d04d-11eb-9162-af6879d3cdfc.png)
Now, no matter if I click the activate icon in the HUD or click into the tile menu and activate the checkbox, as soon as I click back on the tile it is inactive.

Trigger Tile Actions:
![image](https://user-images.githubusercontent.com/86129117/122622481-b43eb600-d04d-11eb-809f-35faaf4fc971.png)

**Comment by ironmonk88** [comment]
I'm noticing there's a "Provides Cover" control at the bottom, and that's not part of Active Tiles, so I'm wondering if it's another module causing issue.
Could you create a new world, and just have Active Tiles working, and see if it still has an issue?

**Comment by derbal213** [comment]
I'm seeing the same behavior with only Active Tiles working. For me, it seems to happen when I add the Pause Game, Deactivate and Teleport actions to the list of actions. I'm also noticing that when this occurs, if you refresh Foundry, the tile will now be activated (even if you didn't reactivate it).

![Active Tiles](https://user-images.githubusercontent.com/6456972/122998045-9093ac80-d37a-11eb-9b38-cf21a884cfce.PNG)

**Comment by ironmonk88** [comment]
That was a weird one.  Took forever to track it down.
It looks like running all the triggers at once was preventing the database from updating.
So everything looked like it fired, but wasn't actually saved.

**Comment by ironmonk88** [comment]
I've marked this as "fixed waiting for release" but I'll wait until you confirm the first issue is solved by fixing the second issue.

**Comment by huskyskins** [comment]
Did some troubleshooting.  Only experiencing problem when:

1. Using Lightswitch module; and
2. Triggering a macro and deactivate tile; and
3. The macro includes both game.LightSwitch.flipTheSwitchGM("X22E") and game.LightSwitch.flipTheSwitch("X22E") code

Don't know if there's anything to be done there, but that seems to be the conflict.

**Comment by ironmonk88** [comment]
Version 1.0.9 adds support to toggle sounds and lights.
"Activate/Deactivate Tiles" has been converted to just "Activate/Deactivate" and you can select Ambient Light sources and Ambient Sound sources.
I'm not sure what's up with Lightswitch, but does that help the problem if Active Tiles does the work?

**Comment by huskyskins** [comment]
Completely fixed with the new update.  Thank you.
