### ISSUE TITLE
Showing/Hiding 'this tile' does nothing

### ISSUE THREAD

**Issue by brian-e-haley** [ironmonk88/monks-active-tiles#10]

**Comment by ironmonk88** [comment]
Is this still an issue.
There's been a bunch of changes since.

**Comment by brian-e-haley** [comment]
Will update. Unaware of any way of setting tile visibility outside of using a dummy NPC to trigger tile so that is how I will test.

**Comment by brian-e-haley** [comment]
@ironmonk88 after some quick testing show/hide does nothing that I can see. My method of testing is using a test token set created as a PC and moving over the tile with show/hide=toggle set. Moving over the tile has no visible effect from the test token's POV. Having no way to set the initial visibility of the tile leads me to believe that there is no visibility setting to be set and this feature needs to be implemented first to be able to toggle the visibility from the PCs POV.

**Comment by ironmonk88** [comment]
![image](https://user-images.githubusercontent.com/75920956/125982223-7d0f0771-8a5b-4171-8a29-d9191bc23c90.png)
You can set the Tile's visibility from the Tile HUD.
![TileToggling](https://user-images.githubusercontent.com/75920956/125983170-e641c116-cbf4-4892-befe-b8c258f2d056.gif)

**Comment by brian-e-haley** [comment]
I was not aware there was a token hud.

The issue is that there is no visual difference between a hidden and shown tile when using token vision for some reason.

Tile is hidden.
![image](https://user-images.githubusercontent.com/26179509/125992031-8dc297d2-b957-4739-8149-9be78cc388fa.png)

Token can still see tile.
![image](https://user-images.githubusercontent.com/26179509/125992054-150d2818-3c56-4ef2-920f-5a4848747779.png)

**Comment by ironmonk88** [comment]
As a GM, you're always going to see the slightly opaque tile if it has no image.  That's so you don't "lose" it.  The opaqueness will only show to the players if it's visible.
To be fair, the show/hide still works... it's just not going to do much if there's no background image to show/hide.  It's really meant to work with a Tile that has an image.
Were you intending to use the Activate/Deactivate action?  That will stop the Tile from triggering again, once it's been triggered once.

**Comment by brian-e-haley** [comment]
That was me just testing the functionality. I wasn't aware of the right click functionality of the tile and I was mostly using it for displaying flavour text, signs, pausing for combat, rolls for traps and hidden objects.

I think this was just a user error so we can mark this issue as closed. If there are any further issues though I will let you know.

**Comment by ironmonk88** [comment]
No worries.
Glad I could introduce you to some new features.
Closing the ticket.  :-)
