### ISSUE TITLE
FEATURE REQUEST: Filter on Elevation Range

### ISSUE THREAD

**Issue by galaara98** [ironmonk88/monks-active-tiles#100]
I can do a filter by Attribute: Elevation, but it only accepts a single integer.  
I love to be able to filter on if a token is on this tile and at an elevation of -15 to 65 etc.

**Comment by ironmonk88** [comment]
Technically... you can do this by adding two Attribute filters one right after the other.
First one filters by any elevation greater than -15 and the second filters by any less than 65.

**Comment by ironmonk88** [comment]
Closing this as there is a solution available using the current filters.

**Comment by galaara98** [comment]
Ok, makes sense!  Thanks for responding.
