### ISSUE TITLE
"Filter by attributes" not working

### ISSUE THREAD

**Issue by simondw2000** [ironmonk88/monks-active-tiles#101]
Apologies if this is just me using incorrect syntax, but I've been using Baileywiki videos as reference, and I think I've got everything set up correctly.

See the screenshot for details of the tile setup.

1. When the token (with passive perception of 21) enters the tile, there is a check for tokens with >=15 which should pick up the token.
2. Then there is a stop message if no token was picked up.
3. Then it should send a notification.

With the current setup, the notification in step 3 is never triggering.
- I have tried changing the token's passive perception to various numbers between 1-30 and it still won't trigger.
- I have tried changing the ">=15" to "<=15" and then the tile triggers every time regardless of the token's passive perception score.
- No errors are being generated in the console.
- I have checked for updates today and am already on the current version.

![image](https://user-images.githubusercontent.com/30345746/151148575-26469386-dc77-4841-8467-6379ec85bbda.png)

**Comment by simondw2000** [comment]
Just realised I hadn't tested with other modules diabled.
I have now done this (Only Monk's Active Tile Triggers and Monk's TokenBar enabled). The problem persists.

**Comment by ironmonk88** [comment]
You probably want `skills.prc.passive` that would be passive perception. 
`skills.per.passive` is passive persuasion.  :-)

**Comment by simondw2000** [comment]
Omg, I'm such an idiot.

Thank you @ironmonk88
