### ISSUE TITLE
On Click not activating in 9.245

### ISSUE THREAD

**Issue by Olliebird** [ironmonk88/monks-active-tiles#105]
In the latest build, it appears tiles with the 'On Click' or 'On Double Click' aren't activating. See settings in SS. 

![image](https://user-images.githubusercontent.com/16262718/151675114-a87dfe65-d235-4e26-9203-13a0d00dcbf8.png)

Other triggers do appear to activate normally, such as 'On Enter', 'On Exit', etc. Only 'On Click/Double Click' do nothing.

**Comment by TomChristoffer** [comment]
Can confirm, this doesn't work for me either.

**Comment by Tarmorax** [comment]
I also have this issue.

**Comment by Ulvtand** [comment]
It works fine for me. But I have 9,249, maybe that's what makes the difference?

**Comment by Necrotech242** [comment]
Same issue here, On v 9.249

**Comment by ironmonk88** [comment]
I'm assuming PF2E.  That system introduced an error that prevented On Click from working.
It should have been fixed in the last release of Active Tiles though.

**Comment by Necrotech242** [comment]
Was playing Mutant: Year Zero. But the release today fixed the issue. 
Great job!

**Comment by Joshmvii7** [comment]
@ironmonk88 I play PF2E. On click and on double click is not working in the PF2E 3.4 release.

**Comment by ironmonk88** [comment]
Closing this ticket as I believe the issue has been resolved.
