### ISSUE TITLE
Triggering token can't find token

### ISSUE THREAD

**Issue by TomChristoffer** [ironmonk88/monks-active-tiles#109]
Whenever the 'Triggering Token' entity is triggered by a player it can't find a token. The History is just blank where it lists token names, and there's an info message that says 'no token to teleport' upon trying to teleport triggering tokens. I as the GM can trigger these things with no problem, teleporting, clicking, everything, with both npcs and player tokens, but the players themselves can't on their instances.

**Comment by AustinTiger** [comment]
First off, awesome module.  I really enjoy many of your modules.

I have also been having this exact issue over the past day.  Here's a screen shot of versions, tile count, etc in case any of this is useful.

![NoTokenFound-versions](https://user-images.githubusercontent.com/98142084/152694991-86051eec-3fc1-41b4-87f9-c69fcfbe425c.png)

**Comment by ironmonk88** [comment]
Fixed and released.  The latest code made some small minor changes... that had some big effects apparently.

**Comment by AustinTiger** [comment]
Confirmed fixed.  Thanks!
