### ISSUE TITLE
Once per token check box no longer there when creating new tile

### ISSUE THREAD

**Issue by kuchrk24** [ironmonk88/monks-active-tiles#111]
Module version 1.0.55
Foundry version 9.249

Recently updated modules and I am no longer seeing the checkbox for "once per token" when creating a new active tile. Tiles created before update that had that checked still show it.

![image](https://user-images.githubusercontent.com/74018852/152862962-15a2a7ca-39c4-4a69-ba16-66762e4c271b.png)

**Comment by ironmonk88** [comment]
Once per token has been removed, and has now been added as a filter.
The filter gives you a much more flexible way of providing the same features.

The Min. Required field has also been removed in favor of a filter.

**Comment by kuchrk24** [comment]
Oh sorry about that. Will pre-existing tiles that used the checkbox still work, or do they need to be converted?

**Comment by kuchrk24** [comment]
Actually it seems like the tile history isn't populated anymore. Is that intentional? Regardless of pre-existing tile or newly created one with the filter, it doesn't seem to be honoring token activation count. Checking the tile history shows a blank list even though the tile has been activated.

**Comment by ironmonk88** [comment]
They will continue to work as expected.  The code hasn't disappeared, just the controls are hidden.
So if you've changed the value, the controls will still be there and the code will still work.  As soon as you set them back to default, or if you create a new Tile, they won't be there and you'd need to use the filters.

**Comment by kuchrk24** [comment]
Excuse my ignorance. Is there documentation somewhere of all the options and what that do? The readme seems pretty sparse. Having trouble getting it to work with the new way.

**Comment by ironmonk88** [comment]
Well... that's a bug.
It's been fixed, I'll try and get a patch out later today.

**Comment by kuchrk24** [comment]
Oh ok. Thank you!

**Comment by ironmonk88** [comment]
My documentation is in desperate need of an upgrade.
It's on the list when I have time.
There's a lot more help and examples on my server.
https://discord.gg/fqX7FFax
