### ISSUE TITLE
BUG: Not chatting in character.

### ISSUE THREAD

**Issue by pesky-wobbit** [ironmonk88/monks-active-tiles#112]
I'm using the chat message action like so
![image](https://user-images.githubusercontent.com/477446/152893020-9af1445f-213c-4451-8779-6738a34bae4c.png)
but getting this result
![image](https://user-images.githubusercontent.com/477446/152892924-254bbf87-aa5e-4ac5-a46d-f73ae4a311e4.png)
I'm wishing the Chat used the character name instead of the player name. Thanks!

**Comment by ironmonk88** [comment]
There have been changes to the Chat Message action and it's using the character name when I test it.
Is this still an issue?

**Comment by ironmonk88** [comment]
Closing this as there's been changes, I can't replicate and there's been no response to the question.
