### ISSUE TITLE
BUG: Teleportation Locks Token Movement Indefinitely

### ISSUE THREAD

**Issue by Zephyr2011** [ironmonk88/monks-active-tiles#116]
**VERSION:** 1.0.57
Note: this was not present in version 1.0.5.5

**ISSUE:**
Using a Tile trigger to teleport a token to a new scene "On Click" results in the new token being unable to move indefinitely. Using a Tile Trigger to teleport _anywhere_ "On Enter" results in the token stopping movement part-way into the tile and being unable to move indefinitely, as a result, tokens are also unable to teleport to the new scene. All movement appears to be disabled, this includes arrow-key, click-and-drag, and macro movement for GM and player.

"On Click" issues appear to only affect Cross-Scene teleports.

"On Enter" issues appear to affect both Cross-Scene and Intra-Scene teleports.

There does not appear to be a visual indicator giving a duration to this effect. Refreshing, and restarting FoundryVTT does not appear to restore movement abilities. The token must be deleted and replaced to function.

**SUSPECTED CAUSE:**
I believe this is related to the new flag stopping tokens from moving mid-teleport:

>  Added a flag for teleporting so the token won't be moved mid-teleport.  I believe this was causing a sync issue between the GM and players.

For "On Click," the flag is copied onto the new token in the destination scene, but there is no new teleport action to remove the flag.
For "On Enter," the flag is added to the token, but the teleport isn't completed (due to load times?), and therefore the flag is not removed.

**PROPOSED SOLUTION:**
Add a timer or similar measure to automatically remove the flag after a given length of time from its creation, regardless of teleport status.

I don't know if this is a viable solution, but I'm not sure how else to cleanly remove the flag from cross scene tokens.

**STEPS TO RECREATE:**

1. Create Tile
2. Add Teleport Trigger
3. Select coordinates or tile destination on new scene (or the same scene if Testing "On Enter" in step 6)
4. Select any combination of teleport "secondary options" (snap to grid, animate canvas pan, etc.)
5. Save Trigger
6. Set "When" field to "On Click" or "On Enter" (for the respective behaviors)
7. Update tile.
8. Place token in same scene with tile. (Linked, Unlinked, Player, and NPC all appear to be affected identically)
9. Trigger tile with token

**Comment by Zephyr2011** [comment]
**UPDATE:**
Tested on new version 1.05.8

"On Click" issues appear to be resolved completely.

"On Enter" no longer locks token movement indefinitely, however, tokens stop moving part way into entering the tile and teleports do not complete. The tokens can be moved after a brief delay, but the teleport does not occur.

**Comment by ironmonk88** [comment]
Omg.  This is one of these fixes that needed to be done... but I just can't seem to get correct.
Try version 1.0.59.
And I'll add a timer in the next version to release the teleport regardless of if it succeeded.

**Comment by Zephyr2011** [comment]
Just tested in 1.0.5.9

No worries! I appreciate the fast response time and bug fixes on this.

Looks like the "On Enter" is still having issues (both cross-scene and intra-scene). Movement stops before the teleport goes off so there's this "sticky" effect where a token stops moving before fully entering the tile's area. After a brief delay the token can be moved, but won't ever teleport, so I think no change in behavior for me between 1.0.5.8 and 1.0.5.9 (unless there's an edge case I didn't test between the two).

**Comment by pesky-wobbit** [comment]
This has cropped up for me again - but only when invoking the "avoid other tokens at destination" option.

**Comment by ironmonk88** [comment]
I believe this should be fixed?
Just cleaning up the ticket queue, please let me know if it's still an issue.
