### ISSUE TITLE
Bug - 1.0.59 ENter / Exit Movement will not trigger actions only click on seems to work 

### ISSUE THREAD

**Issue by Ramz1337** [ironmonk88/monks-active-tiles#119]
1.0.59 DND 5e Tile trigger will work with click on but does not work with on enter/exit or movement.

Running latest ver of foundry etc.

**Comment by ironmonk88** [comment]
It looks like it's working correctly for me.
Any errors in the console?
What actions are you trying to perform?
Have you run Find the Culprit to see if another module is interfering?

**Comment by Ramz1337** [comment]
Hi sorry for the delay in feedback
