### ISSUE TITLE
Action: Pause Game - Unpause is toggling pause

### ISSUE THREAD

**Issue by galaara98** [ironmonk88/monks-active-tiles#126]
the Unpause action is acting like a toggle (if paused it will unpause, but if unpaused it will pause)
Pause Game - Pause is working as expected (if unpaused, pause.  If Paused, do nothing (technically, i can see it resets the paused game icon to its original location, so it probably "re-pauses")

Pausing doesnt seem like toggle would ever come up, but i suppose it wouldnt hurt to have Pause, Unpause, and Toggle

**Comment by ironmonk88** [comment]
That looks like a bug in Foundry.
I'll compensate for the code in the next release, and add a bug report for them to get that fixed.

**Comment by ironmonk88** [comment]
Should have been fixed a couple versions ago.  Just cleaning up the queue.
