### ISSUE TITLE
On Enter no longer works on newly modified or created tiles

### ISSUE THREAD

**Issue by Dairid** [ironmonk88/monks-active-tiles#129]
Any on enter/exit no longer works on newly modified or created tiles.

I was trying to create some traps and was using a previously known good trap and attempting to associate it with a damage source on scene, every time I'd update the tile it would stop working.

I eventually thought maybe my 'known good' had some kind of error on it.  So I went and just tried to make a fresh tile and could not get it to trigger except by 'manual' or 'clicks' I couldn't get a token moving into the tile to trigger it anymore.  If I left the 'known good' tile alone it would still do 90% of the trap, but the second I modify ANYTHING it kills it's ability to notice a token moving.

**Comment by King-Khufu** [comment]
I am experiencing the same issue.

**Comment by bernardovento** [comment]
Hello, I did some tests, and the error only occurs when I have the Levels and Parallaxia module together. Could you tell me if you have them too?

**Comment by King-Khufu** [comment]
Yup it's an issue with Parallaxia breaking Levels.

**Comment by ironmonk88** [comment]
Closing this as it was a Paralaxia issue and should have been fixed.
