### ISSUE TITLE
Macros Do not Run with Advanced Macros enabled

### ISSUE THREAD

**Issue by akrigline** [ironmonk88/monks-active-tiles#13]
Reproduce steps:
1. Have Advanced Macros enabled with Active Tiles
2. Create a Tile with a trigger that fires a macro (leave arguments blank)
3. Create a simple script macro:
```js
console.log('args', {this: this, arguments});
```
4. Move a token into the tile.

Without Advanced Macros enabled I see the log being fired, but with advanced macros on it is not.
![image](https://user-images.githubusercontent.com/7644614/125952614-f8d102eb-da14-43b5-833f-6fe77fdacda4.png)

**Comment by ironmonk88** [comment]
That's weird.
I'm unable to replicate that.  That script is working for me using both Active Macros and without.
What version are you running and can you click the "Execute Macro as GM" and see if that makes a difference?

**Comment by akrigline** [comment]
I'll take another look as I can and let you know.

**Comment by rinnocenti** [comment]
here is the same, whit advanced macro not run.
but without not running too, but execute the macro with error:
![image](https://user-images.githubusercontent.com/3178127/126739472-c6586b95-a227-4fb2-b9d8-909a2bb7d1cd.png)

**Comment by ironmonk88** [comment]
Latest release is out.  Is this still an issue?

**Comment by tposney** [comment]
I just checked and it seems to still be an issue. I made the following change
```
        if (game.modules.get("advanced-macros")?.active || game.modules.get("furnace")?.active) {
            if ((getProperty(macro, "data.flags.advanced-macros.runAsGM") || getProperty(macro, "data.flags.furnace.runAsGM") || token == undefined) && !game.user.isGM) {
 ```
and the macro now seems to run

**Comment by ironmonk88** [comment]
I think this is fixed in the latest version.

**Comment by tposney** [comment]
args not defined usually means either itemMacro is taking over the roll (character sheet setting for Item Rolls) or advanced macros is not installed

**Comment by tposney** [comment]
Confirm that macros run.
For those used to the normal macro arguments, be aware that things are slightly different when called via tile triggers.
args is an array as before.
args[0] is an object {actor, args, tile, token, user}
args[0].args are the arguments passed to the macro

**Comment by ironmonk88** [comment]
I used your code tposney and it should look the exact same as trigger happy macros now.
Thank you for that!
To get the tile, you'll need to use arguments.tile.  But everything else should be back to normal.
