### ISSUE TITLE
Tokens within tile teleport not working from all directions

### ISSUE THREAD

**Issue by SalieriC** [ironmonk88/monks-active-tiles#130]
I've set up a tile like this:
![image](https://user-images.githubusercontent.com/1230041/154798995-51eb6a5a-c171-4633-b578-79564672cd86.png)

The issue is that entering the tile from south or east works fine all the time. Entering the tile from the north or west however always produced an error as seen below (red grid is to illustrate the maps grid). The token stops within movement, unaligned to the grid and a notification pops up informing that there is no token to teleport.
![teleport](https://user-images.githubusercontent.com/1230041/154799234-980f8e1a-3192-42a7-aea1-3a2d74a3cf56.gif)

I've tried to make the tile half a grid bigger to the north and west but that doesn't fix it.

**Comment by Roblinde** [comment]
@SalieriC I had this same issue and inspected the code. All the logic is good, but it seems there's a race condition, when the token triggers the tile, it does so at the start of it's movement when only a small portion of the token is on the tile. 

A simple workaround is to add a delay just before the trigger that checks for tokens within.

Here's an example of a configuration that seems to work for me:
![image](https://user-images.githubusercontent.com/1835323/160107847-c4887c3b-f676-47ab-8318-acaefc0d538b.png)

**Comment by ironmonk88** [comment]
The on enter function has changed.
I'm no longer able to replicate this.

**Comment by ironmonk88** [comment]
Is this still an issue?

**Comment by Roblinde** [comment]
@ironmonk88 I think this is resolved as far as I can tell! Thanks!

**Comment by ironmonk88** [comment]
Fixed in the recent release.
