### ISSUE TITLE
A token flying or hovering across a trapped tile still triggers the tile

### ISSUE THREAD

**Issue by rpganalyst** [ironmonk88/monks-active-tiles#131]
Hello,
I set a trap tile in a dungeon, then I would like flying tokens to overcome the trap to avoid accidental reveal of the trap location.
I'm using Drag Ruler, DnD5e Drag Ruler Enhancer, Enhanced Terrain Layers and Terrain Rulers module.

Thank you

**Comment by MarkPearce** [comment]
you could check token.data.elevation in your macro

**Comment by rpganalyst** [comment]
> you could check token.data.elevation in your macro

Hello, I'm a rather new user of Foundry, so I've no macros running in my games.
You are saying that I should set a macro to change the parameter of token elevation for a flying/hovering token in order to avoid the trapped tile triggering, are you?

Thank you.

**Comment by MarkPearce** [comment]
there's so many ways to approach it that its hard to say exactly.  But if you are triggering a macro for the trap, then you could use something like this.... 

if (token.data.elevation == 0) {
  <your trap macro here>
}  

that will only run the macro if the token is at elevation 0. So if you set a flying creature's elevation to anything but 0 the macro will not be run.

**Comment by rpganalyst** [comment]
> there's so many ways to approach it that its hard to say exactly. But if you are triggering a macro for the trap, then you could add something like this to the trap macro....
> 
> if (token.data.elevation == 0) {
> 
> your trap macro here
> 
> }
> 
> that will only run the macro if the token is at elevation 0. So if you set a flying creature's elevation to anything but 0 the macro will not be run.

Actually I've never used macros, but it's a good time to start! I'm using Monk's Active Tiles to set the trap and it autotriggers when someone enters. Can I export its settings in a macro and then add your IF line?
Thank you.

**Comment by MarkPearce** [comment]
I'm no expert... but i guess that depends on what action you use with trigger? I normally use "run macro" for a trap. 
Then you could modify the macro code.
 
I was just looking into it a bit more, and you can use "filters" in monks active tiles as conditions.  Here is an example of a trap that will only trigger if elevation = 0
 
![image](https://user-images.githubusercontent.com/6976378/156174005-3ace37ad-a39e-4260-83ab-f79638f746b2.png)

baileywiki the undisputed master of foundry automation, discussed the technique in this video
https://www.reddit.com/r/FoundryVTT/comments/scoe30/foundry_quick_tutorial_creating_smart_traps_and/

**Comment by rpganalyst** [comment]
> I'm no expert... but i guess that depends on what action you use with trigger? I normally use "run macro" for a trap. Then you could modify the macro code.
> 
> I was just looking into it a bit more, and you can use "filters" in monks active tiles as conditions. Here is an example of a trap that will only trigger if elevation = 0
> 
> ![image](https://user-images.githubusercontent.com/6976378/156174005-3ace37ad-a39e-4260-83ab-f79638f746b2.png)
> 
> baileywiki the undisputed master of foundry automation, discussed the technique in this video https://www.reddit.com/r/FoundryVTT/comments/scoe30/foundry_quick_tutorial_creating_smart_traps_and/

Thank you, it works. But I detect a new issue: Stop Token Movement triggers even if the token elevation does not triggers the other tile effects. If it isn't a error of mine, I'm going to close this Issue and open a new one about this.

**Comment by ironmonk88** [comment]
The problem with stop movement is that it needs to alter the token's destination before it knows if the token will be affected or not.
What you can do though is use "Continue if none" to an anchor that uses a "Move Token" action to go to the tokens original destination.

**Comment by rpganalyst** [comment]
> The problem with stop movement is that it needs to alter the token's destination before it knows if the token will be affected or not. What you can do though is use "Continue if none" to an anchor that uses a "Move Token" action to go to the tokens original destination.

Could you provide a screenshot with an exemple? I know the features you name, but I can't use them, I still don't understand all the options that your module give to the GM.

Thank you.

**Comment by ironmonk88** [comment]
![image](https://user-images.githubusercontent.com/75920956/164948847-3aef350a-108b-4056-b8dc-da934548a406.png)
This should do what you're looking for.
Make sure you use `Triggering Tokens` instead of Current Tokens for the Move Action.

**Comment by ironmonk88** [comment]
![image](https://user-images.githubusercontent.com/75920956/164948895-1428d91a-eeee-44f6-95ad-ab8da3608eb9.png)
That's the "original location" button.

**Comment by rpganalyst** [comment]
> ![image](https://user-images.githubusercontent.com/75920956/164948895-1428d91a-eeee-44f6-95ad-ab8da3608eb9.png) That's the "original location" button.

> ![image](https://user-images.githubusercontent.com/75920956/164948847-3aef350a-108b-4056-b8dc-da934548a406.png) This should do what you're looking for. Make sure you use `Triggering Tokens` instead of Current Tokens for the Move Action.

Tomorrow morning (CEST) I'll try that, then I suppose I can come back to close this issue with gratitude.

**Comment by rpganalyst** [comment]
The tiles are working perfectly now, the problem Is the Flying Speed module that doesn't set the token height › 0. Thank you.
