### ISSUE TITLE
Question: Mutiple event types

### ISSUE THREAD

**Issue by HippyCraig** [ironmonk88/monks-active-tiles#132]
Not an issue but I was wondering if one tile can fire on mutiple types of events.  For example if I want to have differnt events fire for mouse over and something differnt on a mouse out, but also respond to a click.  Currently I have to use over lapping tiles to achived this, is there a better way?  Can you have a tile trigger and do different actions based on mutiple event types?

**Comment by ironmonk88** [comment]
You couldn't at the time this question was asked.
But the current version of MATT allows it.

**Comment by HippyCraig** [comment]
GREAT!!!!!
