### ISSUE TITLE
Feature Request: Timer Integration

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#133]
Would it be possible, either as its own action or as part of a Delay action, or both, to have a timer be activated using the Timer settings.

https://foundryvtt.com/packages/timer

**Comment by ironmonk88** [comment]
Added support for the Chat Timer function of Monk's Little Details.
It's not technically Timer support... but it should server the same purpose.

Please feel free to re-open the ticket if you need support specifically for this module.
