### ISSUE TITLE
Feature Request: Manually enter Target

### ISSUE THREAD

**Issue by dcoughler** [ironmonk88/monks-active-tiles#134]
It would be very beneficial if you could manually enter a target rather than only being able to select it.

Workflow Example: You develop a trap tile with multiple steps. You want to reuse it in more than one place on the map. You copy the component tile(s), and paste at the second location. Now you need to update any target indicators. Currently, you need to go through each event, bring out the target tool and select the new target.  It would be very helpful if we could use the target tool to get the new identifier once, then simply copy paste into the required steps rather than have to use the target tool each time.

**Comment by ironmonk88** [comment]
I think at that point you could use Tagger integration to achieve what you're looking for.
And a little easier since it works off human text rather than a unique identifier.

**Comment by dcoughler** [comment]
I don't really want an extra module. Maybe I'll just see if I can't make the field editable.

**Comment by ironmonk88** [comment]
Support should be available in the latest version.  Double-clicking the field will open a dialog to enter the entity id.
