### ISSUE TITLE
Bug:  TypeError when using filter by items in inventory

### ISSUE THREAD

**Issue by overdox** [ironmonk88/monks-active-tiles#135]
Getting a type error when trying to use the filter by items in inventory in combination with the "hurt/heal" option, in the PF2e system.
~~However, it does seem to work while using other options in combination with the filter.~~

Scratch that, seems to trigger regardless if the item is found in the characters inventory or not.

![Screenshot of the console](https://i.imgur.com/aDLNaZ7.png)

**Comment by ironmonk88** [comment]
Looks like it's an issue with Pathfinder 2.
I've updated the code to compensate.

**Comment by ironmonk88** [comment]
This should be fixed in the latest version, just cleaning up the ticket queue.
