### ISSUE TITLE
Support Drawings in addition to Tiles

### ISSUE THREAD

**Issue by devinnasar** [ironmonk88/monks-active-tiles#138]
As a GM, I'd like for Monk's Active Tile Triggers to support Drawings in addition to Tiles as being a designation for zones that trigger game effects, so that I can design triggers without needing to supply assets to mark them.

Hello,

Drawings as a zone designation for triggers seems like it would be more flexible for being able to quickly lay out the interactivity in a scene.

- Drawings are able to be shaped as polygons, so their areas of influence would be more dynamic and accurate to the art that they cover.
  - For example, a boulder triggering an effect would benefit from a circular boundary.
- Drawings also have inherent styling options, which would allow GMs to create visual markers to note the categories that their zones fall into.
  - For example - Baileywiki creates a number of static square tiles which contain icons designating what the tile category is, but often in his videos, he needs to stretch them to make them fit the scenario he lays out, which distorts the tile art.
  - Drawings support tiling textures, which would allow the art to simply repeat itself or tesselate depending on the texture art.

**Comment by devinnasar** [comment]
As I've been following Theripper93's work with Levels, it occurs to me that rather than adding standalone trigger functionality to drawings, it might work to simply add a drawing as a mask on top of a tile similar to how Levels allows us to define a hole. Right now in order to accommodate odd shapes for triggers people have to deploy multiple tiles of the same kind, say for a triangular rocky outcropping where players fall if they cross the edge.

**Comment by ironmonk88** [comment]
The latest MATT should support complex transparent images.
It might require the use of two images if the image has a transparent "hole" in the center, as the function that finds the border can only find a border.
Closing this as it should now be accommodating the spirit of the request.
