### ISSUE TITLE
Request: Change scene's background/foreground image

### ISSUE THREAD

**Issue by Waltrobus** [ironmonk88/monks-active-tiles#139]
In some cases it is very useful to be able to change the scene's bg/fg image instead of the whole scene. For example the PCs are travelling with an airship (or some other larger vehicle) and the scenery changes, but not the vehicle itself making it important to keep the character positioning and fog of war inside the ship/vehicle. It would be handy to have the MAT handle the change of the bg image file instead of going through the file picker to change the image manually every time.

**Comment by ironmonk88** [comment]
Changing the background of a Scene is available as an action.
You should also be able to change it via the Alter action.  So to change the foreground image you'd have to go that route.
