### ISSUE TITLE
Feature Request: Activate Tile on Right Click

### ISSUE THREAD

**Issue by hlmodking** [ironmonk88/monks-active-tiles#141]
**Request:** Add an option for "right click to activate" to allow for right clicking of the canvas as an activation trigger. 

**Reason:** Some macros require an actively selected token/actor. If the **core setting of "Left Click to Release"** is active for the player/gm; the token will release upon a left click before Monks is triggered. This prevents the activation of "click" in Monks during this use case. 

This would be helpful for all systems for many call macros that utilize the selected actor and not just the user. 

Fantastic work, appreciate your efforts and continuous updates!

**Comment by ironmonk88** [comment]
Right click was added a couple versions ago, Just cleaning up the ticket queue.
