### ISSUE TITLE
Bug: Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by overdox** [ironmonk88/monks-active-tiles#143]
There seems to be a recursive function call causing issues for my existing world. I am no longer able to add or modify existing actions on tiles, on either new or already created tiles. 
Tiles with existing actions are working fine, I'm just no longer able to modify them. But if I create a new world, I can do so.

Tested with only Monk's Active Tiles module v 1.0.64, and no other modules active.

![Screenshot of the console](https://i.imgur.com/uMtJXqp.png)

**Comment by overdox** [comment]
I have narrowed the issue down to a actor in the world. After I deleted said actor, I was able to add new actions. 
I don't have history enabled on any of my active tiles. Any idea how this issue could have occurred?

**Comment by JamzTheMan** [comment]
Mmm, I encountered the exact same issue today as well in my PF2E world.  Thanks to @overdox I did the same, I had to delete several world actors (PC's) and it started working again. I tried to narrow it down to a single actor but I need to remove at least 4 before it resolved.

Oddly enough I was able to re-import the actors and MAT still continued to work, so possibly old JSON data on the actors that got cleaned up on import...

**Comment by JamzTheMan** [comment]
Ok, scratch that, it came back after importing this character back and refreshing...

[fvtt-Actor-boraks.json.txt](https://github.com/ironmonk88/monks-active-tiles/files/8257456/fvtt-Actor-boraks.json.txt) <--added .txt so github would attach...

[mat-error.log](https://github.com/ironmonk88/monks-active-tiles/files/8257452/mat-error.log)

![image](https://user-images.githubusercontent.com/8051654/158479134-1fb0a11a-2ea5-4dcc-a85a-53351e8643c5.png)

**Comment by ironmonk88** [comment]
Looks like it's the item "Shield Boss (+2 Gr striking w/rings)" that's causing all the issues.
Somehow PF2E introduced a circular loop with that item.

**Comment by overdox** [comment]
> Looks like it's the item "Shield Boss (+2 Gr striking w/rings)" that's causing all the issues. Somehow PF2E introduced a circular loop with that item.

I find that odd, as I never used that item on any of my characters during testing?

**Comment by ironmonk88** [comment]
I believe this was fixed a few versions back, just cleaning up the ticket queue
