### ISSUE TITLE
Feature Request: Cycle Image via Rolltable

### ISSUE THREAD

**Issue by GrumpyVader** [ironmonk88/monks-active-tiles#144]
Use Case: Setting up a card draw with x number of cards. Each card should be random but also not draw the same card more than once. Utilizing rolltables could provide this functionality, otherwise logic would be needed to track if an image has already been used. The other advantage to using rolltables is eliminating the need to duplicate the image references for multiple tiles.

**Comment by ironmonk88** [comment]
You can already sort of do this.  And doesn't require Cycle Images.

If you create a Rolltable with a list of image paths.
![image](https://user-images.githubusercontent.com/75920956/158473375-f3413554-a33b-4dc8-99ea-17133b874023.png)
Then add the actions to change the Tile's `img` attribute based on the result from the Rolltable.
![image](https://user-images.githubusercontent.com/75920956/158473506-5afbecc3-f55f-49a6-ad16-2e314b27344e.png)
You can change the Tile's image based on the Rolltable.

There was a bug in the code... so this won't work until the next release though.

**Comment by GrumpyVader** [comment]
Ohh. I did not know that. I will test it out with your next release.
