### ISSUE TITLE
Active tiles/Tagger -  Cycle images

### ISSUE THREAD

**Issue by OCEISCO** [ironmonk88/monks-active-tiles#150]
Hello monk
Already [raised this issue with Haxxer](https://github.com/fantasycalendar/FoundryVTT-Tagger/issues/11), where cycle images do not support tagger and therefore limit the development of prefabs with alternate images/states. When I was adding a new prefab actor to the canvas, with an action to cycle images for - name{#}, the instance cannot be updated as the rest of the elements, and therefore breaks the prefab functionality.

I was wondering if you can give some advice on the best approach to use cycle images with tagger?
Thank you

![InkedTagger_Cycle images_LI](https://user-images.githubusercontent.com/101099466/159220178-7dc8e175-93f2-4ad1-b0ba-0b90905e1ed1.jpg)

**Comment by ironmonk88** [comment]
Closing this as there's been no response to indicate it's still an issue.
