### ISSUE TITLE
Play Animation Trigger on traps not working for player

### ISSUE THREAD

**Issue by sigshot552** [ironmonk88/monks-active-tiles#151]
I can setup triggers to play animation while as a GM. However, everytime my players walk over the trigger, the animation doesnt play and I get a red error of:

User "Name" lacks permission to update tile [tile name] in parent scene [scene name]

all other triggers are working. Any ideas?

**Comment by ironmonk88** [comment]
Thank you for catching that.
There's a handful of actions that can't be triggered if the GM isn't present.  Looks like I missed this one.
I'll make sure that action can only be triggered by the GM in the next release.

**Comment by sigshot552** [comment]
No worries! I had the "allow players" box checked and it still wouldnt work. Ended up having to to have both a gm and player logged in for it to fire properly from the players view. THANKS!!!

**Comment by ironmonk88** [comment]
Closing this ticket as the issue should have been resolved.
