### ISSUE TITLE
Feature Request: Tile Tooltips

### ISSUE THREAD

**Issue by GrumpyVader** [ironmonk88/monks-active-tiles#152]
Use Case: Display a "tooltip" or description for a tile on Hover Over. This would be useful in displaying a "snippet" of journal info without having to load the full journal.

**Comment by ironmonk88** [comment]
In the latest version you should be able to create a Text Drawing, and then use On Hover to show/hide it.
![image](https://user-images.githubusercontent.com/75920956/164947225-d18e047f-aa87-41fd-808a-2cc5a9d5c04a.png)
I prefer doing it this way, and it leaves it up to the user how they want to display a tooltip.
