### ISSUE TITLE
Potential conflict with Monk's Active Tile Triggers

### ISSUE THREAD

**Issue by rpganalyst** [ironmonk88/monks-active-tiles#154]
Hello, I posted this issue on Perfect Vision's github. It's seems to be on Monk's Active Tiles' end. Here my previous post.
![image](https://user-images.githubusercontent.com/47994415/160255751-0a76213a-68f7-4712-b3e5-0c46b135cbfc.png)
Thank you

P.S. Even with the warning I've not experimented problems.

**Comment by ironmonk88** [comment]
Should already be fixed in the latest version.

**Comment by rpganalyst** [comment]
> Should already be fixed in the latest version.

It is, thank you.
