### ISSUE TITLE
[1.0.67] Hover pointer stuck after scene change

### ISSUE THREAD

**Issue by jocolamarco** [ironmonk88/monks-active-tiles#156]
1- Mouse icon changes when hovering on the tile only.
2- Click tile that navigates to a different scene
3- Mouse icon changes when hovering on the tile and gets stuck:

https://user-images.githubusercontent.com/45291719/160427113-079f50aa-4cf7-440e-ae33-1683b68de057.mp4

Tile area:
![image](https://user-images.githubusercontent.com/45291719/160428077-ead59850-9da0-487e-9ff2-e88b5a180f8c.png)

**How the tile is configured:**
![image](https://user-images.githubusercontent.com/45291719/160427508-c609a5c4-ab4c-45ff-9fa4-1d2548f65ea8.png)
![image](https://user-images.githubusercontent.com/45291719/160427587-5cd2cf69-92c8-4c9d-a89a-bd4d2ff2f2ef.png)

**Versions:**
![image](https://user-images.githubusercontent.com/45291719/160427232-3de6c0a1-af99-4343-9032-bfd22fbd1a44.png)
![image](https://user-images.githubusercontent.com/45291719/160427288-dc174cf3-1ef5-49e3-a300-858e4e3a5adf.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
