### ISSUE TITLE
Please add documentation

### ISSUE THREAD

**Issue by dmrickey** [ironmonk88/monks-active-tiles#157]
It would be incredibly useful to add documentation about the different categories of triggers, the different options for individual triggers, how logical triggers interact.. etc

**Comment by Shuggaloaf** [comment]
A strong 2nd on this. There are items that the label doesn't clearly indicate what they do and I've found at least a dozen triggers so far that seem to do nothing.

The mod itself is amazing. Adds a lot of options for things I use dot have to have a macro for. I just want to be able to use _more_ of it. :-)

**Comment by the-real-orson** [comment]
A third on this.

**Comment by ironmonk88** [comment]
[http://crowguide.wikidot.com/monk-s-active-tile-triggers](http://crowguide.wikidot.com/monk-s-active-tile-triggers)
