### ISSUE TITLE
Add action grouping

### ISSUE THREAD

**Issue by ironmonk88** [ironmonk88/monks-active-tiles#16]
I think this could fit in nicely with what event triggers them (On Enter, On Exit, etc.)
And what to add a little logic to it.

**Comment by happy-cujo** [comment]
You mean that one tile can have multiple flows? On exit do X, on enter do Y? 
If yes then that would be awesome.

**Comment by Haxxer** [comment]
I too would find many usecases for this - I've been noodling with Sequencer to be able to create client side effects, which would be awesome for active tiles.

If a user hovers over a tile, play an effect on the tile _only_ for that user, and once their mouse leaves the tile, end that effect.

**Comment by ironmonk88** [comment]
Closing this, I didn't end up implementing this, but I think with landings it does a decent job of representing the spirit of the request.
