### ISSUE TITLE
Heartbeat effect not playing via Kandashi's Fluid Canvas

### ISSUE THREAD

**Issue by KammaKhazi** [ironmonk88/monks-active-tiles#160]
Hiya, I noticed setting up an active effect tile for a trap that using 'Execute Effect' with Kandashi's Fluid Canvas (v0.3.0) to set a "Heart Beat" effect does not currently work. Earthquake seems to work fine. Many thanks for all your excellent modules.

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
