### ISSUE TITLE
Change Movement Mode Clarification

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#161]
![image](https://user-images.githubusercontent.com/99844555/162097462-f640cb66-6b3e-4021-af35-98e093c8fc9c.png)

Add "Global" to the middle; some new users may question why an Action called Change Movement asks you if you want to change movement.

**Comment by ironmonk88** [comment]
Closing this as it's been added.
Technically a Tokenbar issue, which is why I forgot to close it.
