### ISSUE TITLE
Number of Simultaneous Tokens required to activate

### ISSUE THREAD

**Issue by ericloyd** [ironmonk88/monks-active-tiles#163]
I was struggling with a trap door that required three players to stand on it before it was "enough weight" to fall and open up to the pit below.  I though "Min required to Trigger" meant that if I used "Enter" as the trigger, then three players entering the tile would cause it to trigger.  I had to look through the code to see that it's a cumulative count of how many people have entered the tile, not a simultaneous count.

Is there any way to make it so that a tile has to have X number of people currently "entered" onto the tile (which is really the only time it make sense) to activate?  I realize this means having a counter somewhere that enter/exit increments/decrements.  I'd even be happy to have a dummy tile somewhere that has the counter on it and link to it somehow to incrrement/decrement something.

Maybe I'm missing something, but is there any way to do what I want?

**Comment by ironmonk88** [comment]
![image](https://user-images.githubusercontent.com/75920956/162288213-f2ddaca8-3d9b-49ba-9b44-d8f8f9121f0f.png)
![image](https://user-images.githubusercontent.com/75920956/162288331-f511dfa4-6f91-4aa1-84e1-32ba5935f658.png)

**Comment by ericloyd** [comment]
That must be a newer version than what I have.  :-)

I suppose I should get moving and update my Foundry from 8 to 9 so I can see what all the new modules are, but I have so much invested in the campaign world and we're so close to the end of a major quest that I don't want to break stuff.  Thanks for this.  I'll go look when I update.

Now I just need to figure out how anchors work....

**Comment by ericloyd** [comment]
For what it's worth, I did a basic work-around that just triggered 33% of the time and called it a day.

**Comment by ironmonk88** [comment]
Closing this as there is a solution available.
