### ISSUE TITLE
Bug: Delay actions

### ISSUE THREAD

**Issue by overdox** [ironmonk88/monks-active-tiles#170]
Hi version 1.0.70 and 1.0.71 seems to have a slight bug with the delay actions function, where they seem to stop all subsequent triggers to occur.
As an example, if I make tile that I will use to trigger three other tiles, lets call them tille 1, tile 2 and tile 3.

This will work just fine. but if I now add a delay of 5 seconds to tile 1, tile 1 will trigger just fine after the 5 seconds delay, but tile 2 and 3 will no longer get triggered.

Including a video that shows the problem in action
https://youtu.be/aFaIc78dcg0

This was however working just fine with version 1.0.69 and earilier versions.

**Comment by ironmonk88** [comment]
So, good news and bad new.  
For some future planned changes, it needs to be switched to this.  And switching it back would break other things.
But, the good news is you can tell Active Tiles to run all of them at the same time you just need to have them all in the same group.  Easiest way is to use the Tagger module, name all the Tiles with the same tag and when you trigger, use tagger.  Second option, if you don't want to use another module is set up a Macro to return the tiles you want to trigger `return {tiles: [array of tile document or array of tile ids]}`.  So you'd run the macro before you run the trigger, and then tell the trigger action to use the current tiles.

**Comment by overdox** [comment]
Alright, that makes sense. Thanks for letting me know.

**Comment by ironmonk88** [comment]
Closing this as there are ways around it.
