### ISSUE TITLE
Bug: Pan Canvas to Player Tokens

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#171]
![image](https://user-images.githubusercontent.com/99844555/164916115-63a9000d-b4d0-4540-9ddd-4ec55e9335f7.png)
Setting Pan Canvas to Player Tokens, saving, and going back to the tile config window causes Pan Canvas to revert to this.

Uncaught (in promise) TypeError: CONFIG[docName] is undefined
[Detected 1 package: monks-active-tiles]
    fromUuid foundry.js:2556
    locationName monks-active-tiles.js:4473
    changeAction action-config.js:600
    activateListeners action-config.js:86
    _render foundry.js:3090
    _render foundry.js:3764
    render foundry.js:3021
    _editAction active-tile-config.js:198
    jQuery 9
    activateListeners active-tile-config.js:173
    _render foundry.js:3090
    _render foundry.js:3764
    render foundry.js:3021
    render foundry.js:4259
    _onClickLeft2 foundry.js:21944
    _onClickLeft2 foundry.js:37285
    callback foundry.js:24252
    _handleClickLeft2 foundry.js:24456
    _handleMouseDown foundry.js:24418
    emit index.js:181
    dispatchEvent interaction.min.js:8
    processPointerDown interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    findHit interaction.min.js:8
    processInteractive interaction.min.js:8
    onPointerDown interaction.min.js:8
foundry.js:2556:24

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
