### ISSUE TITLE
Bug: Chat Message to GM Only

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#173]
Chat Messages are whispering to the Triggering Player even when set to GM Only.

**Comment by GrumpyVader** [comment]
I second this. I was trying to setup passive perception check chat messages to GM Only but they were still showing on the player chat log.

**Comment by ironmonk88** [comment]
This was an odd one that I wasn't expecting from Foundry.  Apparently the sender gets included in the whisper.
Should be fixed in the latest release.
