### ISSUE TITLE
Bug: Toggle Y

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#174]
![image](https://user-images.githubusercontent.com/99844555/165407759-85390fe0-ed35-4e98-b407-27c27f765079.png)

With this setup, the altered token does one of three things when the tile is triggered:

- Gets moved all the way to the edge of the screen. This one more likely after the token is manually moved, but not 100%.
- Nothing. Always follows the above, but still happens on its own sometimes.
- Works as normal

![firefox_G9zQjkkgKH](https://user-images.githubusercontent.com/99844555/165408062-1cf3758b-2d7c-4953-9a93-a2c3bf1f02fc.gif)
.

**Comment by ironmonk88** [comment]
Not really a bug.  Just possibly improperly worded and bad documentation.

You'd want to use `= ({{entity.data.y}} || 0) == 1500 ? 1600 : 1500`.  
Token in this context doesn't mean what you think it means.
I believe token would refer to the triggering token, not the actual entities you requested the action to alter.
