### ISSUE TITLE
FEATURE REQUEST: Randomization..

### ISSUE THREAD

**Issue by galaara98** [ironmonk88/monks-active-tiles#176]
<strike>
- Something like Random 0-X [where the range is allowed to be at least 8] or "roll 1dX" then somehow allow the flow to continue based on the random
--could be hard coded to go to an anchor like _Random## (like: _Random09), but any way you think is good to allow flow control from the random result. </strike>

____
Would it still be possible to add "Random in List" (in addition to "First in List")

**Comment by ironmonk88** [comment]
I think that would be best handled by a Macro.  You could easily write the random logic in the Macro then return `{goto: "RandomAnchor"}` and that would randomly go to an Anchor.  That way you could have full control of how the randomization works, and what you want to call the Anchors.
Not sure it's worth re-inventing something that can already work.

**Comment by galaara98** [comment]
Would it still be possible to add "Random in List" (in addition to "First in List")

**Comment by ironmonk88** [comment]
Updated the `First in List` to be `Position in List` and allowed first, last, and random to be used as position.
