### ISSUE TITLE
Bug: Cycle Images, Set Image

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#177]
Attempting to Set Image # to the last image in a Cycle Image does not work. In this video, clicking the tile to set the image # to 5 sets it to image # 0. Does the same if I lower the image count to 3; then clicking # 3 fails.

https://user-images.githubusercontent.com/99844555/166087431-efe9b50a-cc3b-4bfa-9f54-bfabad36726a.mp4

![image](https://user-images.githubusercontent.com/99844555/166087463-11525f9f-277e-4505-8059-0b01f3ea2d6e.png)
![image](https://user-images.githubusercontent.com/99844555/166087473-bc427e33-ab54-47ce-a52e-98aeb97f21f1.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
