### ISSUE TITLE
Filter by elevation has disappeared

### ISSUE THREAD

**Issue by legionsole2133** [ironmonk88/monks-active-tiles#178]
Hi there,

I'm pretty much a noob when it comes to foundry but I'd been using this module to create holes and traps and it was working perfectly. However, today I went to make a new trap and tried to set it to check elevation is zero as I have a couple of flying party members... but i cant filter by that anymore. When I go to filter by attribute and type in elevation it does not recognise it nor auto complete it as it used to.
Any help will be appreciated.
Cheers

**Comment by ironmonk88** [comment]
It's still there, you just have to type it in. `elevation`
Unfortunately that list is controlled by the system, which I'm guessing is DnD5e, and for some reason they've removed it from the list.

**Comment by legionsole2133** [comment]
Ahhhh I see, thanks!

**Comment by chrisjbrown** [comment]
is it still there? I only see the `action` -> `elevation` but i don't see the `filter by` -> `elevation` option 😕
