### ISSUE TITLE
Bug: Add to Combat "unknown combatant" ("Select an entity"/"Use player tokens")

### ISSUE THREAD

**Issue by ToGreedy** [ironmonk88/monks-active-tiles#183]
I use a trigger tile to add player and npc to combat when one of the players walks into the trigger.
But every time it triggers i only get "unknown combatant" when i use "Select an entity". On the other hand when i use "Use player tokens" they didnt get added at all. 
The only thing that works is "Current token" but for that i need to walk into it with every player and npc, by which the sense of the trigger tile would then be lost for the most part. :(

**Comment by ironmonk88** [comment]
So I can't 100% replicate this.  I tried player characters and they added correctly.  I selected the entity and used a token and it worked fine.
What I did notice is that you could select an Actor when trying to use the Select an Entity... and you shouldn't be able to do that.  Fixed that bug for the next release.

**Comment by ironmonk88** [comment]
Closing this as I can't replicate and there's been no follow up.
