### ISSUE TITLE
Feature Request: Check Entity Count on Tiles

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#189]
Got a request I'm putting in for Zephyr; he'd like to be able to filter by attributes & tags on a specific tile.

Filter by Attributes allows targeting of the tile itself; but not sure if it works, due to the following:
Check Entity Count doesn't allow targeting of tiles at all.

**Comment by ironmonk88** [comment]
At some point it looks like I added this.
Check entity count should allow for additional types.
And Filter by Attributes should allow targeting of the Tile itself.
