### ISSUE TITLE
Bug: Rolltable, Alter, and some special characters

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#190]
![image](https://user-images.githubusercontent.com/99844555/169617878-54d36c03-5e86-4de8-b67c-649861b52411.png)

![image](https://user-images.githubusercontent.com/99844555/169617994-3ddd9ee1-c773-447c-98bc-6d79c23cc8a3.png)

Apostrophes get jumbled when altering text on a drawing using {{value.text.[0]}}.

Edit: did some more testing; guessing this might just be a coding limitation, but I'll add them here anyway.

- & results in _& amp;_ (without the space)
- " results in _quot;_
- < > results in _& lt;_ and _& gt;_ respectively (without the space)

**Comment by ironmonk88** [comment]
That's not really a bug.  That's just how Handlebars does things.
You need to triple wrap for it to output the correct text.
`{{{value.text.[0]}}}`
