### ISSUE TITLE
Bug: Conflict with Ambient Doors

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#194]
https://github.com/EndlesNights/ambientdoors

The "Triggers" section does not appear on newly created doors until the configuration window is opened, closed, and re-opened while this mod is on.
![image](https://user-images.githubusercontent.com/99844555/170549549-e3c39d74-94ec-4b5b-8be2-1e882cfc42c7.png)

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
