### ISSUE TITLE
Bug?: Clicking a Tile Behind a Door Icon

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#196]
Tiles in 5e are clickable through a door icon, but in other tested systems (GURPS, PF1 & PF2) the tiles are not clickable through the door icon.

5e ![5e](https://user-images.githubusercontent.com/99844555/170592735-50ee3dfc-1d18-458e-a02d-6017c278972b.gif)
PF1 ![Pathfinder Tile](https://user-images.githubusercontent.com/99844555/170592737-79d6e930-3579-41e0-bf64-dbdd10b0f5fd.gif)

**Comment by ironmonk88** [comment]
Support for this was added to the latest release.
