### ISSUE TITLE
Bug: Door Triggers & Tagger Support

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#197]
![image](https://user-images.githubusercontent.com/99844555/170790733-5a7de7d5-e8ed-478b-9ee0-48300e8377ab.png)

![firefox_67sl3Ts6Ly](https://user-images.githubusercontent.com/99844555/170790821-7f869be0-ed56-479d-8354-221a5f66d8b3.gif)
With Tagger ^^

![firefox_6dFNrRFTCq](https://user-images.githubusercontent.com/99844555/170791630-8e9296e9-fbdb-43d2-86e1-5035131989ed.gif)
^^ With Select Entity

Doesn't trigger the tile when using the Tagger option.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
