### ISSUE TITLE
integrate with the Module Monk's Token Bar

### ISSUE THREAD

**Issue by eunaumtenhoid** [ironmonk88/monks-active-tiles#199]
would it be possible to integrate with your other mod Monk's Token Bar Module?
for example when clicking on a token it asks for an attribute roll, so it is activated in the Monk's Token Bar Module and shown in the chat

**Comment by ironmonk88** [comment]
It already does.
![image](https://user-images.githubusercontent.com/75920956/170834253-bc469b6f-7f6c-4a77-b192-b99e5d561a3b.png)
