### ISSUE TITLE
Bug: Move Details Window & This Tile

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#202]
![firefox_qg6NNMYLDo](https://user-images.githubusercontent.com/99844555/171505338-a863837b-0fcd-4dec-b3c7-956a7d313c0d.gif)

Getting some really weird results using the move window and "this Tile"

Triggers once in the wrong direction, then won't trigger until the tile is moved manually.

![firefox_7v2wy6KS1u](https://user-images.githubusercontent.com/99844555/171505650-700ce6ed-fedd-4fe9-be57-69b0cd835260.gif)

Works fine with tokens ^

**Comment by ironmonk88** [comment]
I think this is fixed... but it shouldn't be working with the tokens at all.
This will have to wait until the next release to confirm I fixed the correct bug.

**Comment by ironmonk88** [comment]
Okay, latest release is out.
Need to confirm that I got the correct bug fixed.

**Comment by ironmonk88** [comment]
Fixed in latest release.
