### ISSUE TITLE
[Feature Request] Activate Journal Note (to spawn MEJ Encounters)

### ISSUE THREAD

**Issue by That-Italian-Guy** [ironmonk88/monks-active-tiles#203]
Right now I can't find a way to activate the "Start Encounter" function on a MEJ Encounter note that has been dragged onto the battlemap. since you can already spawn a Note with MATT, it would be nice to also be able to activate it.
![image](https://user-images.githubusercontent.com/106380880/171594144-9a4f155f-2c00-422b-894f-a67c20b8ee66.png)

Addendum: it would also be nice to be able to manipulate notes as well as tokens with more actions (mainly to reposition them). That way it would be possible to
- Create Journal Note (with a MEJ encounter);
- Move the Note to a destination/height appropriate;
- Start the encounter by activating the MEJ note.

**Comment by ironmonk88** [comment]
Use the Create Token action, you can select a Journal Entry.  Then follow that up with an Add to Combat action using the current tokens.

Create Journal Note already exists as an action.
Moving the Note already exists, it's just the Move action.

**Comment by ironmonk88** [comment]
Closing as all these actions should exist now.
