### ISSUE TITLE
[Feature Request] Pop-up menu input selection

### ISSUE THREAD

**Issue by That-Italian-Guy** [ironmonk88/monks-active-tiles#204]
Right now you have to select a specific entity (or "wildcard" it by using concepts like "current actors" or "within current tile"). It would be nice to be able to select "pop-up menu" as a selection option.

- When this option is selected, the interface would present a field where entities (like MEJ Encounters, Actors, etc) can be dragged and dropped (or quick searched if more convenient). This would be our "list of options";
- When the tile is triggered and the code reaches this point, the GM (and/or players) would be presented with a pop-up that contains our "list of options";
- Each option should be clickable (if no multi-selection is possible for the type of entity) or there should be checkmarks to enable multi-selection.
- Whenever the GM (and/or players) have confirmed their selection, the code would continue normally (with the selected entities as the target/triggerer/etc).

Case use:
- user input within the execution of the code allows incredible flexibility with minimal preparation (IE: be able to select which one of the MEJ random encounters you have added to the list to spawn within a single tile)

**Comment by ironmonk88** [comment]
This can currently be done with the `Show Dialog` action.
You'll have to put some work in to craft what you want the dialog to look like and what options it has, but allows you more flexibility than just a popup.  And since you can return whatever you wish from the Dialog, you can control what data is being passed.
