### ISSUE TITLE
Bug: Roll Table Quantity not saving when blank

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#206]
Setting the quantity to "blank" doesn't get saved.

https://user-images.githubusercontent.com/99844555/171686330-9592fcba-baf3-4f49-bb4c-0f0d29fd3a90.mp4

**Comment by ironmonk88** [comment]
Well... that's going to be an interesting one.
Technically, it does get saved.  It just adds the default back in when you go to edit it.
Fixed the text in the Tile Config to read properly... just not sure what to do about it resetting to the default the next time you edit it.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
