### ISSUE TITLE
Feature Request: add effect to Show image to players (or journal entry).

### ISSUE THREAD

**Issue by franckflo** [ironmonk88/monks-active-tiles#21]
Thanks for this great Module, It's amazing! Would it be possible to add an effect to be able to show an image or a journal entry to the players? I know we could do this with a macro, but it would be nice to have that effect specifically. Thanks!

**Comment by ironmonk88** [comment]
There's an action to open a Journal Entry.
But I just realized that it only opens for the GM.
Updated the code to be able to select who gets to see the Journal Entry.

**Comment by ironmonk88** [comment]
Latest release should have this fix.
