### ISSUE TITLE
Feature Request: Hover & Click combo triggers

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#210]
To be used with auto-anchors; to have a tooltip or interactive indication go active/inactive on hover in/out, and another set of actions to be triggered on click/double click.

**Comment by ironmonk88** [comment]
Marking this as duplicate as I think at that point it falls under, being able to set multiple triggers.  Rather than combining.

**Comment by Crowguard** [comment]
Gotcha; my bad.
