### ISSUE TITLE
Bug: Create Token (Current Collection)

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#211]
![image](https://user-images.githubusercontent.com/99844555/172018096-7e93c9fa-63ca-42f2-8742-1ffe268ce48b.png)

Creating encounters from journal tables is failing. 

Rolltable with just 2 encounter journals.

These 2 errors with my usual mods on

- TABLE_RESULT_TYPES.ENTITY is deprecated. Please use TABLE_RESULT_TYPES.DOCUMENT instead. constants.mjs:337:13
- game.data.version is deprecated since V9 in favor of game.version foundry.js:5120:17

Meanwhile getting a single different error with just your mods & libwrapper on.

- The 'entities' option for TextEditor.enrichHTML is deprecated. Please use 'documents' instead. foundry.js:44720:15

**Comment by ironmonk88** [comment]
Note to self
![image](https://user-images.githubusercontent.com/75920956/208551348-f4ebe9c8-d260-4948-9b15-6b6044db3247.png)
v10 uses pages now.

**Comment by ironmonk88** [comment]
I think this is already fixed?

**Comment by ironmonk88** [comment]
Fixed in the latest release.
