### ISSUE TITLE
Feature Request: Trigger on Light/Darkness Level

### ISSUE THREAD

**Issue by Gneech** [ironmonk88/monks-active-tiles#215]
Akin to the way sound/light elements etc., can activate or deactivate based on the light level of the scene, have a tile activate/deactivate based on the amount of light hitting it.

(Example use case: a town scene with a tile that causes all items tagged "Daytime" to become visible when darkness is 0-0.74, and hidden when darkness is 0.75-1.)

Alternatively, a hook into the timestamp from Simple Calendar--e.g., "It is a WEEKDAY between 7 AM and 5 PM" would do the trick, but I suspect is probably harder to implement and not as flexible to use.

Thank you! :)

**Comment by roi007leaf** [comment]
+1 for this request, cheers!

**Comment by Eluinn** [comment]
+1 from me as well!! I especially like the idea of syncing with Simple Calendar so shops can have open/closed schedules, people can lock up for the night, or special patrol schedules and etc.

**Comment by Akallabeth13666** [comment]
+1 for this request too :)

**Comment by ironmonk88** [comment]
Closing this as Darkness change and Time change triggers was added awhile ago.
auto landings for value are included.
You can reference the darkness and time values using `value.darkness` and `value.time`
