### ISSUE TITLE
Bug: Active Effects, Pathfinder 2e

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#216]
Error upon triggering and the effect is not added; only active modules are yours, Data Inspector, and FTC.

monks-active-tiles |  TypeError: baseCondition.data.alsoApplies is undefined
    createAdditionallyAppliedConditions https://crowguard.forge-vtt.com/systems/pf2e/main.bundle.js:19
    createConditions https://crowguard.forge-vtt.com/systems/pf2e/main.bundle.js:19
    addConditionToToken https://crowguard.forge-vtt.com/systems/pf2e/main.bundle.js:19
    fn https://assets.forge-vtt.com/bazaar/modules/monks-active-tiles/1.0.79/monks-active-tiles.js:2465
    runActions https://assets.forge-vtt.com/bazaar/modules/monks-active-tiles/1.0.79/monks-active-tiles.js:6916
    trigger https://assets.forge-vtt.com/bazaar/modules/monks-active-tiles/1.0.79/monks-active-tiles.js:6870
    doTrigger https://assets.forge-vtt.com/bazaar/modules/monks-active-tiles/1.0.79/monks-active-tiles.js:7347
    setTimeout handler*doTrigger https://assets.forge-vtt.com/bazaar/modules/monks-active-tiles/1.0.79/monks-active-tiles.js:7345
    <anonymous> https://assets.forge-vtt.com/bazaar/modules/monks-active-tiles/1.0.79/monks-active-tiles.js:7356
    _call https://crowguard.forge-vtt.com/scripts/foundry.js:294
    call https://crowguard.forge-vtt.com/scripts/foundry.js:279
    _preUpdateDocumentArray https://crowguard.forge-vtt.com/scripts/foundry.js:10221
    _updateEmbeddedDocuments https://crowguard.forge-vtt.com/scripts/foundry.js:10152
    update https://crowguard.forge-vtt.com/common/abstract/backend.mjs:153
    updateDocuments https://crowguard.forge-vtt.com/common/abstract/document.mjs:373
    updateEmbeddedDocuments https://crowguard.forge-vtt.com/common/abstract/document.mjs:540
    updateEmbeddedDocuments https://crowguard.forge-vtt.com/modules/enhanced-terrain-layer/terrain-main.js:93
    updateEmbeddedDocuments https://crowguard.forge-vtt.com/modules/enhanced-terrain-layer/terrain-main.js:101
    moveMany https://crowguard.forge-vtt.com/scripts/foundry.js:22502
    _handleMovement https://crowguard.forge-vtt.com/scripts/foundry.js:1141
    _onPan https://crowguard.forge-vtt.com/scripts/foundry.js:1252
    setTimeout handler*_onPan https://crowguard.forge-vtt.com/scripts/foundry.js:1252
    onDown https://crowguard.forge-vtt.com/scripts/foundry.js:861
    _executeKeybind https://crowguard.forge-vtt.com/scripts/foundry.js:1630
    _processKeyboardContext https://crowguard.forge-vtt.com/scripts/foundry.js:1669
    _handleKeyboardEvent https://crowguard.forge-vtt.com/scripts/foundry.js:1707
    KeyboardManager https://crowguard.forge-vtt.com/scripts/foundry.js:1361
monks-active-tiles.js:13:13
    error https://assets.forge-vtt.com/bazaar/modules/monks-active-tiles/1.0.79/monks-active-tiles.js:13
    runActions https://assets.forge-vtt.com/bazaar/modules/monks-active-tiles/1.0.79/monks-active-tiles.js:6974
    trigger https://assets.forge-vtt.com/bazaar/modules/monks-active-tiles/1.0.79/monks-active-tiles.js:6870
    doTrigger https://assets.forge-vtt.com/bazaar/modules/monks-active-tiles/1.0.79/monks-active-tiles.js:7347
    (Async: setTimeout handler)
    doTrigger https://assets.forge-vtt.com/bazaar/modules/monks-active-tiles/1.0.79/monks-active-tiles.js:7345
    <anonymous> https://assets.forge-vtt.com/bazaar/modules/monks-active-tiles/1.0.79/monks-active-tiles.js:7356
    _call https://crowguard.forge-vtt.com/scripts/foundry.js:294
    call https://crowguard.forge-vtt.com/scripts/foundry.js:279
    _preUpdateDocumentArray https://crowguard.forge-vtt.com/scripts/foundry.js:10221
    _updateEmbeddedDocuments https://crowguard.forge-vtt.com/scripts/foundry.js:10152
    update https://crowguard.forge-vtt.com/common/abstract/backend.mjs:153
    updateDocuments https://crowguard.forge-vtt.com/common/abstract/document.mjs:373
    updateEmbeddedDocuments https://crowguard.forge-vtt.com/common/abstract/document.mjs:540
    updateEmbeddedDocuments https://crowguard.forge-vtt.com/modules/enhanced-terrain-layer/terrain-main.js:93
    updateEmbeddedDocuments https://crowguard.forge-vtt.com/modules/enhanced-terrain-layer/terrain-main.js:101
    moveMany https://crowguard.forge-vtt.com/scripts/foundry.js:22502
    _handleMovement https://crowguard.forge-vtt.com/scripts/foundry.js:1141
    _onPan https://crowguard.forge-vtt.com/scripts/foundry.js:1252
    (Async: setTimeout handler)
    _onPan https://crowguard.forge-vtt.com/scripts/foundry.js:1252
    onDown https://crowguard.forge-vtt.com/scripts/foundry.js:861
    _executeKeybind https://crowguard.forge-vtt.com/scripts/foundry.js:1630
    _processKeyboardContext https://crowguard.forge-vtt.com/scripts/foundry.js:1669
    _handleKeyboardEvent https://crowguard.forge-vtt.com/scripts/foundry.js:1707
    KeyboardManager https://crowguard.forge-vtt.com/scripts/foundry.js:1361

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
