### ISSUE TITLE
Issues with Monks Active Tile Triggers and Smart Doors

### ISSUE THREAD

**Issue by Gurrgel** [ironmonk88/monks-active-tiles#217]
Using the latest versions of Foundry VTT (9.269), my system (DnD5e, 1.61) Monk's Active Tile Triggers (1.079) and Smart Doors (1.3.3), I encounter an issue where MATT's abiliity to let doors trigger tiles when opened or closed does not seem to work if the door is Synchronised with other doors through the Smart Doors module. 

For reference, in case you're less familiar with that module, Smart Doors (among other things) lets you synchronise doors into groups, so that opening/closing one will do the same to other doors in the same group. Having Smart Doors installed in and of itself is no issue for MATT, but if a door is synchronised with other doors, interacting with it won't trigger its connected tiles. This is an issue even when the door in question is manually opened, i.e. not opened due to another door in the synchronised group being opened.

The problem remains the same even with no other modules active, and was confirmed by AWizardForHire on the discord as well. 

I've added a similar issue on Smart Door's github as well: https://github.com/manuelVo/foundryvtt-smart-doors/issues/26

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.  Although synchronized doors won't work.
