### ISSUE TITLE
Opening a door deselects token

### ISSUE THREAD

**Issue by Krigsmaskine** [ironmonk88/monks-active-tiles#218]
In DnD5e with Monk's Active Tiles as the sole module on, it deselects a selected token whenever you open a door, both as player and GM.

MATT version: 1.0.79.
DnD5e version: 1.6.1.

**Comment by Co0nmz** [comment]
Same with PF1e

**Comment by ironmonk88** [comment]
Turn off the setting "Allow door click through".
![image](https://user-images.githubusercontent.com/75920956/174420908-eb5fed99-92ac-4930-80b9-d4c2a61978df.png)
You won't be able to click a Tile that's underneath the door, but you also won't deselect a token when clicking the door.
With that setting on there's nothing I can do about deselecting the Token.

Also be aware that using the module "FoundryVTT Arms Reach" will also create the same effect.
