### ISSUE TITLE
Bug: Duplicate/Delete action in PF2e

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#220]
![image](https://user-images.githubusercontent.com/99844555/173898519-ecd7ab66-940f-4f24-b893-320179b6368c.png)
WAY off from its location.

**Comment by ironmonk88** [comment]
Could you run FtC to make sure it isn't a module conflict?

**Comment by Crowguard** [comment]
yeah, I'll check again, but only things active were your mods, Tagger, and Data Inspector

**Comment by Crowguard** [comment]
https://user-images.githubusercontent.com/99844555/174105006-ba0401a7-8fe4-4adf-b163-9042461ae96d.mp4

Foundr9 9.269
Pf2e 3.11.2.6

Only MATT & FTC

**Comment by ironmonk88** [comment]
That looks like a Firefox issue.
It doesn't want to set the bottom property for an inline element.
That's going to be fun to try and fix.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
