### ISSUE TITLE
Bug: Play Sound (Browse Files button)

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#221]
https://user-images.githubusercontent.com/99844555/173942053-0cf267a7-0da1-4635-b41b-b2ac2d1f6916.mp4

Clicking the browse files button on this action when it already has a sound file opens the browsing window twice; it won't update the file location on the first shown window, it has to be selected with the second one.

D&D 5e, only mod on is MATT. On Forge.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
