### ISSUE TITLE
Bug: Roll Table (same bug from Run Macro)

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#223]
![image](https://user-images.githubusercontent.com/99844555/174467403-edc252f2-19ee-4bfc-9236-98ee5d0c3a56.png)

**Comment by ironmonk88** [comment]
Did this get fixed in the latest release?

**Comment by ironmonk88** [comment]
Is this still an issue?

**Comment by Crowguard** [comment]
Nope. I can't get it to occur anymore.
