### ISSUE TITLE
Bug: Starfinder functionality borked. Issues with Roll Request and Redirect Request Results.

### ISSUE THREAD

**Issue by Caboozles** [ironmonk88/monks-active-tiles#224]
Active Tiles functionality currently is bugged with the Starfinder system. When attempting to request active rolls, it's unable to autoroll, and as a result while 'Roll Request' semi-functions and does permit results, it fails to then be read by a Redirect Request Roll, preventing any trigger utilizing them from functioning.

Small notes: 
Macros that function in 5e will not properly replicate in Starfinder.
Possibly related warning?: "game.data.version is deprecated since V9 in favor of game.version."

Game Versions:
Foundry: 9.269 stable
Starfinder: 0.19.1
Monk's Active Tile Triggers: 1.0.82
Monk's TokenBar: 1.0.67

Related images
<img src="https://i.imgur.com/V288Erc.png">
<img src="https://i.imgur.com/KghsVFP.png">
<img src="https://i.imgur.com/tx7mk8S.png">

**Comment by Crowguard** [comment]
Same issue with the 3.5 SRD System.

**Comment by ironmonk88** [comment]
This is 100% to do with the system itself.
They don't provide a way to actually bypass the dialog.
The code is there and ready to go in case they ever implement it though.
