### ISSUE TITLE
Bug report: "Tokens within Tile" in "Select Entity"

### ISSUE THREAD

**Issue by SirZeel** [ironmonk88/monks-active-tiles#225]
When you create a tile with ANY kind of "Action" on the trigger, if you select "Tokens within Tile" in the "Select Entity" section, the tile will activate only from south and east but not from north and west.

Video link: https://youtu.be/fLooCuxu7WA

Edit: update.
Selecting this configuration [as opposed to any other configuration] will solve the issue.
Still a bug tho.

![image](https://user-images.githubusercontent.com/96880264/174670721-7ada05e1-6d99-411e-9cf9-6a606c75dad7.png)

**Comment by ironmonk88** [comment]
I can't replicate this, I have a feeling either I've changed the code enough that it's no longer an issue, or it's just a matter of timing and the Tile is triggering 1 pixel before the token would be considered within the tile.
If it's still an issue, please re-open the ticket and provide an export of the scene involved so I can check.
