### ISSUE TITLE
Issue with the logic

### ISSUE THREAD

**Issue by Akallabeth13666** [ironmonk88/monks-active-tiles#227]
Hi,

Any idea why I cannot specify the amount of items that should be present in inventory?
It works only to check if there is one of given item.

I am trying to check if character has 3 green gems as per attached
![itemcount](https://user-images.githubusercontent.com/95130435/175394128-b8556228-e9f7-4f65-b890-eebff7db1987.JPG)

**Comment by ironmonk88** [comment]
Working as expected.
Check entity count it to primarily see the number of tokens currently being viewed.

So you're getting the tokens that have a green gem, and checking that there are more than three *tokens* with a green gem.  Not if a specific token has more than three green gems.

Next release you can filter by item count.

**Comment by Akallabeth13666** [comment]
Oh ok, thanks! Clear! I will wait for the release then, any idea when? :)

**Comment by ironmonk88** [comment]
Closing as this feature has been added.
