### ISSUE TITLE
Comprehensive User Guide

### ISSUE THREAD

**Issue by rprejean** [ironmonk88/monks-active-tiles#228]
Greetings great mod. Love it. Is there a comprehensive guide that explains Actions, Filters, Logic, Tagger, etc in detail? I've spent a lot of time and use it well. Now I'm trying things that I don't know if I'm doing it wrong or it doesn't work as I expect it. A comprehensive guide would be very useful.

For example, I'm playing with the idea of the PC puts a crystal on a pedistal. If the PC doesn't happen, nothing happens. If they have it, all goes as planned.

Expanding on that, I thought it would be interesting if the PC doesn't have it the PC takes damage and nothing happens. I know how to do all the damage, that's easy. It's the If/Else/Then part that I'm trying to figure out.

**Comment by ironmonk88** [comment]
http://crowguide.wikidot.com/monk-s-active-tile-triggers

https://discord.gg/ySTBcqpZ

**Comment by rprejean** [comment]
THANK YOU!!!
