### ISSUE TITLE
[BUG] Run Macro: cannot select a macro

### ISSUE THREAD

**Issue by Visteus** [ironmonk88/monks-active-tiles#229]
As in the title, I get a "Select Entity" box that acts just like selecting a token/tile/etc for other Actions. Unable to actually run a macro from the trigger.
![image](https://user-images.githubusercontent.com/39381505/175787288-5d52ac56-b659-4d9d-ade7-e4cc82d79c1f.png)

**Comment by ironmonk88** [comment]
![image](https://user-images.githubusercontent.com/75920956/175797190-2e6ac69a-b12c-4172-9098-740bb1764f2f.png)
Click on the Macro folder and select one of the Macros in the list.
