### ISSUE TITLE
[Bug] new tab UI break others tab's Levels module.

### ISSUE THREAD

**Issue by rinnocenti** [ironmonk88/monks-active-tiles#237]
The new tabs UI is hiding other tabs from other modules. (levels for example)
don't show levels tab anymore.
![image](https://user-images.githubusercontent.com/3178127/177705509-07b5c786-e8b3-4bdd-b19a-1f14eba22909.png)

**Comment by ironmonk88** [comment]
I believe this was fixed awhile ago.  Closing the ticket.
