### ISSUE TITLE
Trigger request contested roll (Monks token bar)

### ISSUE THREAD

**Issue by Stembeater** [ironmonk88/monks-active-tiles#238]
The request roll trigger does not work when token enters active tile.

**Comment by ironmonk88** [comment]
It seems to be working for me.

**Comment by Stembeater** [comment]
So is there something I am doing wrong this is on a clean game with only monks active tiles and monks token bar installed.
I have followed instructions based on http://crowguide.wikidot.com/monk-s-active-tile-triggers. 


![trigger1](https://user-images.githubusercontent.com/108875929/177913565-f3509fcd-0ad0-444b-8766-811bf4b34294.PNG)
![trigger 2](https://user-images.githubusercontent.com/108875929/177913568-76be5d3e-45f9-4560-989c-87c9d08a04b6.PNG)
![trigger 3](https://user-images.githubusercontent.com/108875929/177913573-70b1c778-871a-4ed6-a3cd-a34c82631411.PNG)
![trigger 4](https://user-images.githubusercontent.com/108875929/177913579-66bab3b7-9a82-4eba-8b69-028e6c4b5e74.PNG)

**Comment by Stembeater** [comment]
Re did it as i realized 50% trigger hadn't been changed 
![trigger 5](https://user-images.githubusercontent.com/108875929/177914098-67a96f0e-ab60-4bcc-a336-431138db7a03.PNG)
.

**Comment by Crowguard** [comment]
Also having the same issue in my testing. No errors in the console on either GM or player.

D&D 5e 1.6.3
MATT 1.0.87
Tokenbar 1.0.67

https://user-images.githubusercontent.com/99844555/177925172-b982bf2f-c90a-40d3-a7ae-5ca24d6d986e.mp4

**Comment by ironmonk88** [comment]
Closing this as it looks like it's working now.
I suspect I fixed something in Tokenbar, but I can't be entirely sure.
Please re-open if it's still not fixed.
