### ISSUE TITLE
On click not working (resolved)

### ISSUE THREAD

**Issue by powametal** [ironmonk88/monks-active-tiles#24]
Awesome plugin by the way

I know you just added this in the last update but I can't figure out how to make the on click work, can please check this out?

I've set my actions, tile is set to active, 
it doesn't seem to do anything in the console when I click the tile as GM or as a Player

Thanks a lot

![onclick](https://user-images.githubusercontent.com/66213947/127071736-c12442f9-1ba7-40f7-a11f-8a822e3bf536.jpg)

**Comment by ironmonk88** [comment]
You have to press the "Power button" icon from the Tile HUD.
There's a ticket to allow just the Tile to be clicked... but I havn't completed that yet.
Basically On Click, means it won't be triggered by Tokens, but you still have to go to the Tiles layer, right-click to get the HUD and click the "Manually Trigger" button.

**Comment by powametal** [comment]
It worked! I thought I had to click the tile! 

Thank you for the quick answer!
