### ISSUE TITLE
[BUG] "On Enter" trigger does not function when entering an x or y position of "0"

### ISSUE THREAD

**Issue by Wisehowl** [ironmonk88/monks-active-tiles#244]
If an active tile trigger is triggered by the player entering a coordinate whose value is "0" the event will not function.  This happens on scenes with no padding where the token moves LEFT into an active tile on the leftmost column of the scene or UP into an active tile on the topmost row of the scene.  Under the same conditions if the token moves UP OR DOWN into an active tile on the leftmost column or RIGHT OR LEFT into an active tile on the topmost row it will behave as expected.  This issue will also occur when entering the tile set up under the same conditions with the "on enter/exit", "on movement", or "on stop within tile".  This issue does NOT occur on the bottom-most row or the right-most column on unpadded scenes.

Note: On a previous update this only affected scenes that had an unequal height/width.  This now happens on all scenes without padding.

**Steps to Reproduce**

1. Create a scene with no padding
2. Create an active tile with the "on enter" trigger
3. Give the active tile an observable effect
4. Position the active tile on the topmost row or the leftmost column of the scene
5. Spawn a token
6. Move the token LEFT into the tile if the tile's position is on the leftmost column OR move the token UP into the tile if the tile is positioned on the topmost row.

Versions Used:
Foundry: Version 9 (269)
System: Pathfinder 2e (3.12.2.10)

Video:
https://user-images.githubusercontent.com/32818836/178113685-696802f2-af41-46ed-bc25-f7027e4644e7.mp4

**Comment by ironmonk88** [comment]
Closing this as I believe it has been fixed.
