### ISSUE TITLE
[BUG] Brief description of your issue

### ISSUE THREAD

**Issue by Boifuba** [ironmonk88/monks-active-tiles#247]
Foundry V9
No other modules 
GURPS GGA 
i get this error 
![image](https://user-images.githubusercontent.com/21176804/178652253-224651f5-48c2-4826-9165-59abb32dd935.png)
when i'm trying to insert the id on the macro field
![image](https://user-images.githubusercontent.com/21176804/178652311-486efbd8-75fb-4a88-91dd-8d3dfe356cc3.png)

**Comment by SirZeel** [comment]
You might want to edit the title.

**Comment by Boifuba** [comment]
ty
