### ISSUE TITLE
[BUG] Cancelling a Show Dialogue sends you to the "No" landing instead.

### ISSUE THREAD

**Issue by Gurrgel** [ironmonk88/monks-active-tiles#252]
**Describe the bug**
If you have a Tile with the Show Dialogue option, if you press the X to close the window with the Dialogue, MATT treats it as if you had clicked No.

**To Reproduce**
1. Create a Tile with a Show Dialogue action and a Landing for the Yes and No answers.
2. Trigger the tile through whatever mean you set it up to trigger.
3. Press the X to close the dialogue question.
4. Despite not pressing No, you will be sent to the No Landing.

**Expected behavior**
I would expect the Tile's actions to either stop completely, or at least continue from whatever follows the Show Dialogue action.

**Please complete as much of the following information as possible:**
 - Tested in my local Foundry application.
 - Foundry v9.269
 - System D&D 5e v1-6-3
 - Monk's Active Tile Triggers v 1.0.90
 - No console messages.
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.

**Comment by ironmonk88** [comment]
The option to have a close trigger No was added awhile ago.
Closing this ticket.
