### ISSUE TITLE
[BUG] Change Permissions not working

### ISSUE THREAD

**Issue by Richard-Hounshell** [ironmonk88/monks-active-tiles#253]
**Describe the bug**
The action "Change Permissions" is not working when using Tagger to select an actor from its tagged token

**To Reproduce**
1. Tag a token with or without a linked actor sheet
2. Create a trigger action to 'Change Permissions' for the tagged token to 'Observer' for 'Everyone'
3. Fire the triggered action

**Expected behavior**
The permissions for the token's actor sheet should change to 'Observer' for all players or as appropriate based on other options selected.

**Please complete as much of the following information as possible:**
 - Browsers: Chrome and Edge
 - Foundry Version v9.255
 - System D&D5e 1.6.3
 - Module version 1.090
 - Are there any errors in the console? No.
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction? Yes, there was no interactions found.

**Comment by ironmonk88** [comment]
Closing this as I believe it's been fixed.
