### ISSUE TITLE
Bug: Move with Tag as Destination

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#254]
Still something going on with it. The four tiles all have the same tag. No errors. 

Only action is Move to "Tag".

https://user-images.githubusercontent.com/99844555/179447195-a871512a-5eea-4b69-82b6-47e79317d96a.mp4

https://user-images.githubusercontent.com/99844555/179447360-784bee2a-ef33-456c-9b7d-63def2b2d11c.mp4

Foundry 9.269
MATT 1.0.9
D&D 5e 1.6.3
FTC. Just MATT & Tagger

**Comment by ironmonk88** [comment]
Is this still an issue?
If you can replicate it... can you post the scene json?

**Comment by Crowguard** [comment]
Seems to be working as expected now.
