### ISSUE TITLE
Error Popup when used with DF Scene Enhancement

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/monks-active-tiles#255]
A high percentage of the time I switch scenes, I get a popup telling me there's a conflict between your module and DF Scene Enhancement. This is the error:

[W] libWrapper: Potential conflict detected between module DF Scene Enhancement and module Monk's Active Tile Triggers.
Module df-scene-enhance did not chain the wrapper for 'SceneDirectory.prototype._onClickDocumentName'.
🎁console_ui @ libWrapper-notifications.js:90

**Comment by M0nk3yy** [comment]
I've been getting the same notification. I haven't noticed any bad behaviour (yet), so it's just the popup and console warning. I can't get around it by disabling MAT as I'm currently using an FA map that needs it lol.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
