### ISSUE TITLE
[BUG] Diagonal Auto-Landings

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#257]
Diagonals stop at up/down or left/right unless the diagonals are the first actions in the sequence. 

Seems like the opposite of the usual landing rules; but I'm probably missing something.

Incorrect Sequence

![image](https://user-images.githubusercontent.com/99844555/180486111-af6ebe4a-7431-411a-b8be-641711307930.png)

https://user-images.githubusercontent.com/99844555/180486126-4ed13eca-e8ef-4509-a3bc-f1447a274b05.mp4

Correct Sequence

![image](https://user-images.githubusercontent.com/99844555/180486370-f6ec5360-9ba4-4926-8c58-dde7f1b8f471.png)

https://user-images.githubusercontent.com/99844555/180486376-a543b1b7-421f-4301-b9a5-e0308e70b903.mp4

**Comment by ironmonk88** [comment]
It will find the first landing that satisfies the requirement.  So if you put a _up before an _up-left, it's going to trigger before the _up-left because it satisfies the requirements.
I tried replicating the sequences you had here... but it's not firing the way the videos show.
So... maybe it was fixed?

**Comment by Crowguard** [comment]
> It will find the first landing that satisfies the requirement. So if you put a _up before an _up-left, it's going to trigger before the _up-left because it satisfies the requirements. I tried replicating the sequences you had here... but it's not firing the way the videos show. So... maybe it was fixed?

Can't replicate the video anymore either. Mark this closed/fixed I guess?

**Comment by ironmonk88** [comment]
Marking this closed.  If it continues to be an issue, re-open.
