### ISSUE TITLE
Target Player Owned Tokens Within a Tile

### ISSUE THREAD

**Issue by Richard-Hounshell** [ironmonk88/monks-active-tiles#258]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The option to target only player owned tokens, within a tile.

**Additional context**
Useful for traps that should only effect players and not enemies.

**Comment by ironmonk88** [comment]
![image](https://user-images.githubusercontent.com/75920956/198870363-c56965dd-0156-4a33-9798-391a359dbe1b.png)
Already possible.
