### ISSUE TITLE
Expand flow control

### ISSUE THREAD

**Issue by happy-cujo** [ironmonk88/monks-active-tiles#26]
Allow methods to return true/false/Promise (also in macros) that can determine if next function in the stack should be executed or the whole process should terminate earlier.

Introduce new general setting for actions "Terminate process on failure" that will stop the execution if action with this setting enabled results in exception. Probably send Notification to GM when something like this happens.

For macro check if it returns true/false. If return is undefined treat is as true to not break backward compatibility.

Use cases:
- When there is an error during the process due to incorrect state of tokens or other entities (or reference no longer exists),  module catches it and continue it's work. Sometimes it doesn't make sense to continue when one of the first steps fails. Example: don't trigger scene modification when teleportation of token failed.
- With macros we could show a dialog to an user. Then depends on the user selection it would continue it's work, or terminate the process gracefully. Example: teleport tile that executes macro defining the destination. After triggering the tile, a dialog with potential destinations is presented to user. Cancelling the dialog aborts the process.

**Comment by ironmonk88** [comment]
It already does a lot of that.  But I could clean it up.

If a macro returns false it will stop the remaining actions from firing.
And you can set a request roll to stop processing actions on a Pass/Fail.

What I need to clean up is make sure if an action fails, that it fails gracefully and lets the GM know.

**Comment by happy-cujo** [comment]
Ok, after you mentioned it...
 `return await MonksActiveTiles._executeMacro(macro, tile, token, action, userid);`
It's pretty clear. My bad. 

I mean in some cases the scene setup can change (tiles/tokens can be removed) and in those cases it would make sense to not execute the rest of actions when current one (that depends on such tile/token) fails. But maybe you're right and just a proper notification for GM will be sufficient.

**Comment by ironmonk88** [comment]
Closing this as I think the request has been satisfied.
