### ISSUE TITLE
Create Token not keeping info from roll table

### ISSUE THREAD

**Issue by Theopholis** [ironmonk88/monks-active-tiles#260]
IN Version 1.0.25 you could use a roll table followed by the create token and it would create the token from the roll table. For some reason that is no longer working. 
My sequence 
Roll Table (list of characters)
Create Token (Current actor, collection of actors @ a specific location on map)
Open Actor Sheet (current actor, triggering player)
Altar (Token within a tile (from create token), actorlink value: owner)

It won't create the token anymore so it can't complete the rest.

**Comment by Crowguard** [comment]
Can confirm.

**Comment by ironmonk88** [comment]
Fixed in latest release.
