### ISSUE TITLE
[BUG] Chat Message Not Sending to 

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#263]
Chat Message is possibly not sending to all possible recipients when following a Request Roll action. (I'll try to test more after work)
User's screen shows only one message to one player; but two successes.
![image](https://user-images.githubusercontent.com/99844555/182038691-826fdc92-9246-48f4-b05c-53d134c6da49.png)

Pathfinder 1.

**Comment by ironmonk88** [comment]
Fixed in latest release.
