### ISSUE TITLE
[BUG] Trigger Action "Move" does not work between scenes

### ISSUE THREAD

**Issue by nhjjr** [ironmonk88/monks-active-tiles#265]
**Describe the bug**
When the Trigger Action "Move" is used to move a tile on another scene, Foundry throws an error in the console instead of moving the tile.

**To Reproduce**
1. Add a tile with the Trigger Action "Move"
2. Set "Select Entity" to an entity on another scene (either by manually entering the scene/tile ID, or using the 'Select an Entity' button)
3. Select some coordinates different from those of the previously selected entity
4. Activate the tile to receive the error

**Expected behavior**
The tile set in the "Select Entity" box is supposed to move to the indicated coordinates on its own scene.

**Please complete as much of the following information as possible:**
 - Browser: Firefox
 - Foundry Version: v9 build 269
 - System: Call of Cthulhu 7th Edition (Unofficial) v0.7.11
 - Module version: 1.0.90
 - Are there any errors in the console: yes, see additional context below
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: No, because MATT is the only module currently enabled

**Additional context**
The following error trace is shown in the F12 console:

```
monks-active-tiles.js:14 monks-active-tiles |  TypeError: Cannot read properties of null (reading 'w')
    at TileDocument.fn (monks-active-tiles.js:615)
    at async TileDocument.runActions (monks-active-tiles.js:8088)
    at async TileDocument.trigger (monks-active-tiles.js:8035)
error	@	monks-active-tiles.js:14
TileDocument.runActions	@	monks-active-tiles.js:8153
async function (async)		
TileDocument.runActions	@	monks-active-tiles.js:8070
TileDocument.trigger	@	monks-active-tiles.js:8035
manuallyTrigger	@	monks-active-tiles.js:8347
dispatch	@	jquery.min.js:2
v.handle	@	jquery.min.js:2
```

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
