### ISSUE TITLE
Switch Tile Image not interfacing with Levels and/or Better Roofs

### ISSUE THREAD

**Issue by abominablerob** [ironmonk88/monks-active-tiles#266]
I have noticed that the switch tile image trigger doesn't function properly when the Levels module is active. Is it possible to allow these modules to function together?
When used with Levels, switch tile image does not immediately change the image. Instead it disappears until another tool or tile is selected (as gm this always seems to work, but only once or twice as a players) or foundry is refreshed (always works).

**Comment by Benethor92** [comment]
Yes, i have the same issue. Cant get it to work at all, tiles are allways disappearing, not changing or not responding at all. Works fine on an emtpy canvas

**Comment by Zilandrix** [comment]
unsure if this is the same issue, but when I use multiface tiles it works only when the GM is in the screen. This is a major issue, as I am using triggers for a menu system. Creating as book with a "page turn" trigger. 

Is there any way around this? Or something I'm missing? I even have "Allow Players" avticve to allow them to inte4ract with no GM, but it doesnt work.

**Comment by Crowguard** [comment]
@Zilandrix That's a new security thing Foundry pushed as part of 9.280. Its #286. No clue if mods will be able to work around it or not.

**Comment by ironmonk88** [comment]
Fixed in latest release.
