### ISSUE TITLE
Feature Request: MEJ Roll Table Logging

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#268]
A new action, to be used with Roll Tables; when following a rolltable, it will log the results to a specified MEJ entry.

**Comment by ironmonk88** [comment]
Sort of added this.
I've given you an action to append text to a Journal Page.  And it uses the same handlebar options that other fields get, so you should be able to build the text from previously rolled tables.

**Comment by ironmonk88** [comment]
This is part of Enhanced Journals and will be released when that's updated.

**Comment by ironmonk88** [comment]
Closing this as I believe MEJ has been updated?  If not... it will be at some point.
