### ISSUE TITLE
Tiny Petition to add an option to open the Party Inventory window from the Party Inventory Module.

### ISSUE THREAD

**Issue by bklick** [ironmonk88/monks-active-tiles#269]
**Is your feature request related to a problem? Please describe.**
I am trying to create a robust landing page for my players, and one of the things I'd like to do is give them trivially easy access to their party inventory. I am using the Party Inventory module, here: 
https://github.com/teroparvinen/foundry-party-inventory

**Describe the solution you'd like**
I'd love to be able to open the module's Party Inventory window via an active tile in MATT. 

**Additional context**
The module recently added an API for opening this window, which I think might help?
**https://github.com/teroparvinen/foundry-party-inventory/commit/ddd19c32ceb231d52efe36204eafcb8d0e9cdb78**

I mentioned this in Discord and you said I should ask here. :) Love everything you do!

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
