### ISSUE TITLE
[BUG]? Play Sound & Restrict to Scene

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#270]
The Play Sound action is not restricting the sound to the scene.

Edit: Both player side and GM side.

![image](https://user-images.githubusercontent.com/99844555/185228231-ef75a85c-a3f9-49ab-aa4b-95d6f679d2e3.png)

MATT 1.0.9
Foundry 9.269
D&D 5e  9.163

**Comment by ironmonk88** [comment]
Fixed in latest release.
