### ISSUE TITLE
[BUG] Change from previous behavior. Change Tile Image

### ISSUE THREAD

**Issue by mazirian** [ironmonk88/monks-active-tiles#272]
I am not sure which release changed this behavior but I am going to try and explain this the best I can.

In the past there was the option to set a tiles image to a specified image by providing a path to the new image.  under the new options the only option is to either cycle between images specified within the times images tab or go to a specific image specified within the tile.

Why this matters:
In my use case I setup a Theatre of the mind scene that has a 10x9 area that I would switch to a small random battle map triggered by double clicking on another hidden tile on the scene. For this I did use the cycle through tile images feature and this still mostly works (problem I face to follow).  I then had another hidden tile I could trigger to set the image to a blank image.  This blank image was not part of the tile images because I did not want it to be one of the random options.

With the current trigger options this setup is no longer working as well. Yes I can set on of the images to a blank tile and create the trigger to pick that specific entry, but the trigger to do the random picking will also choose this blank image at times and when the list is small it can be quite frequent.

Screenshot of the setup to hopefully make the description more clear.
![example_1](https://user-images.githubusercontent.com/1999902/185804846-88d1cc0c-5744-4894-a516-c8203e06155d.jpg)

**Comment by ironmonk88** [comment]
Have you tried `Alter`
![image](https://user-images.githubusercontent.com/75920956/185805430-0bc24122-6d07-4018-af68-a652aeb22c68.png)

**Comment by mazirian** [comment]
That is a workable solution. I overlooked it. 
Thank you!

**Comment by ironmonk88** [comment]
Closing this as I think a solution was found.
