### ISSUE TITLE
[BUG] Teleport to off-scene Tag

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#276]
Teleporting to an off-scene Tag using "all scenes" is failing. 

Zephyr's error screen. 
![image](https://user-images.githubusercontent.com/99844555/187572381-50bf7f46-9dc4-4cd0-8800-0f3d2eade34c.png)

The error I get when attempting. monks-active-tiles |  TypeError: dest.x is undefined
![image](https://user-images.githubusercontent.com/99844555/187572524-edd2803e-f564-4468-b391-606033c0b333.png)

MATT 1.0.9
5e 1.6.3
Foundry 9.280
FTC ✔️

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
