### ISSUE TITLE
[FR] Make links to sub-pages of journal entries also usable for trigger targets

### ISSUE THREAD

**Issue by wickermoon** [ironmonk88/monks-active-tiles#277]
**Is your feature request related to a problem? Please describe.**
With the new journal system, it is now possible to create sub-pages for journal entries. That is a nice way to organize journal entries. Unfortunately, MATT cannot use direct links to these pages, but only to the overall journal entry.

**Describe the solution you'd like**
I'd love it if I could simply link to the sub-page of a journal entry. :)

**Additional context**
![image](https://user-images.githubusercontent.com/15907070/187811558-efd39766-745a-4d5c-9277-9f9a325b8aad.png)
For a better explanation: On the left is a new journal entry with sub-pages, on the right is the old single-page journal entry I'm currently using. On the far right you can see the directory structure of the journal entries (old and new)

**Comment by ironmonk88** [comment]
Closing this as I believe it's been implemented.
