### ISSUE TITLE
[BUG] Monk AActive Tiles not working with Levels in v.10

### ISSUE THREAD

**Issue by danil0man** [ironmonk88/monks-active-tiles#279]
**Describe the bug**
IF i have a map that use levels together with monk active tiles I am getting this error on the console and is not showing me the map at all. This is in version 10. IT was working fine in version v.9

**Expected behavior**
It would show the map and it would work together with levels

**Screenshots**
![image](https://user-images.githubusercontent.com/72052103/187904034-d4adaa09-ca56-4e0f-8796-50bfa2a4322c.png) Console Errors
![image](https://user-images.githubusercontent.com/72052103/187904587-504498ec-6fe5-458b-a7fa-e8d8cb76284e.png) How the map looks

 - Browser Brave Chromium
 - Foundry Versionv.10 build 283
 - System Warhammer Fantasy Roleplay 4th Edition 6.1.1
 -  Monk Active Tile Triggers 1.0.91
 - Levels 3.0.9.1
 -IS an interaction between levels and Monk active tiles. It works in other maps that don't have levels

**Additional context**

**Comment by lucasmiranda2711** [comment]
Levels has to be accessed through CONFIG.Levels.API now, the documentation:
https://theripper93.com/wiki/index.php/Levels#API

**Comment by danil0man** [comment]
Levels is working without trouble. what is not working is levels together with Monk Active Tiles

**Comment by lucasmiranda2711** [comment]
> Levels is working without trouble. what is not working is levels together with Monk Active Tiles

Sorry, it seems I haven't made myself clear, Levels is working indeed, but v10 of levels changes it's way of accessing a few methods, for example this line of monk tiles:

           ` if (game.modules.get("levels")?.active && _levels && _levels.isTokenInRange && !_levels.isTokenInRange(token, tile._object))`

should be changed to:

            `if (game.modules.get("levels")?.active && CONFIG.Levels.API && CONFIG.Levels.API.isTokenInRange && !CONFIG.Levels.API.isTokenInRange(token, tile._object))`

**Comment by Zetzaro** [comment]
Hi, getting a similar problem on token movement. Can still see the canvas but moving a token sends a console error: 
![image](https://user-images.githubusercontent.com/112820612/188324685-6d867a98-44ca-4eda-bcfe-0a23d33cef97.png)

**Comment by ironmonk88** [comment]
This should be fixed now.
