### ISSUE TITLE
RequestRoll preset resets after attempt to add token to roll

### ISSUE THREAD

**Issue by happy-cujo** [ironmonk88/monks-active-tiles#28]
FVTT: 0.8.8
DND5e: 1.4.1
Mon's Active Tiles: 1.0.21

Steps to reproduce:
1. Create an active tile that Request Roll.
2. Configure the roll. Do not disable configuration dialog.
3. Trigger the tile.
4. Select different token and try to add it to the roll

Expected:
Token is added and RequestRoll configuration stays untouched.

Actual:
RequestRoll form resets. It's setup is gone. Token is added.

Notes:
Also it seems that the new instance of RequestRoll that show up after adding token is cached somewhere, because after few tries with different tokens, form is showing all tokens added until now.

https://user-images.githubusercontent.com/15898113/128092172-88e25c1b-0b3e-4a5c-9561-bcb158f31df0.mp4

**Comment by ironmonk88** [comment]
Is this still an issue?
I tried to replicate it, but the values aren't reset for me.

**Comment by happy-cujo** [comment]
Yeah. I've narrowed the modules only to the ones from you. 
```
Active Modules:
----------
Monk's Active Tile Triggers v1.0.24;
Monk's Little Details v1.0.35;
Monk's TokenBar v1.0.49;
Tidy UI - Game Settings v0.1.24;
```

Here's what I get:
## Scenario 1.
0. Load foundry, don't do anything else.
1. Setup Request Roll for tile (like in video)
2. Trigger the tile
3. Try to add other token to Request Roll.

Result
In console (sometimes I need to try to add the token second time) I'm getting error like this:
```
Uncaught TypeError: (intermediate value).system.savingthrow is undefined
    changeTokens savingthrow.js:106
    jQuery 10
    activateListeners savingthrow.js:209
    _render foundry.js:2070
    call_wrapped libWrapper-wrapper.js:465
    <anonymous> listeners.js:75
    _render#0 libWrapper-wrapper.js:160
    render foundry.js:2004
    fn monks-tokenbar.js:279
    trigger monks-active-tiles.js:2251
    doTrigger monks-active-tiles.js:2405
    setTimeout handler*doTrigger monks-active-tiles.js:2403
    <anonymous> monks-active-tiles.js:2415
    _call lib-wrapper.js line 1 > eval:4
    call foundry.js:179
    _preUpdateDocumentArray foundry.js:8790
    _updateEmbeddedDocuments foundry.js:8728
    update backend.mjs:153
    updateDocuments document.mjs:366
    updateEmbeddedDocuments document.mjs:532
    moveMany foundry.js:19708
    _handleMovement foundry.js:812
    _onMovement foundry.js:781
    setTimeout handler*_onMovement foundry.js:781
    _handleKeys foundry.js:558
    _handleKeys main.js:93
    _onKeyDown foundry.js:511
    KeyboardManager foundry.js:335
    initializeKeyboard foundry.js:4452
    setupGame foundry.js:4292
    _initializeGameView foundry.js:5117
    _initializeView foundry.js:5093
    initialize foundry.js:4202
    call_wrapped libWrapper-wrapper.js:465
    libWrapperInit libWrapper-api.js:659
    initialize#0 libWrapper-wrapper.js:160
    <anonymous> foundry.js:53180
    async* foundry.js:53162
```
For the test I'm using actor from starting heroes, but other monsters behave the same.

## Scenario 2
1. Setup Request Roll for tile (like in initial video)
2. Open up the Request Roll from the Token Bar, and close it
3. Trigger tile
4. Try to add other token to Request Roll.

Result
I'm getting exactly the same behavior as in the video. The token is added, but the Request Roll setup resets.

**Comment by ironmonk88** [comment]
This would technically be a Tokenbar issue, but the code that was causing an error no longer exists.
I couldn't replicate it following your steps.

Can I ask again if this is still an issue?

**Comment by happy-cujo** [comment]
I'm no longer using a foundry. It the code is not there and replication did not show similar results I think we can close this issue.
