### ISSUE TITLE
[BUG] v10 Scrolling Text

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#283]
Scrolling text is no longer attached to the token in v10; it stays on the canvas where it was triggered if the token moves afterward.

v9 
![firefox_40TvR3PrDs](https://user-images.githubusercontent.com/99844555/187991984-d4aa7b66-d392-48ce-8b2b-6eaf4e0fd333.gif)

v10
![Foundry_Virtual_Tabletop_y6wxqRd2Zx](https://user-images.githubusercontent.com/99844555/187992025-40408f0d-4d22-45f0-97be-f1779a5d184d.gif)

**Comment by ironmonk88** [comment]
That... is a Foundry issue.  :-(
