### ISSUE TITLE
[BUG] v10 Reording Actions

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#284]
![Foundry_Virtual_Tabletop_B7zIcavsMR](https://user-images.githubusercontent.com/99844555/187996229-8dff3545-805d-4467-a458-00bb4e37f740.gif)

![image](https://user-images.githubusercontent.com/99844555/187996303-c007df45-4c5e-4bf1-895a-b43c9bd91175.png)
Sometimes it works, sometimes it doesn't.

**Comment by Crowguard** [comment]
Still occurring. Its only on newly created tiles that haven't been saved yet.
![image](https://user-images.githubusercontent.com/99844555/189547477-32c63062-5c11-4f9b-b031-b053051c8837.png)

**Comment by ironmonk88** [comment]
This should be fixed now.
