### ISSUE TITLE
[BUG] v10: It breaks core "Move along measured ruler" functionality

### ISSUE THREAD

**Issue by paranoicsan** [ironmonk88/monks-active-tiles#288]
**Describe the bug**
"Move along measured ruler" action is broken. It raises an error in console and does nothing.
```javascript
Uncaught (in promise) TypeError: this._getRaysFromWaypoints is not a function
    at Ruler.moveToken (monks-active-tiles.js:1719:33)
    at Ruler.moveToken (monks-active-tiles.js:1765:38)
    at Object._onMeasuredRulerMovement [as onDown] (foundry.js:1620:13)
    at KeyboardManager._executeKeybind (foundry.js:2097:66)
    at KeyboardManager._processKeyboardContext (foundry.js:2136:33)
    at KeyboardManager._handleKeyboardEvent (foundry.js:2174:10)
    at foundry.js:1823:54
```

**To Reproduce**
1. Activate a Ruler with `ctrl`
2. Hold the left mouse button and drag the pointer
3. Do not release the button - press `space`
4. Nothing will happen and error will arise

**Expected behavior**
Token should move following the ruler

**Screenshots**
![Animation](https://user-images.githubusercontent.com/784577/188230107-e4a6a510-f8c3-4037-aac8-e63af1e12895.gif)

**Please complete as much of the following information as possible:**
Electron application
![image](https://user-images.githubusercontent.com/784577/188229640-d715528c-50b9-4e62-bddd-fda2e82661d9.png)

**Comment by Crowguard** [comment]
Can confirm. Still of the error 
![image](https://user-images.githubusercontent.com/99844555/188233679-40b4dbd5-636f-410d-861d-a2f094dc1c00.png)

**Comment by BinarMorker** [comment]
Hey there! Not sure about how the code is supposed to work too much, but the fix I did seems to work well enough.

**Comment by paranoicsan** [comment]
Can confirm the fix by @BinarMorker works! But [raises another error in console](https://github.com/ironmonk88/monks-active-tiles/pull/294#issuecomment-1236368249) 😬

**Comment by ironmonk88** [comment]
This should be fixed now.
