### ISSUE TITLE
Can't open Create or Edit action with no actor/token on scene

### ISSUE THREAD

**Issue by Smoldar-og** [ironmonk88/monks-active-tiles#29]
A error is generated on the console whenever you attempt to enter the edit or create new action if there is no actors/tokens on the active canvas. Not really a error or bug per say, but can be kinda confusing.

Uncaught TypeError: Cannot read property 'data' of undefined
    at new ActionConfig (action-config.js:8)
    at ActiveTileConfig._editAction (active-tile-config.js:124)
    at HTMLAnchorElement.dispatch (jquery.min.js:2)
    at HTMLAnchorElement.v.handle (jquery.min.js:2)

**Comment by ironmonk88** [comment]
Fixed this issue.
To populate the typeahead for the Alter action I grab the available properties from a Token.  If there wasn't any Token available it was generating this error.
