### ISSUE TITLE
[BUG] Door triggers not working correctly in v10

### ISSUE THREAD

**Issue by voodoofrog** [ironmonk88/monks-active-tiles#295]
**Describe the bug**
When using a door to trigger a tile, nothing is happening.

**To Reproduce**
1. Create/activate a scene,
2. Setup an active tile with an action in the scene.
3. Add a door to the scene.
4. Setup an "On Open Door" trigger on the door and link to the tile.
5. Open the door.

**Expected behavior**
The tile should fire it's actions when the door is opened.

**Please complete as much of the following information as possible:**
 - Browser: Firefox
 - Foundry Version: v10.284
 - System: D&D5e
 - Module version: 1.0.91
 - Are there any errors in the console: No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: No

**Additional context**
When debugging, I noticed that at line 1360 it's trying to optionally chain a `document` property from the `wall` object, however no such property exists. Changing this to just pass the `wall` object itself to `triggerDoor` seems to correct the issue.

**Comment by Crowguard** [comment]
The only chat message that will trigger here is _doorlock, and it only triggers on checking the lock, not on actually locking the door. The _dooropen will trigger when attempting to right-right to lock an open door.

![image](https://user-images.githubusercontent.com/99844555/188701531-d2f7ddb6-448b-4c7a-8047-6497f2a0f305.png)

![image](https://user-images.githubusercontent.com/99844555/188704357-18b00543-bb82-43d9-9cb8-0c44c24e1ce8.png)

**Comment by ironmonk88** [comment]
This should be fixed now.
