### ISSUE TITLE
[BUG] v10. Tile History Window appearance

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#296]
![image](https://user-images.githubusercontent.com/99844555/188325210-878eb5ba-a742-4881-9d97-cb968253b472.png)

Electron app ^ . Browser is normal.

![image](https://user-images.githubusercontent.com/99844555/188325482-c3eb2226-afca-42ee-b241-8f1622f00109.png)

![image](https://user-images.githubusercontent.com/99844555/188325229-60ff2d1a-aff2-4792-8312-38b57735e7b8.png)

**Comment by ironmonk88** [comment]
This should be fixed now.
