### ISSUE TITLE
[BUG] v10. Combat Triggers

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#297]
All trigger methods fail to activate.

![image](https://user-images.githubusercontent.com/99844555/188326302-3eeaee6b-9d09-45f4-ac6c-653a75986e94.png)

Combat Start, Round Start, Turn Start ^

![image](https://user-images.githubusercontent.com/99844555/188326489-7088d8f6-e291-431a-8882-395b516d105f.png)

Combat Turn End ^

![image](https://user-images.githubusercontent.com/99844555/188326509-170ae23d-7df3-412d-8f0c-4132f7dfe0f1.png)

Combat End ^

![image](https://user-images.githubusercontent.com/99844555/188707386-8a2f2641-eab5-43d5-b610-fd42e4469e30.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
