### ISSUE TITLE
[BUG] v10. Attack

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#299]
Attack card is created, but has this warning. Can't test the MIDI part yet.

![image](https://user-images.githubusercontent.com/99844555/188351743-3393052a-4e16-4e78-b902-5d4b8d553b29.png)

![image](https://user-images.githubusercontent.com/99844555/188707002-d6d709c4-474d-4cba-bbc2-bcd2c1f802a7.png)

**Comment by ironmonk88** [comment]
This should be fixed now.
