### ISSUE TITLE
No triggering of effects when token enters from a non-snapped edge

### ISSUE THREAD

**Issue by tagnullde** [ironmonk88/monks-active-tiles#3]
After playing with this module for a couple of minutes I noticed some strange behavior.

I created a tile with these settings:
![image](https://user-images.githubusercontent.com/44159008/122878264-d8ddab00-d337-11eb-81e5-ffee5b1a512b.png)

When trying to trigger the effects it works just from a specific direction:
![not-triggering](https://user-images.githubusercontent.com/44159008/122882818-daf63880-d33c-11eb-9ada-b62635073fa2.gif)

After a bit of troubleshooing it seems like it can't handle non-square tiles. See the next gif for reference. It only works from "grid-snapped edges by the looks of it.
![grid](https://user-images.githubusercontent.com/44159008/122883854-ded68a80-d33d-11eb-8e5a-43de38012467.gif)

**Comment by ironmonk88** [comment]
Are there any errors in the console?
DnD5e?
It's functioning properly on my machine.  With non-snapped and non-square.

**Comment by tagnullde** [comment]
Yes. 5e, Newest version of System,Foundry and Module.
No errors on the console. 

When the token moves through the tile without teleporting, I get these messages:
![image](https://user-images.githubusercontent.com/44159008/123001146-b20f8b00-d3b0-11eb-904c-fa591ced3ba2.png)

And this when it teleports:
![image](https://user-images.githubusercontent.com/44159008/123001242-ce132c80-d3b0-11eb-97ff-8771c6c8b9d5.png)

I also noticed that the tile notice the changes without updating the tile first.
![no-setting](https://user-images.githubusercontent.com/44159008/123001773-627d8f00-d3b1-11eb-9d83-8223511153e4.gif)

I had a similar issue once where it saved the teleport location but not the checkmark in the "activate" checkbox.

**Comment by ironmonk88** [comment]
I think I just randomly stumbled into being able to replicate this.
The tile has to be a very specific size, and I believe the token, due to grid snapping, can just sneak into the tile without triggering it.  I think the token is landing right on the border in between moves.

As for the second one, it's a bit of a Foundry issue I'm trying to work around.  Saving the action, redraws the Tile Config, and it's not retaining any previous information if it hasn't been saved.

**Comment by tagnullde** [comment]
I updated to the latest version of your module. it seems to work a bit better (not sure if you actually put some fixes in the last update). But my token can still run through some parts without a trigger triggering.

**Comment by ironmonk88** [comment]
How close to the corner or edge were they?
You might need to play with the size of the Tile.
Due to various reasons, the actual edge used is just inside for On Enter and just outside for On Exit.

**Comment by ironmonk88** [comment]
Closing this as the triggering process has changed.
