### ISSUE TITLE
[BUG] v10. Show Dialog

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#301]
Seems to work fine. Console warning
![image](https://user-images.githubusercontent.com/99844555/188353551-3962ffe5-461a-492e-9e56-51565dae11b7.png)

**Comment by Crowguard** [comment]
Closing this. No longer there after reinstalling MATT.

**Comment by Crowguard** [comment]
It wasn't fixed, I just forgot to select a dialog option and click Yes. 

![image](https://user-images.githubusercontent.com/99844555/188706569-2b057a83-08fa-40d7-beb9-87681aba7235.png)

**Comment by ironmonk88** [comment]
This should be fixed now.
