### ISSUE TITLE
[BUG] v10. Trigger Tile

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#303]
Doesn't seem to work at all.
![image](https://user-images.githubusercontent.com/99844555/188355123-66855778-6f63-49e3-a03b-bfe795a673f9.png)

**Comment by everyonecancode** [comment]
Can confirm. Have the same error when trying to "Add" action into the tile.

Steps to reproduce:
1. Create an empty tile
2. Go to "Triggers"
3. Select "Actions"
4. Press "Add"

Expected result:
New action is added, allowing GM to select an action

Actual result:
Nothing happens, an error shown in the post above is displayed in console logs.

**Comment by everyonecancode** [comment]
UPDATE:

Probably as many users I have forgotten to update module AGAIN after migrating to V10. Updating module seems to have fixed this issue.

@Crowguard  Please check if updating modules fixes your reported issues.

**Comment by Crowguard** [comment]
> UPDATE:
> 
> Probably as many users I have forgotten to update module AGAIN after migrating to V10. Updating module seems to have fixed this issue.
> 
> @Crowguard Please check if updating modules fixes your reported issues.

I had, but uninstalling and reinstalling it did fix it. Either way, appreciated, and now I need to retest all these other issues from my previous testing.

**Comment by Crowguard** [comment]
Closing this for now, since it seems to be fixed.
