### ISSUE TITLE
[BUG] v10. Filter by Attributes

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#304]
Doesn't work when using 5e actor attributes. Does work when using token attributes.

![image](https://user-images.githubusercontent.com/99844555/188705891-06289d5e-1447-4a79-be49-de21aaafadf8.png)

![image](https://user-images.githubusercontent.com/99844555/188705907-f1b19fdb-8127-47e8-970b-2d41b28f82b5.png)

**Comment by ironmonk88** [comment]
This should be fixed now.
