### ISSUE TITLE
[BUG] V10. Run Batch

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#306]
Not working with this setup. No errors. 

![image](https://user-images.githubusercontent.com/99844555/188357332-4c28bb1f-3862-4352-940a-ea88fe45ae2f.png)

https://user-images.githubusercontent.com/99844555/188357291-14557e41-fe60-45a2-8258-c0c15fbda8c2.mp4

![image](https://user-images.githubusercontent.com/99844555/188703968-69b8084a-a2aa-44a8-9e42-18a4f31ee589.png)

**Comment by ironmonk88** [comment]
It's technically doing exactly what you asked.
Essentially you asked it to move up, then down, so the sum total is no movement.
You'd need the Run All Batch Actions to be in between the two actions.

**Comment by Crowguard** [comment]
I should have used a trigger method other than On Enter for my video, it makes it hard to notice. if you watch the second half of it where the token enters from the side, it moves up one grid despite the batch.

I can't replicate this now, so I'm assuming it was a bug that got fixed with Foundry's last update.
