### ISSUE TITLE
[BUG] v10. Trigger Tile from Journal Macro

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#307]
```
canvas.background.get("DUMqSPH87BHzrrJi").document.trigger({});
Tagger.getByTag("testing")[0].trigger({});
```
No longer works. 
![image](https://user-images.githubusercontent.com/99844555/188358658-3a434a2f-0a09-49df-bc43-d23bbb6ed434.png)

**Comment by ironmonk88** [comment]
That's a Foundry change.
`canvas.background` no longer exists it's `canvas.tiles`

**Comment by Crowguard** [comment]
Appreciated & noted. Can close this I guess.
