### ISSUE TITLE
Request: Play Sound - Scene Option

### ISSUE THREAD

**Issue by ignorantcave** [ironmonk88/monks-active-tiles#31]
Using trigger to Play Sound for Everybody, plays sound for Everybody, through scenes. 
 Other options are for the Player or GM. 
Is it possible to have an option that limits the sounds to those on the same scene, whether current or a specific scene?

This could have application of something happening in one scene trigger a sound for another scene other players may be on.  Or to limit noise to one scene, while players in other scenes would be oblivious.

**Comment by ironmonk88** [comment]
Good suggestion.
Should be available in the latest release.
