### ISSUE TITLE
Support JournalPageEntries and Anchors in Open a Journal

### ISSUE THREAD

**Issue by wickermoon** [ironmonk88/monks-active-tiles#312]
**Is your feature request related to a problem? Please describe.**
With v10, it is now possible (and almost mandatory) to have pages (and anchors) for journal entries. These pages contain the actual content of a journal entry and can be used to organize content. With the current "Open a Journal" action, it is only possible to utilize this with some effort (copy-pasting the correct JournalEntry.JournalPageEntry#anchor ID).

**Describe the solution you'd like**
I the action to also support pages (and achors). For this, I would like to have a drop-down of all the pages that belong to a selected journal entry.

**Additional context**
I have already worked on a solution that is easy-to-use for users and would like to have feedback on it. See the associated pull request for more information on that.

**Why my own solution?**
I totally understand that developers of modules have a lot on their plate. I want to gain some insight in module creation, so creating my own features for an already existing module helps me achieve that. At the same time I can take some work off the developer, while adding to the module's functionality.

**Why THAT solution?**
In my opinion, it is bothersome for the user to first select a journal entry, then open it and selecting a journal entry page. In some cases, the user will even have to scroll down, if the default journal page has a lot of anchors. At the same time, it would be theoretically possible for a user to select journalentry A, but then select page of journalentry B. While that makes no sense, I have learned that users never make sense, when using a software.

With my solution, the user only needs to select the journal entry. The page selection will then self-populate with valid journalpageentries. The anchors must currently be hand-written, but I want to get around to also self-populating these, eventually.

**Comment by ironmonk88** [comment]
Fixed in latest release.
