### ISSUE TITLE
[BUG] running a macro with advanced-macro produces error

### ISSUE THREAD

**Issue by wickermoon** [ironmonk88/monks-active-tiles#315]
**Describe the bug**
The "Run Macro" action is handled differently when you have advanced-macro installed. This extra code tries to call "callScriptFunction" which has been removed by advanced-macro, in favour of using execute directly. Running a macro with advanced-macro installed is therefore currently not possible.

**To Reproduce**
1. Have advanced-macro installed and active
2. Create a "Run Macro" trigger
3. Activate trigger

**Expected behavior**
No error.

**Screenshots**
![image](https://user-images.githubusercontent.com/15907070/189259738-c1e1cb97-dbd9-4986-b6b4-20bbafc446d1.png)

**Please complete as much of the following information as possible:**
 - Browser chrome
 - Foundry Version v10 latest
 - System d&d5e 2.0.2
 - Module version: latest

**Additional context**
I've already fixed the problem in PR #314

**Comment by ironmonk88** [comment]
This should be fixed in the latest release.
