### ISSUE TITLE
[BUG] v10. Move action

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#316]
![image](https://user-images.githubusercontent.com/99844555/189430372-bcf9915a-dfcc-4bf2-b6f9-73936a46c4cb.png)

The action fails and logs this in the console. 
![image](https://user-images.githubusercontent.com/99844555/189430302-fb4ec29e-664b-4ae4-bc71-0d53aaa87f69.png)
Tried with coordinates and original destination.

![image](https://user-images.githubusercontent.com/99844555/189430448-889c84ab-89e5-46b6-8729-61b28bad84c2.png)
Just MATT & MEJ

**Comment by ironmonk88** [comment]
This should be fixed now.
