### ISSUE TITLE
[BUG] conflict with token movement

### ISSUE THREAD

**Issue by dmmarcelo** [ironmonk88/monks-active-tiles#319]
when activated, I can't (holding the control) drag the ruler and press the space for the token to move, since in V10 the drag ruler module is not working, this is the best way to measure the characters' movement. I don't want to give up the Monk Active Trigger, it makes automation so much easier.

**Comment by StrugglerXIV** [comment]
I was able to fix it by deleting some lines of code.
If you open the "monks-active-tiles.js" file and delete the code from line 1682 to line 1770, the movement bug should disappear and so far I haven't had any functionality issues or any error on the console.

Could be a momentarily fix until release for any that need it.
