### ISSUE TITLE
[BUG] v10. Teleport

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#320]
### Snap to Grid

Teleporting cross-scene with snap to grid active does not actually snap to grid. Nothing in the console

![image](https://user-images.githubusercontent.com/99844555/190021093-8bd79882-b2eb-41b8-bd2e-e301b34cd80b.png)

### Delete Source Token

Deletes the original token, but throws this error. 

![image](https://user-images.githubusercontent.com/99844555/190023039-a5677e57-2142-49ed-97fa-c0209404cd57.png)

### Avoid Other Tokens

Works, but throws this error.

![image](https://user-images.githubusercontent.com/99844555/190023280-2c4ae532-76b3-4e72-8e5c-2b78a99dcc37.png)

### All 3

Having all three active for a cross-scene teleport results in between 6-120 separate copies of the above error.

### Scene Packer Interaction?

The teleport here teleports the token to a spot other than the target destination, then moves the token across the canvas until it reaches it's destination. 

I was able to replicate this one time using the files Pyram sent me; after either changing scenes or reloading, it no longer occured for me. 
https://www.youtube.com/watch?v=6_lyF0lxjrQ

### FTC

MATT 1.0.91
![image](https://user-images.githubusercontent.com/99844555/190021217-6a5544fe-c994-4cef-88a6-49ab32c3b01e.png)

**Comment by ironmonk88** [comment]
I *think* I've fixed the weird teleport within the scene.  I can't replicate it, so it's a bit of a shot in the dark.

**Comment by ironmonk88** [comment]
This should be fixed now.
