### ISSUE TITLE
[BUG] Item to Canvas Tile Creation

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#322]
Dragging an item to the canvas results in this error. 
![image](https://user-images.githubusercontent.com/99844555/190921534-132918fa-8b6c-4fa8-b999-8e056f112060.png)
MATT 10.2
![image](https://user-images.githubusercontent.com/99844555/190921571-4b7f9f13-1722-451b-b866-53d7d3d3fdc0.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
