### ISSUE TITLE
[BUG] [v10] "On click event" sends ping command 

### ISSUE THREAD

**Issue by everyonecancode** [ironmonk88/monks-active-tiles#323]
**Describe the bug**
Clicking on a tile with "on click" event set up creates ping effect visible for every player.

**To Reproduce**
1. Create a tile
2. Add "change scene" event on "click" action
3. Press it

**Expected behavior**
A scene should be changed for a player without notification for all the other players

**Please complete as much of the following information as possible:**
 - Browser: Brave (chromium based)
 - Foundry Version: v10
 - System Call of Cthulhu 7ed
 - Module version: 10.2
 - Are there any errors in the console : No

**Comment by Zilandrix** [comment]
Having the same issue. Making it "double click" seems to fix the issue, but thats all I could do.

**Comment by ironmonk88** [comment]
Fixed in latest release.
