### ISSUE TITLE
[BUG] Switch Image Transitions

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#324]
Currently not rendering.
https://user-images.githubusercontent.com/99844555/193321951-8ee3ae2f-d476-4bd6-ac1a-c9dd5fbb7fb6.mp4

MATT 10.1
Foundry 10.286
D&D 5e 2.0.3
FTC ✔️

**Comment by ironmonk88** [comment]
Can you try with regular images and an on click rather than the door click and see if that changes things?

**Comment by Crowguard** [comment]
Seems to be working as expected with both click and door triggers now.

**Comment by ironmonk88** [comment]
Closing as it should be fixed.
