### ISSUE TITLE
[BUG] Change Permission

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#326]
A tile triggering a Change Permission action granting ownership to a token when the player already has ownership of the token results in the player losing permission to update the token.

https://user-images.githubusercontent.com/99844555/193728139-bf2b18b5-a89c-49ca-be6c-4c8395613496.mp4

![image](https://user-images.githubusercontent.com/99844555/193728143-6e3136b6-5593-4c87-b985-2ebd7b352d8d.png)

Foundry 10.286
D&D 5e 2.0.3
MATT 10.2
FTC ✔️

**Comment by ironmonk88** [comment]
Fixed in latest release.
