### ISSUE TITLE
[BUG] Hoverover Pointer get stuck as hand after tile is Disabled.

### ISSUE THREAD

**Issue by krobibero** [ironmonk88/monks-active-tiles#329]
I created a tile that when you hover over it to click, the pointer changes to a hand as expected.  After clicking on the tile, the pointer stays a hand and does not change back to an arrow, even when moving off the tile.  The pointer only change back to normal when the clicked tile become active again.

The Trigger setup is set as follows:
Restrict Tokens: Allow All Tokens
Controlled By: Anyone
The "When" action on the Setup page is set to On Click. 
Allow When Paused: Yes
Hoverover Pointer: Yes

There are a few actions, 
1. Play sound file
2. Pan Canvas to tile, and zoom in
3. Deactivate This tile

**To Reproduce**
1. Hover over tile (see hand)
2. Click on the tile to initiate action
4. Move pointer off tile, all around the screen
5. Manually Active the tile again
6. Pointer changes back to normal

**Expected behavior**
The pointer should change back to normal regardless if the tile is active or not

**Please complete as much of the following information as possible:**
 - Browser: testing with Edge and Chrome
 - Foundry: Version v9.255
 - System: Starfinder
 - Module version: 1.0.90
 - No errors in the console
 - No, I have not tried using `Find the Culprit` to make sure it isn't a module interaction.

**Comment by Crowguard** [comment]
Pretty sure this has been fixed at some point in v10 already; it doesn't occur on MATT 10.2

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
