### ISSUE TITLE
Feature Request: Change Attack from item.displayCard to item.roll()

### ISSUE THREAD

**Issue by tposney** [ironmonk88/monks-active-tiles#33]
For modules like better rolls/midi-qol (and probably others) the trigger for the complete roll is item.roll(), rather than display card. For core dnd5e, item.roll() will still do a displayCard().

**Comment by ironmonk88** [comment]
Problem I had with this, is that it opened up a dialog window.  And the "Attack" was really just meant to roll trap damage.
I can add a flag though so that users can choose if they want the full roll or just the chat card.

**Comment by ironmonk88** [comment]
Added a check box so players can either roll, or display a chat card.

**Comment by tposney** [comment]
Works perfectly - I'm not sure it's possible but I think I love this module even more than I did before.
