### ISSUE TITLE
[BUG] Tile Template Issues

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#330]
### Libwrapper Warning

Occurs the first time in a session that you drop a template onto the canvas.

![image](https://user-images.githubusercontent.com/99844555/195646885-46a635de-ae84-4fcd-aa9f-1579d54c1d63.png)

### Reordering Folders

Folders don't seem to be able to be reordered. They seem to just default to newest created at the bottom.

https://user-images.githubusercontent.com/99844555/195175654-c6130229-31e4-4c54-95ca-3fdac9d82ec1.mp4

### Search Bar
Its not finding anything nested within folders for me. 

https://user-images.githubusercontent.com/99844555/194226474-6781e19c-02de-4d8a-b6a9-2a7870e91917.mp4

### Folders

All of the right-click options have their own errors.

#### Edit Folder

![image](https://user-images.githubusercontent.com/99844555/194226684-98b462ba-0988-4c35-a597-c3d2993272c1.png)

#### Remove Folder

![image](https://user-images.githubusercontent.com/99844555/194226885-0afff244-53dc-4ec3-a6c0-6eb6d77ba897.png)

#### Delete Folder

![image](https://user-images.githubusercontent.com/99844555/194227017-1e220021-ae3e-4d24-ae7e-9038e85698f4.png)

#### Clear Folder (from Little Details)

![image](https://user-images.githubusercontent.com/99844555/195690063-d54f45e2-8be9-4f72-9bcf-baf88d14be81.png)

### Imported Tiles

Imported tiles keep the name they had prior to importing and not the name from the imported JSON. Not sure if this is intended or not.

#### Unable to right-click Imported tile

I imported a blank tile from Discord; now I can't right-click it to delete it. Temple found here https://discord.com/channels/862414864692281386/862421211749154816/1030194431254610041

![image](https://user-images.githubusercontent.com/99844555/195693437-44981581-52a9-4ea4-be2c-9c99a6e72359.png)

https://user-images.githubusercontent.com/99844555/195693248-30109c9a-c7ff-4d6d-b473-60284be0c93c.mp4

Edit: This is caused by saving a template before the tile configuration has been saved.

### Deleting Tiles

Not removed from the browser until it is closed and reopened.

https://user-images.githubusercontent.com/99844555/194228636-b6cef212-64c2-4567-a5fe-06aca25acf72.mp4

Right-clicking the "deleted" tile results in this error.

![image](https://user-images.githubusercontent.com/99844555/194228849-9df22e83-e188-43a8-ac0c-15e1d42bd1ac.png)

###

Foundry 10.286
D&D 5e 2.0.3
MATT 10.3
Forge Hosting
Firefox
FTC ✔️

**Comment by ExileofBrokenSky** [comment]
I can confirm the bug in deleting a tile template from the UI not refreshing.

Nearly same setup
Foundry 10.286
PF2e 4.2.6
MATT 10.3
Forge Hosting
Chrome
FTC ✔️

**Comment by Crowguard** [comment]
The Search issue is randomly working for me now 🤷

**Comment by ironmonk88** [comment]
Fixed in latest release.
