### ISSUE TITLE
[BUG] Right-Clicking Context Menu

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#331]
Add a lot of actions to a tile. Right click one of them.

Edit: It needs to be actions near the bottom of the action list, once you start scrolling down.

https://user-images.githubusercontent.com/99844555/194469105-652cd3a3-ded5-4931-9a03-1d02d36b7742.mp4

Nothing in the console. 

Foundry 10.287
5e 2.0.3
MATT 10.3
Forge
Firefox
FTC ✔️

**Comment by ironmonk88** [comment]
Fixed in latest release.
