### ISSUE TITLE
[BUG] Can't Select Actor to perform Attack

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#332]
Attempting to select an actor or token fails and errors. 

(Haven't confirmed this part yet, but someone mentioned that manually inputting the actor ID results in the dropdown to select the attack being blank.)

https://user-images.githubusercontent.com/99844555/194739400-72eda865-2cfb-4a1b-be03-7dce3ee74958.mp4

![image](https://user-images.githubusercontent.com/99844555/194739311-7e47d78f-b609-454c-b29d-5aa6fa2b5b86.png)

Foundry 10.287
D&D 5e 2.0.3
MATT 10.3

**Comment by Vullion** [comment]
I've had the same issue only difference is I run Foundry 10.284

**Comment by Deadlander** [comment]
I am having the same issue. FoundryVTT 10.288, Pathfinder 2e v4.2.6
![image](https://user-images.githubusercontent.com/13036735/196681007-34c9c123-87a1-4551-a4f9-d0ae7e44d408.png)

**Comment by ironmonk88** [comment]
Fixed in latest release.
