### ISSUE TITLE
[BUG] Tagger Wildcard {#}

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#334]
MATT Actions targeting a Tagger Wildcard {#} don't work. No errors.

Incremented prefabs that have swapped to numbers work as expected.

# MATT 10.2
Working as intended.

https://user-images.githubusercontent.com/99844555/195002724-e1149213-a2a7-49f3-9823-ea67497e82e8.mp4

# MATT 10.3
Nothing happens.

https://user-images.githubusercontent.com/99844555/195003050-9d8e3c38-694c-4f95-a4b3-c2052d043fcf.mp4

# Info

MATT 10.3
Tagger 1.3.8
Foundry 10.287
D&D 5e 2.0.3
FTC ✔️

**Comment by ironmonk88** [comment]
Fixed in latest release.
