### ISSUE TITLE
[BUG] {{value.items.0.name}}

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#335]
{{value.items.0.name}} no longer works to forward an item's name to a Chat Message/Notication. Other types still work (it should be right after "an")

![image](https://user-images.githubusercontent.com/99844555/195721666-db7cf754-f2fb-49a7-932d-48cb919acf83.png)

[fvtt-tiledata-item-name-bug.zip](https://github.com/ironmonk88/monks-active-tiles/files/9780976/fvtt-tiledata-item-name-bug.zip)

MATT 10.3
D&D 5e 2.0.3
Foundry 10.288
FTC

**Comment by ironmonk88** [comment]
Fixed in latest release.
