### ISSUE TITLE
[BUG] Stop Animation for Triggering Player does not work for GM (Play Animation action settings)

### ISSUE THREAD

**Issue by MikeyTheMoose** [ironmonk88/monks-active-tiles#339]
**Describe the bug**
For a Play Animation action, setting it to "Stop" the animation for "Triggering Player" does not work. This issue only persists while you are the GM.

Players might actually have the opposite problem, where they are unable to *Play* animations set for "Triggering Player," but Stopping it for only them works fine.

**To Reproduce**
1. Sign in as GM.
2. Place an animated tile.
3. Create a new trigger action: Play Animation.
4. Set Animation: Stop.
5. Set For: Triggering Player.
6. Play the tile animation.
7. Use MATT to trigger the animation to stop.

**Expected behavior**
The tile animation should stop for the triggering player.

**Screenshots**
(https://user-images.githubusercontent.com/110850792/196984214-48e34c72-3665-4f10-85fa-42eb2ed4e149.mp4)

**Please complete as much of the following information as possible:**
 - Browser: Chrome
 - Foundry Version: v10
 - System: PF1e
 - Module version: 10.3
 - Are there any errors in the console: No
 - No other modules active.

**Additional context**
None.

**Comment by ironmonk88** [comment]
Fixed in latest release.
