### ISSUE TITLE
trigger "Attack" Not active save throw

### ISSUE THREAD

**Issue by rinnocenti** [ironmonk88/monks-active-tiles#34]
in trigger made for attacks, if the attack has a "save" it doesn't find a target (neither stops damage nor saves, even if the token is triggered correctly)
Simple attacks find the targets, but if it's with a save it doesn't. (using MIDI save)
![image](https://user-images.githubusercontent.com/3178127/129431809-4efc2054-5de7-40d2-bd54-8e3ba5cc76ce.png)

This is important because I can only apply effects to tokens that miss the save.
with the module's "request roll", if I make a test of more than one token (tile area) it applies the effect to all (even if I only select success or just fail to interrupt), because if one of the tokens fails/has success will all receive other actions, regardless of whether a token passes.
![image](https://user-images.githubusercontent.com/3178127/129431917-a133530f-8e1d-4201-aa01-626b47380ad2.png)

with the direct save application in the attack I can apply the effects only to the failed tokens.

**Comment by rinnocenti** [comment]
Apparently it's some race condition. because sometimes it save, sometimes it doesn't
![image](https://user-images.githubusercontent.com/3178127/129432027-e9a86625-0024-4a7c-9323-7573434f8f0d.png)

**Comment by ironmonk88** [comment]
It should be fixed in the next release. 
The targeting code was after the attack code, and I've swapped them.
It works the second time run, because the first one did the targeting, while the second trigger does the attack.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
