### ISSUE TITLE
[BUG] Play Animation

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#340]
**Describe the bug**
The animation can be played once, and won't trigger again until the scene is left and returned to.

![firefox_DHukpqTGUZ](https://user-images.githubusercontent.com/99844555/196999679-19322d47-53d7-45d6-9069-5bc2baffcf38.gif)

**To Reproduce**
![image](https://user-images.githubusercontent.com/99844555/196999165-1106c7fa-83d2-4ea4-8d85-e75478cb8369.png)
Any trigger really.

**Expected behavior**
Animation should be able to be played repeatedly. 

**Please complete as much of the following information as possible:**
Firefox
Forge
Foundry 10.288
MATT 10.3
FTC ✔️

**Comment by Crowguard** [comment]
This might be fixed now? Seems to be working as expected on 10.291/MATT 10.7.

**Comment by Crowguard** [comment]
Not fixed; another user is reporting its still happening.

**Comment by ironmonk88** [comment]
I'm assuming it's an edge case.  I'd need to know exactly what the set up is, and if there was any errors in the console.

**Comment by ironmonk88** [comment]
Closing this as I believe it was fixed.
Weird Firefox bug.
