### ISSUE TITLE
[BUG] Play Sound Issues

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#341]
**Describe the bug**

While doing the Play Sound testing, I did notice two issues; the playing track wasn't being affected by the global volume slider, and wasn't stopped when I opened the tile config and clicked the stop button there. It only happens sporadically, and reloading seems to fix it.

**Please complete as much of the following information as possible:**
 - Firefox
 - Forge
 - Foundry 10.288
 - D&D 5e 2.0.3
 - MATT 10.3
 - FTC

**Comment by ironmonk88** [comment]
Maybe I've fixed this one?
But it's being affected by the Ambient Volume and the stop sound button stopped the sound each time I tried.

**Comment by Crowguard** [comment]
I think its fixed? It was just an intermittent bug to begin with, but I can't replicate it any more.

**Comment by ironmonk88** [comment]
Closing this as it's possibly fixed?
