### ISSUE TITLE
[BUG] "Open a Journal" action won't allow Page selection from Compendium Journals

### ISSUE THREAD

**Issue by jobyburk** [ironmonk88/monks-active-tiles#342]
**Describe the bug**
The ability to Open a Journal to specific page in 10.3 was a huge upgrade; however, I noticed when trying to do so from a Journal Entry within a Compendium, the dropdown selection for Journal Entry Page showed no options.

**To Reproduce**
1. Go to "Actions" in the Tile Triggers configuration dialog.
2. Select "Open a Journal" from the Actions dropdown. Click "Select an Entity", open a Compendium containing Journal Entries (with multiple pages), and then select an entity (Journal Entry) within the open Compendium. 
3. Go to select a page from the Page dropdown.
4. See error, or rather see nothing, as it will not show you any pages in the dropdown.

**Expected behavior**
I would expect that the pages within journal entries stored in a Compendium are at accessible for selection, and when the tile is triggered, that the specific journal page is opened.

**Screenshots**
![image](https://user-images.githubusercontent.com/8411012/197015813-d0febb17-c21c-4fd6-9f51-726b77489130.png)

**Please complete as much of the following information as possible:**
 - Browser: **Chrome**
 - Foundry Version: **10.288**
 - System: **Pathfinder 2e - version 4.2.6**
 - Module version: **10.3**
 - Are there any errors in the console: **Not applicable**
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction? **No, but was able to reproduce in fresh world with no other modules active.**

**Additional context**
Not much else to add here. Thanks for all that you do!

**Comment by ironmonk88** [comment]
Fixed in latest release.
