### ISSUE TITLE
[BUG] Open Journal, Pages & Subsections

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#344]
Opening a journal to a specific page just opens it to the cover; assuming I'm doing subsection properly and typing in the exact name of the subsection, those also have the same behavior. No errors.

https://user-images.githubusercontent.com/99844555/197308668-bda88455-c87f-4bbf-a19c-9007adb3acba.mp4

Foundry 10.288
MATT 10.3
MEJ 10.3
FTC

**Comment by ironmonk88** [comment]
Fixed in latest release.
