### ISSUE TITLE
[BUG] create invisible token stay at 50% opacity

### ISSUE THREAD

**Issue by Cimeryl** [ironmonk88/monks-active-tiles#346]
**Describe the bug**
When i create a token with MATT and the "Create token" trigger with "Create invisible" check. It create a token invisible as expected.
But if i turn the invisible off (with the icon on top right of the token) or by the "show/hide" function, the token opacity stay at 50%

**To Reproduce**
1. Go to a tile
2. Click on Trigger
3. Click on "+Add"
4. Select "Create Token"
5. Select an Actor and set location
6. Check the "Create Invisible" checkbox
7. Active the tile
8. On the created token, turn off the invisibility
9. See the Token opacity at 0.5

**Expected behavior**
When turn off invisibility on the token, Token opacity must be at 1

**Screenshots**
![image](https://user-images.githubusercontent.com/73182114/197423159-2a2c916d-935b-4209-80dd-65ab7e1677ad.png)
![image](https://user-images.githubusercontent.com/73182114/197423185-5146bec9-4963-4612-b873-8f609a104acf.png)
![create_token](https://user-images.githubusercontent.com/73182114/197423447-ae70ca72-0856-4f91-bd0d-0533b482a006.gif)
![image](https://user-images.githubusercontent.com/73182114/197423513-54e4e50d-bb98-43c2-8b32-c1e66be4fa5a.png)

**Please complete as much of the following information as possible:**
 - Browser Brave 1.44.112 / Chrome 106.0.5249.119
 - Foundry Version 10.288
 - System D&D5 2.0.3
 - Module version MATT 10.3
 - Are there any errors in the console : no
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. : Try with only Matt on a virgin world

**Comment by ironmonk88** [comment]
Fixed in latest release.
