### ISSUE TITLE
[BUG] Reset Rolltable When All Used

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#348]
This option is lo longer resetting the selected rolltable after all options have been used. No errors/warnings besides the "No available results from this roll table" one.

![image](https://user-images.githubusercontent.com/99844555/197895255-e21825eb-aa68-4f38-8910-947b6f5bc8f1.png)

Foundry 10.288
D&D 5e 2.0.3
MATT 10.3

**Comment by ironmonk88** [comment]
Fixed in latest release.
