### ISSUE TITLE
[BUG] Convenient Effect, Apply to This Tile

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#349]
This action really doesn't need "This tile"; and it should probably be removed to prevent confusion.

![image](https://user-images.githubusercontent.com/99844555/198683676-7a98fdac-91fb-41ce-b4e4-76304fc260d7.png)

**Comment by ironmonk88** [comment]
Fixed in the latest release.

**Comment by Crowguard** [comment]
Still there. 10.8. 
![image](https://user-images.githubusercontent.com/99844555/208746838-49231dfc-ba12-4e7b-9f24-50c7a954058e.png)
