### ISSUE TITLE
Adding an item with an onClick trigger does not seem to work.

### ISSUE THREAD

**Issue by tposney** [ironmonk88/monks-active-tiles#35]
I had a look and the problem seems to be updateSelection, which calls tile.trigger(), rather than passing the triggering token.

I naively tried
```
tile.trigger(canvas.tokens.controlled[0]);
```

which seemed to work.

**Comment by tposney** [comment]
Another trivial one
line 1765
```
if (canvas.activeLayer.name == 'TokenLayer') {
```
is probably better as (I've seen some errorslibWrapper-wrapper.js:627 Uncaught TypeError: Cannot read property 'name' of null)
```
if (canvas.activeLayer?.name == 'TokenLayer') {
```

**Comment by BlackMoons** [comment]
After doing some testing on my own issues with clickable tiles, I replaced the line 1778 with:
```
if (canvas.tokens.controlled.length)
    tile.trigger(canvas.tokens.controlled[0],game.user.id);
```
And now the behavior is much better, with chat messages and scripts at least knowing what 'actor' is selected, but oddly no 'token' instance. Chat messages posted by trigger tiles via script or the built in 'chat message' feature now also post under the players selected actor. 

IMO its acceptable to have tile triggers not work if no token is selected to attribute the click to.

**Comment by ironmonk88** [comment]
Fixed, but in a slightly different way.  I added a similar line, but in a more central location to cover some other ways to get there via On Click.

And those ? continue to get me!

**Comment by BlackMoons** [comment]
Thanks! I suspected my fix was not quite right, Because I couldn't get the 'token' in the script just the actor, and the actor seemed to be the base actor.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
