### ISSUE TITLE
[BUG] Convenient Effect, Toggle

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#350]
Attempting to toggle a Convenient Effect fails and results in this error. 

![image](https://user-images.githubusercontent.com/99844555/198689230-4f4a78b3-6b1b-4aab-ae2d-a5c6c0273375.png)

Foundry 10.288
D&D 5e 2.0.3

![image](https://user-images.githubusercontent.com/99844555/198689327-cdf0b0ed-6caa-40a9-9047-58fa2a75661d.png)

**Comment by ironmonk88** [comment]
Nevermind.  Figured out where it was.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
