### ISSUE TITLE
[BUG] Alter, toggle texture.scaleX/Y

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#351]
Attempting to toggle this attribute on a tile other than the triggering tile results it only changing the attribute once. Further triggers have no effect. No errors.

```= ({{tile.texture.scaleY}} || 0) == 1 ? -1 : 1```

https://user-images.githubusercontent.com/99844555/198749676-d48beb6c-12be-40e1-b05f-ec07e0402b52.mp4

![image](https://user-images.githubusercontent.com/99844555/198749761-f3f20111-80d3-42ed-93ea-693a6e74e2d7.png)

Foundry 10.288
MATT 10.4
FTC

**Comment by ironmonk88** [comment]
Yeah, that should be `{{entity.texture.scaleY}}`.  tile refers to the triggering tile... which never changes, so it only happens once.  entity refers to the object being acted upon.
