### ISSUE TITLE
[BUG] Create Token at Current Location

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#352]
![image](https://user-images.githubusercontent.com/99844555/198763478-eb334809-598e-4072-99ee-2c9f750c164e.png)

This setup fails to create a token and results in this error. 

![image](https://user-images.githubusercontent.com/99844555/198763745-2fe073da-e7fc-408c-ac6d-64b535de6b4e.png)

Foundry 10.288
D&D 5e 2.0.3
MATT 10.4

**Comment by ironmonk88** [comment]
And now... next release you'll be able to specify a location from a roll table.

**Comment by ironmonk88** [comment]
Fixed in latest release.
