### ISSUE TITLE
[Feature Request] Ability to create journal pages

### ISSUE THREAD

**Issue by mnoreke** [ironmonk88/monks-active-tiles#356]
When using Active Tiles together with Enhanced Journal, I want to check if a page exists, and if not, have the ability to add a new page to a journal with some initial text. I also want to set what the parent page should be.

Use case:
Automatic logging for the party journal. Adding pages and building the default notes structure as events occur. This would save my party who are horrible note takers from having to type everything, but the basic framework is created for them to simplify their life.

**Comment by ironmonk88** [comment]
Added to a previous release.
