### ISSUE TITLE
[Question] How to create tokens for active players on a scene

### ISSUE THREAD

**Issue by mnoreke** [ironmonk88/monks-active-tiles#357]
Working with Active Tiles, I want to trigger a new scene for the players that are online. As I don't know who will make it each week, I would like to automate the creation of tokens to reduce downtime during a session. This is triggered from a world map where there is a "The Party" token rather than individual tokens.

Create token allows me to select entity, which I tried setting to Current Actors along with Actors for Journal. This does not however create new tokens for active players.

Any suggestions on how to resolve this?

**Comment by Crowguard** [comment]
@mnoreke You'd have to set up a Create Token action for each token; that isn't something that's currently possible to automate using Active Tiles.

Current actors is used in action threads & filters, it isn't for currently logged in PCs.

**Comment by ironmonk88** [comment]
Added the option in the Create Token action to use the players tokens.  That way you can now set up a Tile that will create the party.
