### ISSUE TITLE
[BUG] libWrapper: Potential conflict detected between module DF Scene Enhancement and module Monk's Active Tile Triggers

### ISSUE THREAD

**Issue by yjeroen** [ironmonk88/monks-active-tiles#358]
![image](https://user-images.githubusercontent.com/1303988/200280289-13a48712-21eb-4481-bbfd-f2b4ee5b5375.png)

If you need any more info let me know. Issue appears when having both modules activated and clicking on a scene in the Scene tab to View Scene.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
