### ISSUE TITLE
[BUG] Click Trigger not working with Move Action

### ISSUE THREAD

**Issue by ExileofBrokenSky** [ironmonk88/monks-active-tiles#359]
Trigger - Move: not working for GM, but does work for players

**To Reproduce**
1. Setup a trigger to activate on click, allowing all tokens and anyone to do so.
2. Click on the trigger tile as GM.
3. Setup a Move action with something. I tested with both tokens and tiles getting the same error

Manual Activation, Double Click, Right Click; all as GM also return the same error
Using token based triggers as GM or Triggering in any way as a player results in expected movement.

**Expected behavior**
Designated entity should move.

**Screenshots**
Console Error:
![image](https://user-images.githubusercontent.com/28786777/200872978-ec48f647-cbd8-4db1-852d-6190fbf1d0ca.png)

**Please complete as much of the following information as possible:**
 - Chrome
 - Foundry Version 10 286
 - Pathfinder 2e
 - Module version 10.5
 - Player was using Firefox

**Comment by ironmonk88** [comment]
Fixed in the latest release.
