### ISSUE TITLE
No token/Actor data on 'click' triggers.

### ISSUE THREAD

**Issue by BlackMoons** [ironmonk88/monks-active-tiles#36]
When executing a macro with a 'click' trigger, I can find no evidence of a correctly set up 'actor' or 'token' data anywhere (expected to be the first selected token? or maybe pass an array of all selected tokens?). All messages spawned from macros on click triggers send from GM or whatever token he has selected, and console.log() statements don't seem to appear on the person who clicked console if they arnt GM, and don't appear on the GM's console either (completely lost?)

Also, 'send a chat message' functionality of active tile triggers just sends the message under whoever the GM has currently selected, even when a user is the one who clicked the tile, when the trigger is set to 'click'

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
