### ISSUE TITLE
[BUG] Delay Action: further actions never happen

### ISSUE THREAD

**Issue by ExileofBrokenSky** [ironmonk88/monks-active-tiles#360]
**Describe the bug**
Actions that follow the Delay action  don't happen.

**To Reproduce**
1. Make a trigger with actions that fire normally.
2. Add a delay of any length to the start of the previously working tile actions.
3. Triggered tile will now do nothing
4. No console errors

**Please complete as much of the following information as possible:**
 - Chrome
 - Foundry Version 10.286
 - Pathfinder 2e
 - Module version 10.5
 - Are there any errors in the console [e.g. press F12 and look for red text]
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.

**Additional context**

**Comment by ExileofBrokenSky** [comment]
Good thing it's easy to rollback to 10.4, this would break too many of my trigger tiles.

**Comment by ironmonk88** [comment]
It's fixed, and a patch should be released tonight.

**Comment by Crowguard** [comment]
@ironmonk88 Delay still isn't working if the Delay occurs following a redirect; any actions following the Delay still don't occur.

[fvtt-tiledata-delayafteranchro.zip](https://github.com/ironmonk88/monks-active-tiles/files/9983391/fvtt-tiledata-delayafteranchro.zip)

https://user-images.githubusercontent.com/99844555/201168029-6f21b3ff-9a43-4517-836e-b9e8060ac548.mp4

**Comment by ironmonk88** [comment]
Any errors in the console?
I can't replicate it with the attach Tile.
Works as expected.

**Comment by Crowguard** [comment]
I think its been fixed now; working as expected for me in 10.11.

**Comment by Crowguard** [comment]
Closing as part of ticket cleanup, this is no longer an issue.

**Comment by ironmonk88** [comment]
Closing as it should be fixed now.
