### ISSUE TITLE
Ability to use Macro for generating text for Journal

### ISSUE THREAD

**Issue by mnoreke** [ironmonk88/monks-active-tiles#362]
I would like to be able to run a macro to generate text for journal entries, mostly to get a timestamp of when the event occurred that I am logging.

My players are horrible note takers, so if I can unlock a pre-defined journal entry and log timestamps to it of when things occurred along with some flavor text describing the event, there is less for me to remember (I have memory issues due to a medical condition) as I can just refer them to their journals.

**Comment by mnoreke** [comment]
Having the ability to use token replacement (Ex: [INSERT_FULL_TIMESTAMP] ) would suffice to solve this for me, assuming that tokens can pull data from other modules such as simple calendar.

**Comment by ironmonk88** [comment]
Added `{{timestamp}}` to the list of replaceable items when using the Write to Journal action.
