### ISSUE TITLE
[BUG] Distance Filter

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#363]
Actions following a distance filter are going off regardless of whether the token meets the distance requirement or not, OR the actions won't trigger at all, even if the token is within range. Not sure what the pattern is for why one or the other occurs yet.

Video is shown from the GM side; tile is being triggered on a PC user.

https://user-images.githubusercontent.com/99844555/201156117-36cd0dac-2025-4a09-a913-9c8e3763451f.mp4

Foundry 10.288
D&D 5e 2.0.3
MATT 10.6

**Comment by ironmonk88** [comment]
Closing, I believe it was one of the things I addressed.
