### ISSUE TITLE
[BUG] Journals cant display to players without rights. in v9 it's worked

### ISSUE THREAD

**Issue by Kikimor-rec** [ironmonk88/monks-active-tiles#365]
In V9, the log display trigger worked even for journals that have no rights.

Now when you try to display the Journal to the player without rights to it shows an empty Journal and gives an error in the console.

![image](https://user-images.githubusercontent.com/115701754/201486272-d4ad5785-f565-4be3-9a0f-34dc5b238553.png)

**Comment by larumirak** [comment]
I confirm that there is such an error. The player is shown an empty journal if he does not have rights.

**Comment by icedern** [comment]
I'm also seeing this issue.  I can disable Monks enhanced journal and it'll display the journal title, but no info in the page.  With enhanced journals on, it will give the no permission error.

**Comment by Raelyr195** [comment]
I am also having this issue - many many trigger tiles in my world are designed to open a journal for the triggering player without having them previously been granted permissions. This worked in v. 9 with a simple "Open Journal" action on a "Click" trigger. These same links in v. 10 now result in:
![image](https://user-images.githubusercontent.com/119760992/205461238-fbb656a3-cfca-437a-b14b-28f0f915bc14.png)

**Comment by larumirak** [comment]
I found a temporary solution for myself: the trigger gives the rights of an "observer" to the player on the journal, and then shows this journal. Unfortunately, sometimes the player does not open the journal the first time, it is necessary to click twice.

**Comment by ironmonk88** [comment]
v10 changed how permissions worked.  So it's blocking viewing the journal entries.
I've fixed it to have a temporary work around.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
