### ISSUE TITLE
[BUG] Scaled Image Tiles

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#368]
Tiles with their scale adjusted seem to be using the _Trigger Using Images_ setting even when the setting is unchecked in the tile config; downscaled images are harder to trigger, and upscaled images have their trigger zone expanded even farther into the transparent area outside the image.

https://user-images.githubusercontent.com/99844555/202322580-7f94fade-3407-4645-9cfc-d1d6c2489640.mp4

![image](https://user-images.githubusercontent.com/99844555/202317965-54c85bc7-a584-4d0f-ab78-174a1e8a938c.png)

https://user-images.githubusercontent.com/99844555/202318076-041290b8-b2f3-4055-b91e-ee46148a6acf.mp4

MATT 10.7
Foundry 10.290
D&D 5e 2.0.3
FTC

**Comment by Crowguard** [comment]
I think this was a core problem; it seems to be working as expected again.

https://github.com/foundryvtt/foundryvtt/issues/8560

**Comment by Crowguard** [comment]
Deleted previous comment; still an issue in MATT 10.7.

**Comment by MrLenin** [comment]
Still an issue in 10.12 as well

**Comment by ironmonk88** [comment]
Fixed in the latest release
