### ISSUE TITLE
Add the capability to select consumable items from an actor for Attack.

### ISSUE THREAD

**Issue by billsoranno** [ironmonk88/monks-active-tiles#369]
**Is your feature request related to a problem? Please describe.**
When choosing a action of Attack, only attacks appear in the select list. You tuber Mr.Weaver suggests and edit to allow consumables to be chosen (https://www.youtube.com/watch?v=TUt-X7cGcPw). 

**Describe the solution you'd like**
Include consumable as a type for the attack action.
action.js line 3384 in v10.7

**Additional context**
Module "Traps, Trammels, and Triggers" defines their items as consumables. allowing consumables as an item to choose from will allow selecting their items.

Thanks
Bill

**Comment by ironmonk88** [comment]
Added to the latest release
