### ISSUE TITLE
[Issue] "Use Tokens within triggering Tile" is not working

### ISSUE THREAD

**Issue by vandora03** [ironmonk88/monks-active-tiles#37]
Hi There,

Thanks for the amazing mod!

I wanted to auto request the players(token) that within the triggering tile to give an Reflex save roll, and I've noticed that the "Use Tokens within triggering Tile" function is not working when no token within that tile, as it will request all players tokens to roll Reflex saves (even they are not in the tile).

![image](https://user-images.githubusercontent.com/88712791/129440793-d7c7c73c-1283-44dd-9a73-34afdd2430a7.png)

Tested system version as per below screenshot:
![image](https://user-images.githubusercontent.com/88712791/129440339-64bdff32-e64f-41f8-b273-64d28c9dced2.png)

Console Errors are per below:
![image](https://user-images.githubusercontent.com/88712791/129440482-3324c0a8-3cc3-4383-bf6a-1d02f8066bcb.png)

**Comment by ironmonk88** [comment]
That's working as designed from the Tokenbar, although slightly strange from the Active Tiles perspective.

The request function of Tokenbar is set to default to the party tokens if none are selected for ease of use when pressing the request roll option on the Tokenbar.

If no tokens are passed in from Active Tiles, then Tokenbar assumes it's a regular click from the Tokenbar and will default the tokens.

There's not really a way to differentiate between the two.

**Comment by ironmonk88** [comment]
Closing this as there's not much that can be done about it.  And cleaning up the ticket queue.
