### ISSUE TITLE
[BUG] Move, Current Location

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#371]
Token movement stops, but the following move doesn't occur and results in the error.
![image](https://user-images.githubusercontent.com/99844555/203616240-99e4ebcb-dafc-4986-91b9-2c774ebdaad3.png)

![image](https://user-images.githubusercontent.com/99844555/203616153-fe2832af-6094-448a-8e74-a60a2f638dfe.png)

MATT 10.7

**Comment by ironmonk88** [comment]
Technically... there's still an error though.  :-)

**Comment by ironmonk88** [comment]
Fixed the issue that this was creating.
