### ISSUE TITLE
[Feature Request] Trigger Tile, Specific Landing Field

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#373]
Would it be possible to add a field to the Trigger Tile action to put the name of a landing that the Triggered Tile actions can start at?

(Use case: complicated prefabs/landing pages that add/subtract various {#} Tags where it would be a PITA to add them all to one reset button. This way, the resets can be built into each tile using {#}. The reset button could just be set to target all tiles with a Reset Tag, then it goes to the Reset landing on each tile.)

**Comment by ironmonk88** [comment]
Added to the latest release.
