### ISSUE TITLE
[BUG] Attack action, PF2e

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#377]
The chat cards do nothing when clicked. Nothing in the console.

https://user-images.githubusercontent.com/99844555/205365236-4e3df978-6e90-4332-9855-42944d196e34.mp4

Foundry 10.291
PF2e 4.4.2
MATT 10.7

**Comment by Crowguard** [comment]
Vralek said this is a problem with PF2e, not MATT. But I'm going to leave this ticket here for now, cause I'm almost certain their fix is going to break MATT anyway.

**Comment by Crowguard** [comment]
Update: This action still fails when run through MATT; it seems you have to perform the attack by clicking the button in this Attack section on the character sheet, and not from the actor inventory. When MATT triggers it seems to be the same as clicking the "description" button on the Attack section or on an item.

![image](https://user-images.githubusercontent.com/99844555/208013636-b2d13d97-8a54-470d-b92a-a92a416784c5.png)

**Comment by MrLenin** [comment]
This seems to actually trigger the attack now, but there definitely still appear to be some issues

**Comment by ironmonk88** [comment]
Fixed in the latest release.
