### ISSUE TITLE
Action "Open journal" check permission not working when GM is not online

### ISSUE THREAD

**Issue by Walexmith** [ironmonk88/monks-active-tiles#378]
Hi,

I'm working on a landing page, and it has buttons allowing players to open and edit journal entries. These journal entries have their permissions set to be readable only by the player that owns it. On the active tile dialog, I checked the box "check permission" and it seems to work fine when the GM (me) is logged in. But as soon as I log out, the players have access to journal entries they should not, when clicking on the tiles/buttons.

It looks like the tile don't check for permission if the GM is offline. I would like to be able to leave my game running so my players can come edit their stuff when they want (otherwise my landing page is pretty useless).

 - Firefox 107.0.1
 - Foundry V10 built 290
 - System : Custom System Builder
 - Module version 10.7

Thanks for your time

**Comment by ironmonk88** [comment]
I'm unable to replicate this.
Can you post some screenshots of the tile setup and the journal permissions.

**Comment by ironmonk88** [comment]
Closing this as there's been no response.
