### ISSUE TITLE
[BUG] Pan Canvas, Triggering Player

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#379]
A Pan Canvas for Triggering Player also pans the GM's canvas. Other options seem to work as expected.

![image](https://user-images.githubusercontent.com/99844555/206026476-40488b30-9be0-4b1c-a62d-65777d02c293.png)

https://user-images.githubusercontent.com/99844555/206026678-f162a682-c0ba-452d-b9ee-a5cc9dbb78ce.mp4

Foundry 10.291
MATT 10.7
FTC ✔️

**Comment by ironmonk88** [comment]
Fixed in the latest release.
