### ISSUE TITLE
[Request] Check Item/ActiveEffects

### ISSUE THREAD

**Issue by rinnocenti** [ironmonk88/monks-active-tiles#38]
It would be interesting to have a trigger if the token has a specific item and/or active effect on the token (checking if it is equipped or not) as a condition of the trigger to continue execution or not. (failure and success)

**Comment by tposney** [comment]
Perhaps these and other requests for workflow control could be resolved with a conditional macro call, i.e. the user specifies a macro to run that returns true/false or some other designated set of values that causes the workflow to stop/continue

**Comment by rinnocenti** [comment]
is what I'm using, but it would be interesting for example to do passive perception checks and be able to activate other workflow triggers for that, when passing to display a secret door or a trap, depending on the value of passive perception for example, or not to activate if you have an item equipped or in your backpack.

**Comment by ironmonk88** [comment]
Closing this as MATT has filters for items and effects.
