### ISSUE TITLE
[BUG] Play Sound, for Triggering Player

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#380]
This action is now playing the sound for the GM in addition to the triggering player when triggered.

![image](https://user-images.githubusercontent.com/99844555/206809965-cbfc4a2e-e614-4a69-9daa-7ca46e3543e0.png)

MATT 10.7
Foundry 10.291
D&D 5e 2.0.3

**Comment by ironmonk88** [comment]
Fixed in the latest release.
