### ISSUE TITLE
[BUG] Tile Templates, Create New Subfolder

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#381]
Really minor one; creating a subfolder within a folder adds it to the main directory instead.

https://user-images.githubusercontent.com/99844555/207201202-df60341a-076d-4181-95d6-13f45e160207.mp4

MATT 10.7
Foundry 10.291
D&D 5e 2.0.3

**Comment by ironmonk88** [comment]
Fixed in the latest release.
