### ISSUE TITLE
[Request] Click Triggers within or outside radius

### ISSUE THREAD

**Issue by DJLaserz** [ironmonk88/monks-active-tiles#383]
I like the Click Trigger and Hover over Pointer combo, but I don't want my players to be able to click the tile unless their token is within a certain distance from the tile.

I suggest being able to set a radius that allows for Click Trigger only within that set radius. The opposite would be nice as well, only allows Click Trigger when outside that set radius

Example: A well in the center of town, you can collect water from it but you can only click it when your token is next to the well.

Sorry If this was suggested before, I couldn't find it if it was.

**Comment by ironmonk88** [comment]
![image](https://user-images.githubusercontent.com/75920956/207639140-8fd3b975-6520-4d03-ba19-44850c229c11.png)
![image](https://user-images.githubusercontent.com/75920956/207639201-a66a0cb5-8547-4943-b4fa-e7dc09ee5d14.png)
