### ISSUE TITLE
Allow matching of ANY tag

### ISSUE THREAD

**Issue by xlilcasper** [ironmonk88/monks-active-tiles#384]
I think I found an easy way to allow active tiles to read any tag (instead of by index).
 If you change line 5388 to 
 if (prop && (typeof prop == 'object') &&!(prop instanceof Array)) {
 then you can easily check if a tag is in the array. using the following...

find current tokens with <flags.tagger.tags ""laser-sensor1""

Double quotes were needed in order for it to resolve properly. Also, throws the error about property arrays being removed soon but it works.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
