### ISSUE TITLE
[BUG] Move Action, Manual Activation

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#385]
Move actions fail when manually triggered or via a Trigger Tile.

Manually triggering results in this error; a Trigger Tile method has no error but still fails.
![image](https://user-images.githubusercontent.com/99844555/208196512-288f3775-e531-40cc-b2a1-eac45dbb4d2a.png)
[fvtt-tiledata-moveloop.zip](https://github.com/ironmonk88/monks-active-tiles/files/10249679/fvtt-tiledata-moveloop.zip)

https://user-images.githubusercontent.com/99844555/208195691-b4c0f7c3-e46f-4a5f-bbe2-25e4af55c315.mp4

MATT 10.7
Foundry 10.291
D&D 5e 2.0.3

**Comment by Crowguard** [comment]
Not sure if I should have made this or not; it might be the same as #366? I thought this was fixed once, and the ticket just wasn't closed. Different error from 366 though.

**Comment by ironmonk88** [comment]
I believe I've fixed this.  I can't replicate, and pretty sure the code I altered would fix this.

**Comment by Crowguard** [comment]
Seems to be working as expected now.
