### ISSUE TITLE
[BUG] Javascript error when trying to trigger a tile with a door interaction

### ISSUE THREAD

**Issue by Javalar** [ironmonk88/monks-active-tiles#388]
**Describe the bug**
When using a door to trigger a tile, a Javascript error occurs.

Full error is:
```
Uncaught (in promise) ReferenceError: entry is not defined
[Detected 1 package: monks-active-tiles]
    at triggerDoor (monks-active-tiles.js:1574:43)
    at monks-active-tiles.js:1620:21
```

**To Reproduce**
1. Create/activate a scene,
2. Setup an active tile with an action in the scene.
3. Add a door to the scene.
4. Setup an "On Open Door" trigger on the door and link to the tile.
5. Open the door.

**Expected behavior**
Tile's actions should trigger.

**Please complete as much of the following information as possible:**
 - Chrome
 - Foundry version 10 build 291
 - D&D5e
 - Module version 10.8

**Comment**
As a senior software developer with 20 years of experience, my professional opinion is that "entry" is not defined.

Jokes aside, it seems simply changing:
```javascript
entry = collection.get(docId);
```

to
```javascript
let entry = collection.get(docId);
```

on line 1574 fixes the issue.

**Comment by Crowguard** [comment]
Just adding, this only happens with targeted/Tagger options on the door; the new "Tiles Under Door" option works as expected.

**Comment by ironmonk88** [comment]
> As a senior software developer with 20 years of experience, my professional opinion is that "entry" is not defined.

Lol.

Fixed in the latest release.
