### ISSUE TITLE
[Conflict] libWrapper shows possible conflict with elevationruler and with one-journal

### ISSUE THREAD

**Issue by irbian** [ironmonk88/monks-active-tiles#39]
![image](https://user-images.githubusercontent.com/3071767/129636823-1b658c6b-f1fc-4fce-be0d-3e9a9a2256f0.png)

**Comment by ironmonk88** [comment]
There's not a lot I can do about those.

Active Tiles needs to override onClickEntityName to select Journal Entries.  So in very specific instances, it needs to redirect the control.  If One Journal overrides that function without running the default code it will prevent Active Tiles from working.  This probably needs a ticket to be opened with One Journal, to work on something to fix it.

Elevation Ruler seems to play fair with using libWrapper.  And is only wrapping the function, and returns control back to Active Tiles.  Shouldn't be an issue.

**Comment by irbian** [comment]
Much appreciated, I´ll contact one journal :)

**Comment by irbian** [comment]
For the record, I contacted here https://gitlab.com/fvtt-modules-lab/one-journal/-/issues/25

**Comment by ironmonk88** [comment]
Closing this ticket as there's not much I can do about it.
And it's pretty benign.
Just cleaning up the ticket queue.
