### ISSUE TITLE
[BUG] Alter's UI

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#391]
With the removal of the ability to use multiple attributes in one action with semi-colons, the window dialog should be updated to not recommend that anymore.
![image](https://user-images.githubusercontent.com/99844555/209245695-af3cfd2a-a0da-4ba4-8f66-e54c6c38c4ef.png)

MATT 10.9

**Comment by ironmonk88** [comment]
Fixed in the latest release.
