### ISSUE TITLE
[BUG] Create Token, at This Tile

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#392]
Displays as "Unknown Location" in the action list and the action itself; this is just a display error and isn't impacting the actual action trigger.

![image](https://user-images.githubusercontent.com/99844555/209420139-3087d8eb-de99-4d48-ab03-06fe6eebf065.png)

MATT 10.9

**Comment by ironmonk88** [comment]
Fixed in the latest release.
