### ISSUE TITLE
[Feature Request] Add Resume as a feature, to animated tile after Pause

### ISSUE THREAD

**Issue by krobibero** [ironmonk88/monks-active-tiles#393]
**Is your feature request related to a problem? Please describe.**
I am working with a video file as a tile, that I've created buttons the players can use to Start/Pause/Stop the video.

**Describe the solution you'd like**
It would be really nice if after the players click Pause, they can Resume the video where it left off.  I could not figure out a way within MoT to do this.  Currently the video pauses and if they click on Start, the video plays from the beginning again.  If the click Stop, the video stops and the video is no longer shown at all.  Clicking Start also starts the video from the beginning

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
