### ISSUE TITLE
[BUG] Convenient Effect "Effect undefined could not be found" issue

### ISSUE THREAD

**Issue by iAstinus** [ironmonk88/monks-active-tiles#394]
**Describe the bug**
Convenient effect does not add any effects to the triggering tokens. Note that this only apply to CE effect, not Active Effect action.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create tile with Convenient effect add Blinded (or any other CE effect) on Enter
2. Step on that tile
3. Error appears "Effect undefined could not be found"

**Screenshots**
Setup:
![setup](https://user-images.githubusercontent.com/94170912/209482780-08a7c09d-21ff-4550-b29d-fac72b6edd4b.png)

Error:
![error](https://user-images.githubusercontent.com/94170912/209482773-ca4cfb07-c184-4479-bef1-b96574a034ce.png)

**Please complete as much of the following information as possible:**
 - Foundry v10
 - D&D5e
 - Module version 10.9
 - See below
 - Aside from CE and Active Tiles, no active modules. Clear world

**Comment by ironmonk88** [comment]
Fixed in the latest release.
