### ISSUE TITLE
[BUG] Door Triggers, Multiple Tags

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#395]
A door trigger targeting multiple Tags fails to trigger any of the tiles; no issues when targeting a single Tag that exists in multiple tiles. Nothing in the console. 

![image](https://user-images.githubusercontent.com/99844555/209610747-a856aa77-1d34-4915-bad5-b196fb3c7297.png)

https://user-images.githubusercontent.com/99844555/209610757-1a5301e6-63e7-4196-be3e-8155df36114e.mp4

Scene with setup included. 

[fvtt-Scene-matt-395.zip](https://github.com/ironmonk88/monks-active-tiles/files/10305919/fvtt-Scene-matt-395.zip)

MATT 10.9
Tagger 1.3.9
Foundry 10.291

**Comment by ironmonk88** [comment]
Fixed in the latest release.
