### ISSUE TITLE
[Feature Request] Journal Secret Text Show/Hide action.

### ISSUE THREAD

**Issue by Grandsome** [ironmonk88/monks-active-tiles#396]
Add show/hide action for a journal secret text.

See "Secret Text" in [Journal Entries](https://foundryvtt.com/article/journal/)

**Comment by ironmonk88** [comment]
I think this goes beyond what MATT should be capable of doing.
That's probably more suited to a Macro.
Writing to a Journal Entry is about as far as I want to go, and I don't think MATT is the module to manipulate Journal Entry text.
