### ISSUE TITLE
[BUG] Brief description of your issue

### ISSUE THREAD

**Issue by SalieriC** [ironmonk88/monks-active-tiles#397]
**Describe the bug**
The delete action of a tile fails if that tile is locked. I've only tried using "this tile" but might be true when other tiles are affected as well.

**To Reproduce**

1. Set up a tile and lock it.
2. Set the tile up to trigger on click.
3. Set up the action to delete _this tile_.
4. Click the tile. - It won't be deleted.

**Expected behavior**
Tile should be deleted even if locked.

**Screenshots**
![image](https://user-images.githubusercontent.com/1230041/210135555-82eef0d0-0b98-44f2-9a8b-7c3332532c32.png)

![image](https://user-images.githubusercontent.com/1230041/210135700-8c626c54-5c60-4928-8df6-86cca7d0faf3.png)
In this example, both, Sound and light are deleted as expected but the triggering tile is not as it is currently locked. It works if the tile is manually unlocked first.

**Please complete as much of the following information as possible:**
 - Browser: Chromium based.
 - Foundry Version: 10.291
 - System: SWADE v.2.1.7
 - Module version: 10.9
 - Errors in the console: See screenshot above.
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: No. Rather sure it's MAT due to the error in the console.

**Additional context**

**Comment by ironmonk88** [comment]
That's the purpose of locking a Tile, so it can't be deleted accidentally.
I'm not going to go against a core Foundry feature.
The error itself is an issue if there were no entities to be deleted and that's been fixed.
But if you want to delete a locked Tile, then you'll have to run an alter action to remove the locked condition first.
