### ISSUE TITLE
[BUG] Reset History Error

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#399]
![image](https://user-images.githubusercontent.com/99844555/210301802-f9d56364-6f64-4578-aaef-6bd137ee1350.png)

Only occurring on 1 scene I have when I run a tile that resets everything; not sure what's so special there, but I can send you a copy of the scene if I need to.

MATT 10.10
Foundry 10.291

**Comment by Crowguard** [comment]
Figured out the cause; it happens if a tile without History active is targeted with the Reset History action.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
