### ISSUE TITLE
Same option with token instead of tile ?

### ISSUE THREAD

**Issue by uniwars** [ironmonk88/monks-active-tiles#4]
Would that be possible to add the same option for a token in the token settings menu and not a tile ? It could save some time to just put an invisible token on the map with all the trigger's effect on it rather then putting a tile and if the GM want to store the trigger's effect like for example to store a set of trap he actually need to sue token attacher but if the effects was directly linked to a token it would be faster and easier.

**Comment by powametal** [comment]
This, and add the mouse click trigger to make cool switches

**Comment by Iankid** [comment]
I 2nd this

**Comment by ironmonk88** [comment]
Closing this because I think with the added actions available and the On Click event added, this should be covered.
I think adding it to a Token is a bit outside the scope of this module.
