### ISSUE TITLE
Error when requesting rolls

### ISSUE THREAD

**Issue by LowerMechancial** [ironmonk88/monks-active-tiles#40]
When attempting to trigger a roll, this error appears:
```
Uncaught (in promise) TypeError: Cannot read property 'uuid' of undefined
    at savingthrow.js:131
    at Array.map (<anonymous>)
    at SavingThrowApp.requestRoll (savingthrow.js:128)
    at HTMLButtonElement.i (jquery.min.js:2)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)
```
I've attempted all settings of When (On Enter, One Exit, ect).
I've attempted all Select Entity settings (Select an Entity, Use the triggering Token, ect.)
I've also attempted using Bypass Dialog and Autoroll in different combinations. Of note when both options are unchecked; which causes the dialog to appear, selecting the "Request" button will also produce the same error.

**Comment by ironmonk88** [comment]
This is technically a Tokenbar issue, and I believe has been fixed.
Cleaning up and closing the ticket.
