### ISSUE TITLE
[BUG] Reset History; 10.10 Changes

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#400]
Reset Tile Trigger History action doesn't work without a token selected at all, and even with a token selected, there doesn't seem to be a way to reset the entire history the way it previously functioned.

https://user-images.githubusercontent.com/99844555/210467365-910187fa-3132-455d-ba2f-bafd50381e97.mp4

MATT 10.10

**Comment by ironmonk88** [comment]
Fixed in the latest release.
