### ISSUE TITLE
[BUG] Pan Canvas, to Player Tokens

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#401]
This action isn't working when the target is Player tokens. No errors on either GM or player side. Not sure if its the same as #379 or not, this is the first time I've tried since that one was closed.

MATT 10.10
Foundry 10.291
D&D 5e 2.0.3
FTC ✔️

**Comment by Crowguard** [comment]
![image](https://user-images.githubusercontent.com/99844555/211384841-8c7de04a-25a4-4092-9ea7-4cf2bbb5ddbe.png)

Just the Pan Canvas on its own. Maybe its something you've already fixed in yours? I'll ask Wizard to test out in his.

**Comment by ironmonk88** [comment]
Closing this as it looks like some weirdness with tokens.
