### ISSUE TITLE
[BUG] Write to Journal, Current Journal

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#404]
No text is written to a journal using this setup. Either MEJ or core journals. No errors. Not really a big deal I think, but I thought I'd log it anyway.

![image](https://user-images.githubusercontent.com/99844555/210951421-b98f3606-0aac-4dbb-828d-92176a2cfa55.png)

MATT 10.10

**Comment by ironmonk88** [comment]
Fixed in the latest release.
