### ISSUE TITLE
[BUG] Playlist (Current Action Collection)

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#406]
A playlist set to Current Playlists does not play the results of the previous rolltable result. No errors.

![image](https://user-images.githubusercontent.com/99844555/211725267-4ccb3d59-4edc-467d-a98c-0fd9d919a4c1.png)

MATT 10.11
FTC ✔️

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
