### ISSUE TITLE
[BUG] Create Tokens (from MEJ Encounter)

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#407]
When the Create Token action is targeting a MEJ encounter and the actions run, no tokens are created. No errors in the console. Works as expected targeting an actor.

![image](https://user-images.githubusercontent.com/99844555/211736187-8e1975ab-1cd8-44f4-b7ec-4c4edf3a99b2.png)

https://user-images.githubusercontent.com/99844555/211736211-7f0bfe66-4288-404f-9338-9abb76b3936d.mp4

Foundry 10.291
MATT 10.11
MEJ 10.10

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
