### ISSUE TITLE
[BUG] Open Actor Sheet (Current Actors)

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#408]
Does not open the result of the preceding roll table action. No errors.

![image](https://user-images.githubusercontent.com/99844555/211900721-9d3d8698-0da9-41f9-9c94-6f1ae89834e9.png)

MATT 10.11
Foundry 10.291
D&D 5e 2.1.0

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
