### ISSUE TITLE
[BUG] Brief description of your issue

### ISSUE THREAD

**Issue by laaruk** [ironmonk88/monks-active-tiles#409]
Hello, Ironmonk! With the system update the module has a bug: does not add an item to the inventory of a character/
1. Create tile
2. **Setup**: doubleclick, anyone.
3. **Actions**, add item, for triggering token.
On double-click, the player's character must get the item.
https://imgur.com/fnXmzSa
https://i.imgur.com/fnXmzSa.png
https://imgur.com/bAILdaB
https://imgur.com/V2OB4VK
Browser Microsoft Edge, not errors on f12. Before the system (dnd5e) update, a couple of days ago, everything was working.

**Comment by Crowguard** [comment]
I can confirm this; no errors in the console.

Foundry 10.291
D&D 5e 2.1.2
MATT 10.1

**Comment by ironmonk88** [comment]
Double-click won't work for something like adding an item, because the first click deselects the token, therefore the second click has no target to add the item to.
It's part of how Foundry functions, switch to single click and it will work.
