### ISSUE TITLE
[BUG] Trigger Tile Via Journal Link

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#413]
Chat message actions fire twice when a tile is triggered from a journal. As you can see with the tile moving, its not the entire action sequence, just the message.

https://user-images.githubusercontent.com/99844555/213347507-3cb8c7d7-7a2a-4a34-a16a-c15eae7881f1.mp4

MATT 10.11
Foundry 10.291
5e 2.1.2

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
