### ISSUE TITLE
[BUG] Hurt/Heal, PF2e

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#414]
Hurt/heal doesn't work on PF2. 
![image](https://user-images.githubusercontent.com/99844555/213805722-e8f9de68-3a91-4b78-840a-7c9e9de952d7.png)

Foundry 10.291
MATT 10.11
PF2 4.6.8

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
