### ISSUE TITLE
[BUG] Current Scene Collection

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#415]
![image](https://user-images.githubusercontent.com/99844555/213900278-9d090491-2ac6-4c0b-a3ec-4bef1e17e233.png)

`Current Scene Collection` is displaying as `Unknown Scene` in the action list; should probably be updated so it doesn't look like a broken scene link.

MATT 10.11

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
