### ISSUE TITLE
[BUG] Brief description of your issue

### ISSUE THREAD

**Issue by jasharen** [ironmonk88/monks-active-tiles#417]
**Describe the bug**
I am creating a landing page for my campaign using active tiles set up to run a macro. In this case, open character sheet.

game.actors.getName(character.name).sheet.render(true);

I have set security on the base macro for all players as owner, and then connected it to a tile to run as player. When the user clicks the tile, nothing happens initially.

If they then trigger the same macro from their macro toolbar, everything works. Then after that, if they click on the tile the macro works.

Additionally, if I as the GM execute the macro from the toolbar, it then works for the rest of the players logged in at the time. So it seems that 'someone' needs to click the toolbar version first and then it works for everyone.

**Expected behavior**
Macro to run initially.

**Please complete as much of the following information as possible:**
 - Browser 
       chrome
 - Foundry Version -
      10.291
 - System 
      Fate Core Official
 - Module version 10.11
 - Are there any errors in the console [e.g. press F12 and look for red text]
  No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.
Yes - Indicated that the problem was in Active Tile Triggers

**Comment by ironmonk88** [comment]
You could also do it straight from MATT.
![image](https://user-images.githubusercontent.com/75920956/214776215-0bf5e3a5-43e9-41c1-a355-3d07159a5051.png)

**Comment by jasharen** [comment]
That worked for the character sheet, however I have a couple other macro's that this does not resolve the problem for unfortunately.

Example:
window.Ardittristan.InlineViewer.sendUrl("URL", compat = false, w = 1980, h = 1024, 'Journal')

**Comment by ironmonk88** [comment]
Added the missing properties to the function that execute the player macro.
