### ISSUE TITLE
Prevent footer from being included in the WallConfig's 'Basic' tab

### ISSUE THREAD

**Issue by Aedif** [ironmonk88/monks-active-tiles#419]
**Is your feature request related to a problem? Please describe.**
I'm implementing some features for **Mass Edit** module that require insertion of a footer in WallConfig form. At the moment Active Tiles packages up everything but buttons into the `Basic` tab.

**Describe the solution you'd like**
Update the `$('> *:not(button)', root)` selector to instead be `$('> *:not(button):not(footer)', root)`

**Additional context**
Without footer exclusion:

![withoutFooterExclusion](https://user-images.githubusercontent.com/7693704/214901930-57fb274f-12dd-4dea-b555-da1e471bb525.gif)

With footer exclusion:

![withFooterExclusion](https://user-images.githubusercontent.com/7693704/214902106-df4cae70-9161-4585-a1a6-22ab0a46f47e.gif)

Regular forms still behaves the same.

**Comment by ironmonk88** [comment]
Should be added to the latest version
