### ISSUE TITLE
Selecting Multiple Targets for a Trigger

### ISSUE THREAD

**Issue by d1no1** [ironmonk88/monks-active-tiles#42]
In the same way we can change the state of an object (light, tile, sound, door, etc), one at the moment with each action trigger, could you please allow us to target several so that, for example:
- instead of 3 triggers to change state of 3 lights, 1 trigger would change the state of 3 lights.

The selecting tool would need to be expanded to allow selecting another target after the first and form a list.

**Comment by ironmonk88** [comment]
Closing this as Active Tiles has Tagger support.  So you can use Tagger to label the three lights and use the tag to alter them all with one action.
