### ISSUE TITLE
[BUG] new tagger update throws error 

### ISSUE THREAD

**Issue by WizardForHire123** [ironmonk88/monks-active-tiles#420]
**Describe the bug**
Seems to work functionally but throws a hook error on a tile action believe it’s related to the new tagger update 

**To Reproduce**

1. Add an action such as move with a tag
2. Activate tile
3. Profit?
4.
![3BD17396-072C-4E86-BA96-E0748EB5A95A](https://user-images.githubusercontent.com/98988680/215110046-757e8016-b66d-45bc-83ab-5bc504969397.png)
![92E2192D-8304-4C8F-884C-6FEEC4D54B37](https://user-images.githubusercontent.com/98988680/215110052-43165eba-4d52-4de4-a680-41794b96e20d.png)

**Expected behavior**
No error

**Please complete as much of the following information as possible:**
 - assume that it's connected to the Tagger update. Tagger is 1.4.1, MATT is 10.11. Yes, it's an unlinked token but the actor is there stored in the actor list. V10 and dnd5e 2.1.4
 - it's not actor-dependent, it throws out similar error when I tag a tile - and the tiles also moves according to what's in the other tile setup.
 - 
 reported by Ratzing on the discord 
https://discord.com/channels/862414864692281386/862421211749154816/1068534743794200646

**Comment by Haxxer** [comment]
Fixed with: https://github.com/fantasycalendar/FoundryVTT-Tagger/issues/24

**Comment by ironmonk88** [comment]
Closing as it's been fixed with the tagger update.
