### ISSUE TITLE
Add option for Open Image to trigger action list

### ISSUE THREAD

**Issue by AmaranthaArandir** [ironmonk88/monks-active-tiles#421]
I would like to be able to open an image directly from a tile. 

I can set the tile trigger to open a journal and specify it to go to the journal page that contains the image but a user still has to click on the image to get directly to the image display. 

I'd like to click on the tile and go directly to the image like I'm zooming in to do a close inspection. 

![image](https://user-images.githubusercontent.com/123832847/215284797-4d50049a-5603-42de-87bd-ed589cc43bce.png)

**Comment by Crowguard** [comment]
@AmaranthaArandir Already a thing.
![image](https://user-images.githubusercontent.com/99844555/215389752-f2c86a8b-35ba-4832-920e-befa949b9984.png)

**Comment by ironmonk88** [comment]
Closing as this is already an action

**Comment by AmaranthaArandir** [comment]
Awesome. thanks! I guess I was looking for "Open Image" instead of "Show"
