### ISSUE TITLE
[BUG] Move, Tokens Within Tile

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#423]
This is only moving 1 token at a time; it seems to default to the oldest token again.

Edit: Seems to be applying to moving multiple Tagged tokens as well.

https://user-images.githubusercontent.com/99844555/216420647-8b7a4f35-e845-4b42-8e55-cc64bd552178.mp4

MATT 10.11
Foundry 10.291

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
