### ISSUE TITLE
[BUG] Hurt/Heal Targeting

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#427]
Hurt/Heal probably shouldn't be able to target anything besides tokens; it can currently target the following things that can't be healed

- Drawings
- Lights
- Notes
- Sounds
- Tiles
- Walls

![image](https://user-images.githubusercontent.com/99844555/216804812-3224f1c1-a3fa-4466-ad45-0bdc8dee18c7.png)

It lets you select Terrain, but errors right away.

![image](https://user-images.githubusercontent.com/99844555/216804899-61f5359b-91df-4ea1-a11c-7080488119dc.png)

MATT 10.12

**Comment by ironmonk88** [comment]
Huh.  How long has that been in there like that.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
