### ISSUE TITLE
[BUG] Specific tile configuration stopped working with 10.11

### ISSUE THREAD

**Issue by DarKDinDoN** [ironmonk88/monks-active-tiles#429]
**Describe the bug**
I had a tile configuration that worked great with 10.10, but since 10.11, it stopped working.
Double clicking on the tile does nothing.
The configuration remains the same.
There are no errors in the console.

**To Reproduce**
Here is the configuration of the tile:
![untitled](https://user-images.githubusercontent.com/1687854/216839782-47f6ca3b-69eb-4925-85ed-decaad48bb5c.jpg)

It is placed on an overhead tile that is also hidden from players and activated manually with a double click (only for GM).
It works by:
- Finding a black squared drawing that is not hidden
- if hidden, it proceeds to set its fillAlpha to 1 and show the drawing (even tho the configuration window read "current token")
- If not hidden, set its fillAlpha to 0.1 and hide the drawing

This is a simple trigger to hide parts of the map with black squared drawings and reveal them (parts of the map) on a double click. The fillAlpha thing is just to make it, so the GM is less annoyed by a transparent black drawing when the black squared drawing is supposed to be hidden.

**Expected behavior**
Double-clicking on the tile should trigger the actions.

**Please complete as much of the following information as possible:**
 - Browser Chrome/Firefox
 - Foundry Version V10
 - System Chroniques Oubliées Contemporain
 - Module version 10.11 & 10.12
 - Are there any errors in the console -> no
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction -> no but tried only with this module activated

**Comment by ironmonk88** [comment]
Technically it's working correctly now.  I fixed a bug that was putting everything into the tokens list even if they weren't tokens.
So, everything after the first action should be using `Current Drawings` instead of `Current Tokens`.
Problem is... Alter is missing a bit of code and won't let you select the correct collection.  It's been fixed, but won't be available until the next release.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
