### ISSUE TITLE
[BUG] Alter, Current Tokens

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#431]
Altering `Current Tokens` only applies the changes to one token at a time when the attribute being changed is an actor attribute and not a token one.

It results in this in the log for the token not being altered. 
![image](https://user-images.githubusercontent.com/99844555/217716323-5794380e-b6ef-48e1-ac72-5c2a9f1aba52.png)

https://user-images.githubusercontent.com/99844555/217716083-32a9b7a4-a13f-4f86-bd4f-8164729d54d5.mp4

MATT 10.12

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
