### ISSUE TITLE
[BUG] Left-Click to Release Objects Broken

### ISSUE THREAD

**Issue by Xenophes** [ironmonk88/monks-active-tiles#432]
Normally when you have the Left-Click to Release Objects setting in Core settings toggled, clicking on something like a door doesn't cause you to release control of the object, however with this module enabled, it does (tested using only this module enabled).

1. Select object (like a token).
2. Activate a door on the canvas.
Your token is then deselected.

Normally activating a door with this setting enabled does not cause your token to be deselected, allowing you to manipulate objects of the canvas while still retaining control of your token.

 - In Foundry Client
 - v10
 - D&D 5e
 - Module Version 10.12

**Comment by ironmonk88** [comment]
![image](https://user-images.githubusercontent.com/75920956/217961353-325e32bb-8fdd-4ccc-afc0-98737098bcbb.png)
Turn off the door click through setting.
It's an issue with Foundry that I can't really work around when providing that functionality.
