### ISSUE TITLE
[BUG] Change Scene

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#433]
The action list no longer displays the scene name.

Edit: There's some inconsistency in this. In D&D 5e & PF2, it displays `Active Scene` for me, but not anything else, while in the Cypher system it displays everything.

![image](https://user-images.githubusercontent.com/99844555/218006061-fcc63ab4-741a-48dc-b3fe-ae242d008dff.png)

MATT 10.12

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
