### ISSUE TITLE
[BUG] Exit trigger won't allow movement away from the tile on SWADE system.

### ISSUE THREAD

**Issue by SalieriC** [ironmonk88/monks-active-tiles#434]
**Describe the bug**
When the _exit trigger is used, the tile cannot actually be left on the SWADE system when a delay action is used, movement is cancelled and the actions trigger but the token can't be moved.

**To Reproduce**
1. Use a SWADE world.
2. Set up a tile similar to the screenshot below.
3. Try to move a token away from that tile.

**Expected behavior**
Actions should allow movement away from the tile and only execute after the token moved away from the tile when a delay action is used.

**Screenshots**
![image](https://user-images.githubusercontent.com/1230041/218344571-64213bc1-13eb-45c4-973c-cf3342b6ea44.png)

![image](https://user-images.githubusercontent.com/1230041/218344614-e1ec150c-21ac-450c-b064-08320200d259.png)

[4.webm](https://user-images.githubusercontent.com/1230041/218344624-44e51131-378f-4e78-8a04-0ebe000791ef.webm)

**Please complete as much of the following information as possible:**
 - Browser: Chromium
 - Foundry Version: 10
 - System: SWADE
 - Module version: 10.12
 - Are there any errors in the console?: No.
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction?: Yes, it happens with all other modules deactivated.

**Additional context**
It's worth mentioning that very rarely the token can be moved away but this cannot reliably be reproduced. When testing and it doesn't happen, try again please.
Additional context on Discord starting at this message: https://discord.com/channels/862414864692281386/862421211749154816/1074469748529713162

This is especially breaking as it means the tile needs to be deactivated, moved or deleted in order to regain movement control over the token.

**Comment by ironmonk88** [comment]
Not a bug.
The Stop Movement action applies regardless of where it is in the action list.  This is a limitation in MATT that it needs to stop a token before it knows the exact path of actions the code is going to take.  If it didn't do this, then you'd find tokens moving forward, suddenly stop and reverse back to the point where they were supposed to have stopped.
You can work around this, but adding a Move Token action that uses the "Original Destination" as the destination.

**Comment by ironmonk88** [comment]
On a second look.  You wouldn't happen to be using Monk's Tokenbar would you?
Is that token set to prevent movement using Tokenbar?

**Comment by SalieriC** [comment]
No, not using Tokenbar. Thanks for the clarification. =)
