### ISSUE TITLE
[BUG] Elevation

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#436]
The elevation action fails when used with an `=` in front of the number. I can't actually remember if it ever worked before, but just for consistency with other actions it probably should.

![image](https://user-images.githubusercontent.com/99844555/218942180-4fd8495f-c221-4b8e-99a0-98b338d0e1f9.png)

![image](https://user-images.githubusercontent.com/99844555/218942154-6afb0b15-9d5b-4b00-b401-84c1da7e9e92.png)

MATT 10.12

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
