### ISSUE TITLE
[BUG] Teleport Triggers

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#437]
A user has a Foundry setup where tiles with teleport don't trigger. I tried various clicks & enter; everything resulted in this error. Existing and newly created tiles.

Another edit: Tried with and without the `Use transparency` option on the tiles. Didn't matter.

I've been unable to replicate this in my various worlds so far.

https://user-images.githubusercontent.com/99844555/219577296-7890cc0d-b5bb-46a4-9c79-9aa70787ef94.mp4

MATT 10.12
Foundry 10.291
D&D 5th 2.1.4
FTC ✔️ 

Foundry Virtual Tabletop: Version 10, 10.291
Game System: dnd5e, 2.1.4
Active Modules: 91
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
GPU: ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 3180 x 4540 | Grid Size: 50 | Padding Percentage: 0.05
Walls: 152 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 10 | Tokens: 6

Actors: 1106 (1 Invalid) | Items: 172 | Journal: 164 | Rollable Tables: 13 |
Playlists: 4 | Compendium Packs: 141 | Chat Messages: 2

**Comment by Crowguard** [comment]
Update: user originally said it was all actions, but is now saying its only `Teleport`.

**Comment by Wink8008** [comment]
Same problem for me

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
