### ISSUE TITLE
[BUG] Convenient effects not populated for dfreds 4.x

### ISSUE THREAD

**Issue by gregpola** [ironmonk88/monks-active-tiles#443]
**Describe the bug**
With dfreds-convenient-effects updated to 4.x, the convenient effects are no longer populated for tile actions.

**To Reproduce**
1. Update dfreds-convenient-effects to the latest
2. Create a tile
3. Add an action of type DFred's Convenient Effect
4. See no Effects populated in the drop-down

**Expected behavior**
The drop-down populated with the convenient effects

**Comment by Dairid** [comment]
I am having the same problem.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release

**Comment by DatManRandom** [comment]
I just installed the mod recently so I might be doing something wrong, but I get this same issue only for the "Filter by convenient effect" action type, the normal "Convenient Effect" action type has the "Effect*" field populated normally.

<img width="549" alt="image" src="https://user-images.githubusercontent.com/52916544/235370864-91d89573-0747-48df-8047-6abad23ace9a.png">
