### ISSUE TITLE
[BUG] Trigger Methods Display, Call of Cthulu

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#446]
The field only displays the first trigger method.

https://user-images.githubusercontent.com/99844555/224444201-023937ee-05db-439a-acd3-211372022988.mp4

![image](https://user-images.githubusercontent.com/99844555/224444224-bed3107a-bd8a-4c7f-9e6b-a00e197841e3.png)
MATT 10.12

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
