### ISSUE TITLE
MAT Landing color codes

### ISSUE THREAD

**Issue by Vralek** [ironmonk88/monks-active-tiles#447]
I'm always frustrated when something fires off on a landing that I meant for a different landing. I feel it would aid the community if it were easier to see at a glance where something is triggering.

I'd love to the landings have a section to choose a color and highlight in some way anything that is going to trigger under said landing in the MAT triggers screen, see screenshot. If it could highlight these either fully or with a line around them similar to how Mass Edit does, that would be great.

![Snag_269bd26c](https://user-images.githubusercontent.com/90917755/224789648-ae8ad951-6e55-4c0f-b9a6-0a9e794aae6e.png)

The colors can be just a simple color picker like what is available on : http://crowguide.wikidot.com/color-selector-hexcode-method

**Comment by ironmonk88** [comment]
Closing as this has been added to an active release.
