### ISSUE TITLE
[BUG] Brief description of your issue

### ISSUE THREAD

**Issue by ssveter1** [ironmonk88/monks-active-tiles#448]
**Describe the bug**
Attack rolls are not being triggered by active tiles
The tile is triggering this button
![image](https://user-images.githubusercontent.com/10831302/225436589-e81d8649-5a78-40de-9d98-b7c95b19552e.png)
When it should be triggering this one.
![image](https://user-images.githubusercontent.com/10831302/225436693-22fea4d4-4ab5-4a3f-add6-8c239c095a25.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete as much of the following information as possible:**
 - Desktop
 - Foundry Version v10 build 2.91
 - System Pathfinder 0.82.5
 - Module version
 - Are there any errors in the console [e.g. press F12 and look for red text]
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.

**Additional context**

**Comment by ironmonk88** [comment]
![image](https://user-images.githubusercontent.com/75920956/230839331-60aebbc4-3ddc-4352-b947-6967fac76ae7.png)
Check this checkbox.

**Comment by ironmonk88** [comment]
Closing this as there hasn't been a response and the interface has changed since then.
