### ISSUE TITLE
Detailed Target Clearing

### ISSUE THREAD

**Issue by BarovianBadass** [ironmonk88/monks-active-tiles#453]
When adding targets, we can select specific targets. Can we get that same feature when clearing targets. The only option available currently is to clear ALL targets. This doesn't help when having a set chain of events in place. You find yourself clearing all targets and then targeting specific ones again.
![Target Add](https://user-images.githubusercontent.com/112812283/226754304-0e01a83a-0b7e-46d2-8f3e-67e77dbe955e.png)
![Target Clear](https://user-images.githubusercontent.com/112812283/226754316-22ecbb97-97d2-4546-8b12-400f49a65278.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
