### ISSUE TITLE
[BUG] Rotation Trigger

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#454]
This trigger is going off even when tokens are not within the tile. Not sure if this is intended or not.

https://user-images.githubusercontent.com/99844555/227755806-2463fa21-5caa-4cc3-97ed-be48a3e76300.mp4

MATT 10.12

**Comment by ironmonk88** [comment]
Also affects elevation

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
