### ISSUE TITLE
Chat Message - Tagger

### ISSUE THREAD

**Issue by BarovianBadass** [ironmonk88/monks-active-tiles#457]
Can Tagger be added to the options for Speaker in the Chat Message trigger please.

![image](https://user-images.githubusercontent.com/112812283/228529072-cb31133c-e5dc-4399-bff3-515141cd4914.png)

**Comment by BarovianBadass** [comment]
Who it is being said to would also be nice. That way it can be whispered to entities with specific tags.

![image](https://user-images.githubusercontent.com/112812283/228555696-4725d182-ecd1-4e68-9512-ae2d7ecb3207.png)

**Comment by ironmonk88** [comment]
First part was fixed in a previous release.
Added the option to send a message to the current users. This way you can set the current collection of users to whatever list you want to whisper to and use that as the chat recipients.
