### ISSUE TITLE
[BUG] Alter, Terrain

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#460]
Targeting terrain with Alter results in this.

![image](https://user-images.githubusercontent.com/99844555/230514444-e6c29826-e3e9-4876-b2c1-eea0e8001a3d.png)

https://user-images.githubusercontent.com/99844555/230514402-56f77dc6-5544-41f7-8b90-bb77224a2e9e.mp4

MATT 10.12
Foundry 10.291
ETL 10.6

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
