### ISSUE TITLE
[BUG] Hurt/Heal, Add Chat Message

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#461]
This action fails and errors when this button is checked; runs normally when unchecked.

![image](https://user-images.githubusercontent.com/99844555/230732587-4cad23b0-1340-436d-ab0b-c70cf6496f79.png)

![image](https://user-images.githubusercontent.com/99844555/230732600-c1327b7d-41fd-4af9-8813-62433889643c.png)

MATT 10.12
5e 2.1.5
Foundry 10.291

**Comment by Crowguard** [comment]
Seems to be fixed in MATT 10.14.

**Comment by ironmonk88** [comment]
I think I fixed this?
