### ISSUE TITLE
[PF2e] Add Player Tokens to Combat incorrectly adds minions

### ISSUE THREAD

**Issue by maplealmond** [ironmonk88/monks-active-tiles#462]
In the PF2e System, Add Player Tokens to Combat will add Familiars to the initiative.  Despite being a player-controlled token, Minions should never have their own initiative.

Although possible to correct, it would be nice if this was handled correctly in PF2e out of the box.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.

**Comment by maplealmond** [comment]
Confirmed this is working as expected now.  Thank you!
