### ISSUE TITLE
[BUG] Chat Message & Polyglot

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#463]
A chat message made using Polyglot results in this error; does not seem to be affecting anything though.

![image](https://user-images.githubusercontent.com/99844555/231540054-8c08d659-58b3-4b52-8aa4-bb357ddeeb79.png)

Also, the display seems to have changed slightly and displays the system now too; I believe it just uses to say the Language name.

![image](https://user-images.githubusercontent.com/99844555/231539648-66cd1239-cebb-4d22-bca3-f1e9e8d2bc6e.png)

MATT 10.14
Polyglot 1.8.13
PF2e 4.10.4

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
