### ISSUE TITLE
[BUG] Wrong wiki link

### ISSUE THREAD

**Issue by Gabryel666** [ironmonk88/monks-active-tiles#465]
**Describe the bug**

Just a error on the readme.md.
This is the old wiki link : http://crowguide.wikidot.com/monk-s-active-tile-triggers
Please update to : https://github.com/ironmonk88/monks-module-wiki/wiki/Monk%27s-Active-Tile-Triggers

Thx :)

**Comment by ironmonk88** [comment]
Fixed.  Thank you.
