### ISSUE TITLE
[BUG] Show Dialog, Multiple GMs

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#466]
A `Show Dialog` for `Token Owner` is presented to a player multiple times when multiple GMs are logged in. Does not show multiple times for one of the gamemasters, it has to be a player who triggers it.

https://user-images.githubusercontent.com/99844555/231972505-6960e4da-3580-4c01-8b60-a3539c875658.mp4

MATT 10.15
FTC

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
