### ISSUE TITLE
[BUG] Teleport, Multiple GMs

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#467]
`Teleport` between scenes with multiple GMs or assistant GMs logged in results an extra, unmovable token being created on the destination scene.

https://user-images.githubusercontent.com/99844555/232564394-33f6dcc4-03b6-4118-aaf8-eb3c0dbdf424.mp4

![image](https://user-images.githubusercontent.com/99844555/232564533-17cd7827-ad39-4f83-b5a0-15a6d88ed542.png)

MATT 10.15
Foundry 10.291

**Comment by devteamplus** [comment]
Also, to confirm, this does not occur when a "Trusted Player" is logged in - even if that player is given all the same permissions as an Asst GM or GM.  I have confirmed this with two additional players logged in as Trusted Players.  However, as soon as an Asst GM or additional GM player logs in, this issue occurs.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
