### ISSUE TITLE
[Feature Request] PF2 Compendium Search Integration

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#472]
This one is probably best left for after V11 and the compendium changes, but it would be nice to be able to target entities found using the compendium search that PF2 has implemented.

https://user-images.githubusercontent.com/99844555/233906785-a474d975-7dca-4952-b280-2cd0c5753730.mp4

**Comment by ironmonk88** [comment]
Added to the latest release.
