### ISSUE TITLE
[BUG] Rotation

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#473]
If a Rotation action would rotate the token to 360 degrees or higher, it instead rewinds until it reaches the correct rotation. This is how token rotation with a mouse was working when V10 came out, and I think this might just be some holdover behavior; now rotating a token goes smoothly past 360.

https://user-images.githubusercontent.com/99844555/234641470-c1c8153e-358a-49bd-a33b-28623d8d3edf.mp4

MATT 10.15
Foundry 10.291
FTC

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
