### ISSUE TITLE
[Feature Request] Color Contrast with Dorako UI

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#474]
Some action list colors are difficult to pick out when using Dorako UI's dark mode.
![image](https://user-images.githubusercontent.com/99844555/234769033-4e2338fd-678d-47c2-95d5-0a851ac057f3.png)

**Comment by ironmonk88** [comment]
I think this should be opened with Dorako UI.  They already have a css file for other Monks css changes.

**Comment by Crowguard** [comment]
https://github.com/Dorako/pf2e-dorako-ui/issues/193
