### ISSUE TITLE
`Run Macro` as `Everyone`

### ISSUE THREAD

**Issue by PlasticMohawk** [ironmonk88/monks-active-tiles#475]
**Is your feature request related to a problem? Please describe.**
Below is an example of a macro window setting where I can run the macro on everybody's client when I execute it.

![image](https://user-images.githubusercontent.com/5216225/235163391-acea8b71-d54f-4bd8-894e-3255c0b098ed.png)

If I use the `Run Macro` MATT command, my only options are `Triggering Player` and `GM` - not everybody. So running the above macro from a MATT command won't produce the same results from the macro.

**Describe the solution you'd like**
Add option to `Run Macro` to run on everybody's client at once.

**Additional context**
My use case is I'm setting up macros which programmatically generate ChatMessage content in a whisper to each player. When the `Run Macro` MATT command is triggered, I want every active player (including me, the GM) to receive a whisper with different content as per the results of the macro at the same time.

**Comment by ironmonk88** [comment]
I've added the option to loop through users now, which will allow you to run the macro for each user.
The Macro itself hasn't changed, but you can get the user that it's being sent to it through `arguments[0].entities[0]`
