### ISSUE TITLE
`Create Token` at position relative to triggering tile

### ISSUE THREAD

**Issue by PlasticMohawk** [ironmonk88/monks-active-tiles#476]
**Is your feature request related to a problem? Please describe.**
I want to be able to place a triggering tile anywhere on the canvas, and, on trigger, create a token 50px to the right of the triggering tile.

![image](https://user-images.githubusercontent.com/5216225/235214844-dcdeb86b-4e8c-4f63-8f76-08a0d7d363c5.png)

**Describe the solution you'd like**

Under `Edit Location Details` I would like to enter relative values (see screenshot above) which would imply (in the above example), "Place the created token 50px to the right of the triggering tile's position".

**Additional context**

**Comment by ironmonk88** [comment]
Added a comment to the Discord server.
But I think for this use case you'd create the token in the center of the Tile and then use the Move action to move it relative to the token's current position.

**Comment by ironmonk88** [comment]
Closing this as there is an alternative that should work.
