### ISSUE TITLE
[BUG] MATT tile rolling a roll table will insert extra copies of a macro's ID info recursively into its name on the roll table.

### ISSUE THREAD

**Issue by PlasticMohawk** [ironmonk88/monks-active-tiles#478]
**Describe the bug**
I have a roll table set up with an assortment of macros. I have a MATT tile which rolls on that roll table when I click the active tile. Eith each subsequent click of the tile, there is a chance of the macro's chat message id being injected into the name field on the roll table result recursively, so each roll table result's name will grow longer and longer with copies of the same data.
**To Reproduce**
1. Set up a roll table with a few macros as results on the roll table.
2.) Set up a MATT tile to roll on that roll table.
3.) Trigger the MATT tile 10 or so times, and check the roll table.
4.) You should see the name fields of at least some line items on the roll table are filled with junk data about the macro itself. You should also see this in the chat messages every time you trigger the MATT tile.
5.) This can also cause breaking issues in the roll table itself, causing the user to have to rebuild the table.

**Expected behavior**

I expect the MATT tile to roll multiple times on the roll table without altering the roll table's name data. 

**Screenshots**

![image](https://user-images.githubusercontent.com/5216225/235279829-90e254ab-6833-4dbc-91d8-65da09d1d84e.png)

![image](https://user-images.githubusercontent.com/5216225/235279978-c085df2d-736b-4588-9fc4-cc79935647d7.png)

![image](https://user-images.githubusercontent.com/5216225/235280211-88a7d33c-0838-4ebc-9b15-9a4871b85571.png)

**Please complete as much of the following information as possible:**
 - Chrome 112.0.5615.138
 - Foundry v10
 - System: PF2E
 - Module version 10.15
 - Are there any errors in the console? No obvious errors
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction? FTC Screenshot included.

**Additional context**

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
