### ISSUE TITLE
Quantity field missing from "Filter by Items in Inventory" action

### ISSUE THREAD

**Issue by TofuPotato** [ironmonk88/monks-active-tiles#479]
I checked the wiki on how this works but I don't see the quantity field on my end. Item count isn't enough as I need to check the quantity field in dnd5e. I'm running foundry on version 9, I'm not sure if that's the issue.

My POV
![image](https://user-images.githubusercontent.com/52269305/235292500-40baf6ec-893a-4758-9f48-5db5b02d60ca.png)

The wiki
![image](https://user-images.githubusercontent.com/52269305/235292530-39b27bf0-5730-4ead-b4a6-b1d73c3d22cf.png)

If this was removed for some reason I hope it's added back soon :(

**Comment by Crowguard** [comment]
@TofuPotato That wasn't added until some point in V10.

**Comment by TofuPotato** [comment]
I see, I didn't think to update foundry and was just updating the module itself. Thank you!
