### ISSUE TITLE
[Feature Request] Rotation math/handlebars.

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#480]
Seen a couple people wanting randomized rotations (with the rotation animation that alter doesn't have). Could this action get updated to accept math such as ```- [[(1d38)*10]]``` or handlebar notation?

Currently trying it results in this error.

![image](https://user-images.githubusercontent.com/99844555/235391603-15607b51-bdb0-4d95-be2f-d2813229bb4b.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
