### ISSUE TITLE
[BUG] Teleport Oddness

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#481]
1. Teleport is occasionally is off-grid even with snap-to-grid on.
2. Near the end of the video, the teleport seems to teleport the token down slightly, then move it across the rest of the scene to the destination.
3. Occasionally the token gets stuck instead of teleporting. This is apparently local, as the GM sees it stuck and the player sees it teleport.
Screenshot showing a comparison of what we were seeing for number 3.

![image](https://user-images.githubusercontent.com/99844555/235813545-fe5c027d-10b0-49b8-a697-5657b6f77e15.png)

https://user-images.githubusercontent.com/99844555/235813247-d2b1e55d-80ca-4644-b4bd-45846119788f.mp4

I was able to replicate the issues in my world (didn't run FTC here, as the user already had done it in their world)

https://user-images.githubusercontent.com/99844555/235814382-a3d28219-db74-4cd2-ad1a-d0b2829d3417.mp4

There's a copy of the scene JSON just in case. 

[fvtt-Scene-the-endless-stair.zip](https://github.com/ironmonk88/monks-active-tiles/files/11378599/fvtt-Scene-the-endless-stair.zip)

FTC
MATT 10.15
Foundry 10.291
D&D 5e 2.1.5

**Comment by Crowguard** [comment]
Update; running into issue 2 in my world. It always seems to happen when entering the tile diagonally from the bottom right. None of the other diagonals seem to have this problem.


https://user-images.githubusercontent.com/99844555/236002117-6004379e-0a9b-41be-81d7-5a0660aa2d1e.mp4

**Comment by ironmonk88** [comment]
This has possibly been fixed?

**Comment by Crowguard** [comment]
I think this one's fixed also. Not sure if I should close this one due to the weirdness with it. Might want to double-check after the next update.

**Comment by Crowguard** [comment]
No longer seems to be an issue on 12.01.


https://github.com/ironmonk88/monks-active-tiles/assets/99844555/d0e8a5f0-e976-432c-abed-575edecc79b5
