### ISSUE TITLE
[BUG] Teleport Error

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#482]
User is reporting that teleport actions randomly stopped working at all after having been on 10.15 for a while; attempts results in this error. I can't replicate in my world, but I did log in to theirs and confirm it.

User can recreate the problem in a fresh world with just MATT active.

https://user-images.githubusercontent.com/99844555/236114440-261cd828-9b3a-46b7-8d2e-4ff68c8ab85e.mp4

![image](https://user-images.githubusercontent.com/99844555/236114385-8c9382d7-eab3-42e8-ba8a-8ffd66b4a200.png)

MATT 10.15
Foundry 10.291
D&D 5e 2.1.5
FTC

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
