### ISSUE TITLE
[BUG] Write to Journal

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#483]
I was able to figure out the one problem with Write to Journal from a few weeks ago. It won't create a new page unless there's already at least one page in the journal.

https://user-images.githubusercontent.com/99844555/236361131-4b12b4d8-6ae8-4f3f-ac36-501c23004f9f.mp4

MATT 10.15
Foundry 10.291

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
