### ISSUE TITLE
Feature Request: Visibility Filter

### ISSUE THREAD

**Issue by Nysterian** [ironmonk88/monks-active-tiles#485]
One of my players really likes to click randomly on the map while idle, and this causes many of my "on-click" triggers to trigger for that player much earlier than they should. I've tried limiting that by having a distance filter, but that still enables them to trigger it if they're on the other side of a wall and within range.

My current solution to this is to have all those triggers disabled until a door that leads into the room in question is opened, but that requires a lot of setup from my part every time that I want to do something cool like that.

So, I would love if there was a filter, much like the "Filter tokens by distance" one that said "Filter tokens by visibility", that let me filter out tokens that cannot see the triggering tile, by using foundry's vision mechanics.

It could even use a different target for what needs to be visible, allowing for there to be traps that only work if the token can see a certain enemy for example.

**Comment by ironmonk88** [comment]
Added to the latest release.
