### ISSUE TITLE
[BUG] Tiles Being Counted as Current Tokens

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#488]
When running Check Entity Count with Tagger, tiles seem to be getting added to the token collection.

The Chat Messages (Current Tokens) here run a number of times equal to how many tiles were counted.

https://user-images.githubusercontent.com/99844555/236690908-8f986cef-d53e-4a9d-8a5f-f51adac1f6f5.mp4

[fvtt-Scene-488.zip](https://github.com/ironmonk88/monks-active-tiles/files/11415551/fvtt-Scene-488.zip)

MATT 10.15

**Comment by Crowguard** [comment]
Better video showing it happening with `Move` instead.
https://user-images.githubusercontent.com/99844555/236736457-c14523aa-0aeb-4b86-aefd-1b7e2de075da.mp4

**Comment by ironmonk88** [comment]
Fixed in the latest release.
