### ISSUE TITLE
[BUG] FX Master 

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#489]
Displays this error when adding or opening a tile with this action.

![image](https://user-images.githubusercontent.com/99844555/236737005-b1629f60-231b-4ee1-9cef-78655fedaf3c.png)

Also displays the full path in the action list now; I believe it used to be shortened?

![image](https://user-images.githubusercontent.com/99844555/236736853-4c04fe6e-cc6c-4035-971f-f4fa12589ce5.png)

MATT 10.15
FX Master 3.6.0

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
