### ISSUE TITLE
Move Trigger Improper Functionality

### ISSUE THREAD

**Issue by Amd321** [ironmonk88/monks-active-tiles#49]
I've been trying to use some tiles to 'on activate' move certain other tiles and tokens to certain map positions. I'm having the weird functionality of the tokens and tiles to be moved either not moving to their correct place, or not moving at all. This seems to happen when I move more than a certain amount of tokens and tiles at once. I've tried deleting the tokens or tiles and starting over several times, but this keeps happening. I'm not receiving any warnings or errors in my console log, and I've tried doing this with all other modules deactivated, but still get the same results.

**Comment by ironmonk88** [comment]
Is this still an issue?

**Comment by ironmonk88** [comment]
Closing this as there's been no response to the question and there's been a bunch of changes regarding movement.
