### ISSUE TITLE
[BUG] Convenient Effects Don’t Populate Correctly

### ISSUE THREAD

**Issue by DatManRandom** [ironmonk88/monks-active-tiles#490]
If the "DFreds Convenient Effects" mod is installed a number of new actions will be added, of them the "Filter by convenient effect" action type has a drop down list field called "Effects", this field is empty, even though the "Effect" field in the "Convenient Effect" action type is populated correctly.

1. Have DFreds Convenient Effects installed and activated
2. Create a tile and add an action
3. Select the "Filter by convenient effect" action type
4. Find the "Effects" drop down list empty

I expect the list to work like the "Convenient Effect" action type with all the convenient effects listed to pick from, or to work similarly to the "When" field in the tile's Setup page where you can select multiple list items

<img width="549" alt="image" src="https://user-images.githubusercontent.com/52916544/235370864-91d89573-0747-48df-8047-6abad23ace9a.png">

 - Browser: **Google Chrome**
 - Foundry Version: **v10**
 - System: **DnD 5e v2.1.5**
 - Module version: **v10.15**
 - Are there any errors in the console: **None**
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: **No**

A similar issue has been previously reported before, but the released fix only partially solved the issue for me.
It is possible that I am facing this issue because I use Foundry running on MacOS.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
