### ISSUE TITLE
Add "Show Tooltip" Action

### ISSUE THREAD

**Issue by theredspoon** [ironmonk88/monks-active-tiles#491]
**Is your feature request related to a problem? Please describe.**
I have a map with hardcoded names and locations. I want to be see, or have my players see, details of that location when they hover over it. Currently I have this need partially met with map notes + Pin Cushion module, but I cannot set up tiles to behave this way.

**Describe the solution you'd like**
Create an action "Show tooltip" which can display journal entries as a tooltip on hoveron and then disappear on hoveroff. There should be a way to modify text wrapping otherwise the tooltip can extend too far.

**Additional context**
See screenshot of what it can look like with map note + Pin Cushion module.
<img width="409" alt="Screen Shot 2023-05-12 at 4 57 12 PM" src="https://github.com/ironmonk88/monks-active-tiles/assets/20975696/fb324730-ac8c-48a6-80bd-c37812f8fef1">

**Comment by ironmonk88** [comment]
Due to code limitations I can't add tooltips, but I have added the `Close Dialog` action.
This way you can set up a custom Dialog that opens on hoverin and closes on hoverout, effectively creating a tooltip.
