### ISSUE TITLE
[BUG] Activate/Deactivate, Current Collection

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#494]
Does not seem to be deactivating anything. Also, it only displays `Current Tiles`, and does not have a dropdown to select the collection type. No errors. 

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/aa1c9524-af49-4f89-abb0-6874fd732364

10.16

**Comment by ironmonk88** [comment]
Fixed, but... this isn't going to have quite the results you'd think.
It doesn't wait for the move to complete before deactivating the light.
... Although I also realize this is just for testing.  But in case anyone looks this up.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
