### ISSUE TITLE
[BUG] Show Landing Highlight

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#497]
Two line actions take on the color of the last landing in the tile and aren't displaying the number of lines properly.

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/e3bc5418-47b7-42d1-8f31-3d7285d2e00a)

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/932350af-711d-469a-9f77-21cce7e089ca)

MATT 10.16

**Comment by ironmonk88** [comment]
Fixed in the latest release.
