### ISSUE TITLE
Error: You must provide an _id for every object in the update data Array

### ISSUE THREAD

**Issue by jocolamarco** [ironmonk88/monks-active-tiles#5]
**FVTT version:** 0.8.7
**Module version:** 1.0.9 (latest)

Error when setting up sound file to play:

_Uncaught (in promise) Error: You must provide an _id for every object in the update data Array._

![image](https://user-images.githubusercontent.com/45291719/123078363-ce441400-d412-11eb-8b8d-9a1b6d626410.png)

Steps:
1 - Draw tile in screen
2 - Open settings, navigate to Triggers
3 - Click "active"
4 - Add "play Sound" and select file.
5 - Click Update
6 - Sound trigger not shown and error message logged

**Comment by ironmonk88** [comment]
Should be fixed... but I had to change how the actions are saved.
Prior to this, they saved when you closed the action dialog, but that had the unintended consequence of refreshing the Tile and losing any unsaved data.
And this error comes up if the Tile is brand new and hasn't been saved yet.  The action has nothing to save on to.
So the Action Config just edits the actions, but you'll have to save the Tile to save the Actions.

**Comment by ironmonk88** [comment]
Latest release should fix this issue
