### ISSUE TITLE
[BUG] Update 10.16 breaks showing/hiding lights

### ISSUE THREAD

**Issue by maplealmond** [ironmonk88/monks-active-tiles#500]
**Describe the bug**
In version 10.16 turning a light on by using hidden = false fails with a console error.

Using values of 0 and 1 always results in it being hidden so this is not a workaround.

**To Reproduce**
Create a tile which has the following behavior on trigger
* Alter 
* Entity is an Ambient Light
* Attribute is hidden
* Value is false

**Expected behavior**
Light should appear and not error on the console

**Please complete as much of the following information as possible:**
 - Browser: Chrome
 - Foundry Version: v10
 - System: PF2e
 - Module version: 10.16
 - Are there any errors in the console -> "monks-active-tiles |  ReferenceError: prop is not defined"
 - Problem exists with MATT as the only module

**Comment by maplealmond** [comment]
Confirming this works again in 10.17.  Thank you very much.

**Comment by maplealmond** [comment]
Edit:  I may have spoken too soon.  Passing in "false" or "0" appears to toggle the value instead of being interpreted as unhidden.

This is fine for a light switch, but not for some more complex macros.

**Comment by ironmonk88** [comment]
It's sort of fixed.
true/false is going to have to be a special case. To get this to work with the next release, you'll have to put an "=" in front.

**Comment by maplealmond** [comment]
This is sufficient for me.  I've also found a workaround in many (though not all) cases that I can use the new toggle light option.  Thank you!

**Comment by ironmonk88** [comment]
Added to the latest release.
