### ISSUE TITLE
[BUG] Alter Texture.Tint functionality no longer recognizing valid color strings

### ISSUE THREAD

**Issue by EarlyWhirly** [ironmonk88/monks-active-tiles#501]
**Describe the bug**
Color strings that functioned in previous versions of module(~10.15) are no longer considered valid color strings in Alter triggers in recent versions.

**To Reproduce**
1. Set Alter trigger value to texture.tint
2. Testing trigger creates error.

**Expected behavior**

**Screenshots**
![Foundry_Virtual_Tabletop_fwfv5zGM5Y](https://github.com/ironmonk88/monks-active-tiles/assets/117322663/996b29a1-e384-4700-965e-99695b104ebb)
![Foundry_Virtual_Tabletop_dF6dpVaqRl](https://github.com/ironmonk88/monks-active-tiles/assets/117322663/c3e34796-8e9f-4011-8b64-83f1aaa3e5c5)
![Foundry_Virtual_Tabletop_RVvA2zsD44](https://github.com/ironmonk88/monks-active-tiles/assets/117322663/f4e78d08-205f-4d71-8586-537cbf4f0e77)

**Please complete as much of the following information as possible:**
 - Browser [e.g. chrome]
 - Foundry Version [e.g. v10.291]
 - System [Tested in both D&D5e & Pathfinder 2e]
 - Error in 10.16 and 10.17
 - Are there any errors in the console [e.g. press F12 and look for red text] - Yes
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. Yes

**Comment by ironmonk88** [comment]
Due to some changes that allow you to do more with the field, this should be wrapped in quotes.
Technically, it always should have been wrapped in quotes, but the code bypassed the error when it probably shouldn't have.
I'll see if I can make it a little more flexible... but the simple fix right now is to use quotes.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
