### ISSUE TITLE
[BUG] Attack, Multiple Targets

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#502]
The attack action seems to only be targeting the newest created token when multiple targets exist.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/3f20da89-2ae9-4793-9772-30701d80e201

MATT 10.18
FTC, left MIDI on to speed up testing.

**Comment by ironmonk88** [comment]
I think this may have been fixed?

**Comment by Crowguard** [comment]
Seems to be fixed.
