### ISSUE TITLE
Drag an drop clickable scene 

### ISSUE THREAD

**Issue by Kikimor-rec** [ironmonk88/monks-active-tiles#505]
Hi Monk. Thank you for this super module.
Please tell me if it is possible to make it possible to pull scenes on the map and they immediately turn into a clickable timeline translating to the scene? To make it easier to make interactive maps for big adventures.
About the same as it is done with items when dragging them onto the scene.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
