### ISSUE TITLE
[BUG] Getting an undefined error when trying to activate a custom Show Dialog tile as a player

### ISSUE THREAD

**Issue by Dantedevilhunter** [ironmonk88/monks-active-tiles#506]
When attempting to activate a tile with the Show Dialog action set to Custom (Alert and Confirm work with no issues) nothing happens and the console displays the following error:

![image](https://github.com/ironmonk88/monks-active-tiles/assets/22540270/d66214b3-07b9-49cf-ac14-fa7479b02b46)

**To Reproduce**
1. Create a tile triggerable by players
2. Create a Show Dialog action
3. Set the Dialog Type to Custom
4. Attempt to trigger the tile by a player

**Expected behavior**
A dialog is supposed to show up, but players get a console error instead. I want to note that this works for the GM with no issues.

**Please complete as much of the following information as possible:**
 - Browser: Chrome Version 113.0.5672.126 (Official Build) (64-bit)
 - Foundry: Version v10 Stable - Patch 6 (Build 291)
 - System: D&D5e
 - Module version: 10.18
 - Are there any errors in the console - Yes, provided above
 - UPDATE*: This issue happens with MATT as the only active module

**Comment by ironmonk88** [comment]
Fixed in the latest release.
