### ISSUE TITLE
[BUG] Move to wrong coordinates

### ISSUE THREAD

**Issue by Stadhouder** [ironmonk88/monks-active-tiles#507]
**Describe the bug**
Using the Move command in version 10.18 causes tiles to move to a different location than intended. Choosing another tool from the ribbon causes the tiles to snap to the correct place. This happens on all maps, regardless of if Snap to Grid is on or not. The console shows no errors.

**Screenshots**
https://github.com/ironmonk88/monks-active-tiles/assets/133886052/898ab40b-9d45-4c29-bc1f-e751630c058d

**Comment by Vralek** [comment]
This happens in 10.20 as well

**Comment by Stadhouder** [comment]
> This happens in 10.20 as well

**Comment by Stadhouder** [comment]
> This happens in 10.20 as well

My workaround has been to use tokens instead. It's not ideal, but they don't have this issue.
Also, apologies for closing and reopening; I misclicked,

**Comment by ironmonk88** [comment]
Fixed in the latest release.
