### ISSUE TITLE
[BUG] Show Image, Caption

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#509]
Players are unable to see the caption at the top of the top of the window.

Top is player side, bottom is GM side.

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/8e82b57d-33c3-48c7-aa8c-93e2cad30e1e)

MATT 10.18

**Comment by ironmonk88** [comment]
Fixed in the latest release.
