### ISSUE TITLE
[BUG]/[Feature Request] Open Unlinked PF2 Loot Tokens

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#510]
When using `Open Actor Sheet` directly targeting a token, it is unable to open the loot sheet for one of PF2's Loot type NPCs if the token is not linked to the actor; a player is still able to open the unlinked token's inventory when double-clicking it, despite not having access to the actor in the directory.

I'm not entirely sure if this counts as a bug or a feature request to improve PF2 usage.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/dd616274-280d-49cc-b3fa-ac00443e33de

MATT 10.18
PF2 4.11.2

**Comment by ironmonk88** [comment]
This may have been a PF2E issue, or it's been fixed in the latest version.

**Comment by Crowguard** [comment]
Seems to be working on 11.02/PF 5.3.1.
