### ISSUE TITLE
[BUG] Attack action not work with MIDI

### ISSUE THREAD

**Issue by rinnocenti** [ironmonk88/monks-active-tiles#512]
**Describe the bug**
The attack action is not processed by the midi, a weapon or magic attack is not passed through the MIDI.
Not only does it not pass through MIDI, it doesn't address the item's active effects.

**To Reproduce**
![image](https://github.com/ironmonk88/monks-active-tiles/assets/3178127/b74bfff7-85c6-41ac-bef7-a055b4078a0f)
tile configuration

![image](https://github.com/ironmonk88/monks-active-tiles/assets/3178127/cbec4346-b4b7-40d5-80b6-d2921c1c6316)
spell configuration

![image](https://github.com/ironmonk88/monks-active-tiles/assets/3178127/b8f07631-6368-40f9-b463-45b63d32b501)
The attack with spell is done, but it does not go through the MIDI forcing you to click on the button in the chat. 

![image](https://github.com/ironmonk88/monks-active-tiles/assets/3178127/db7adf70-22bb-47a5-bedc-24d14c8f6f56)
but even clicking the button, it doesn't process the item that should apply the active effect.

![image](https://github.com/ironmonk88/monks-active-tiles/assets/3178127/c442e33a-a583-44dc-81fc-625bb368a2e5)

![image](https://github.com/ironmonk88/monks-active-tiles/assets/3178127/55960f2b-95a8-4d3b-be30-d756e14a1694)
Even though an item with an attack is made, it still doesn't go through the MIDI, it doesn't apply the effect and it also doesn't do the attack because it doesn't test the target's AC (nor does it place a target)

**Expected behavior**
when making the attack, the action should invoke the MIDI process to resolve it.
Even though the intention was not to go through MIDI (which I think is a mistake if that's the case, since both are automation modules) the effect and settings of the active effect should be applied.

**Please complete as much of the following information as possible:**
 - Foundry Version [v10.291]
 - System [D&D5e]
 - Module version 10.19

**Comment by rinnocenti** [comment]
by the way
in version 10.18 it was working, as I understand it should.

**Comment by jjarekf** [comment]
Hi,
I was trying to set up traps and encountered the same problem. 

Foundry v10.291.
MATT Module version 10.20
MiDI QOL Module version 10.0.44

**Comment by ironmonk88** [comment]
Fixed in the latest release.
