### ISSUE TITLE
[BUG] Chat Message, No Chat Bubbles for Everyone

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#514]
Chat Bubbles are not displaying on tokens when `Everyone` is selected. Works as expected for `GM Only` and `Token Owner`.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/4f4ce18d-09e0-4154-b23f-5561cfc40c2f

MATT 10.20

**Comment by ironmonk88** [comment]
Fixed in the latest release.
