### ISSUE TITLE
Foundry 11

### ISSUE THREAD

**Issue by Stramp** [ironmonk88/monks-active-tiles#521]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by weepingminotaur** [comment]
Please do not leave v11 compatibility requests as github tickets. Monk is working hard on updating his modules for v11 and any updates will be posted on his Discord server.

**Comment by ironmonk88** [comment]
There isn't enough information here to make this a valid issue or enhancement.
I'll leave this open for a couple hours if you're on v11 and want to change it to a bug report with examples, otherwise it's just a placeholder for something that's going to happen anyways.
