### ISSUE TITLE
Foundry 11 update timeline? [BUG] Brief description of your issue

### ISSUE THREAD

**Issue by Theopholis** [ironmonk88/monks-active-tiles#524]
Any update on timeline to update your modules for Foundry11

**Comment by Crowguard** [comment]
@Theopholis V11 will happen when it happens; this ticket is not helpful and is going to end up closed like the last one #521 .

**Comment by Theopholis** [comment]
Thank you for all you are doing. I apologize for not seeing the post regarding ticket #521. Several other developers have their modules ready, but have not posted them. When I contacted them, they sent me a link to download the .zip file. They were still in debug mode and I have helped work through them. Please remove my comment. I'll look to the discord channel.
