### ISSUE TITLE
Foundry VTT Version 11 Update

### ISSUE THREAD

**Issue by Brethraeus88** [ironmonk88/monks-active-tiles#528]
Update Version 11 Dropped last week, and it seems the Monk's Active Tile Trigger along with a few other Monk's modules (Enhanced Journals and through Enhanced Journals, the store) do not work in the latest Version of the software. Is there a plan to implement an update so that DM's can continue to use these modules in Update Version 11, or will we just not be able to use them any longer as they will break some of the meta in the majority of the games most DM's are using it with. Active tile trigger more specifically.

**Comment by Crowguard** [comment]
@Brethraeus88 See #521 & #524.

**Comment by weepingminotaur** [comment]
Module developers work for free, on their own time. Monk will eventually update his modules to be v11 compliant. There is zero need to file github tickets for v11 compatibility.
