### ISSUE TITLE
V11 support

### ISSUE THREAD

**Issue by pkonshik** [ironmonk88/monks-active-tiles#529]
Hello, could you please take a look onto these errors on FVTT V11 for 3 modules

- Enhanced Journal
- Scene Navigation
- Enhanced terrain level

![image](https://github.com/ironmonk88/monks-active-tiles/assets/52590783/47615098-cdcf-4398-87c2-50129519df96)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/52590783/ee397d33-94bd-43d8-85de-74ec860b1cfb)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/52590783/f64471ab-31aa-4b5a-af11-6b1172a536b8)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/52590783/ab43cef3-1ff4-45bf-bdcf-c46db41394ea)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/52590783/96e86446-2345-441b-b2ed-a65e9c9f507a)
---
Additionally token bar do not show tokens/actors icons
![image](https://github.com/ironmonk88/monks-active-tiles/assets/52590783/350f616d-04d3-434f-9a75-ea8517131078)

**Comment by ironmonk88** [comment]
None of these issues are related to Active Tiles.
Please don't combine multiple tickets for different modules in one place.  Open a ticket with each module.
