### ISSUE TITLE
[BUG] Keypad Tile

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#531]
So I've imported the keypad template; it isn't jumping to `_failedlanding` when the wrong code is entered. Not sure if the problem is with failed landing or the HTML. 

Also, there's an error that pops up when triggering the tile; might be part of the problem?

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/29f3ce96-10a6-4c7f-9790-22f789bda485

MATT 10.21

**Comment by ironmonk88** [comment]
I've clarified the code with examples.
It's using both landings for the submit and code to check while the dialog is active, so there's examples in place if you want to use javascript, or if you want to use landings.

I did fix the issue with the error though.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
