### ISSUE TITLE
[BUG] The module clashes with Levels and removes the Levels tab on all tiles.

### ISSUE THREAD

**Issue by TheXeno30** [ironmonk88/monks-active-tiles#533]
**Describe the bug**
The module clashes with Levels and removes the Levels tab on all tiles.

**To Reproduce**
open any tiles.

**Expected behavior**
in the Levels tab there should be setting to adjust sight and hight

**Screenshots**
![image](https://github.com/ironmonk88/monks-active-tiles/assets/135822719/7cb27c59-9030-4500-8a1f-33730d400555)

**Please complete as much of the following information as possible:**
 - Browser Chrome
 - Foundry Version 10.291
 - System Cyberpunk RED - CORE v0.86.1
 - module version 10.21
 - ![image](https://github.com/ironmonk88/monks-active-tiles/assets/135822719/d0462d64-35f1-424f-acba-d57fc87e8036)
 - Yes used it to find that active tiles and Levels clash

**Additional context**

**Comment by ironmonk88** [comment]
That's an issue with Levels.
There's nothing I can do with MATT to fix it.
A ticket has been opened with that module.

**Comment by TheXeno30** [comment]
ok - thanks for taking the time and thanks for a very very awesome module. Its like wizardry :)

**Comment by TheXeno30** [comment]
just posted an issue with Levels and he reposnded with MATT having a problem that he fixed but only for v11. Its a bit above my paygrade, since in not a programmer, so i dont know how this works, but maybe a solution can be reach between you, for all us v10 users (I can't be the only one running v10 still and using both your awesome modules.).
Thanks again for the time.

**Comment by onekinddonut** [comment]
I just ran into the problem just now with 10.21, I ended installing the module version 10.20 as a temporary fix. It seems to show the levels tab now at least

**Comment by theripper93** [comment]
Funnly enough, this worked fine until MATT 10.21 because the module added tabs incorrectly (maybe intentionally?) lol. So the issues canceled out, unfortunatelly this fix will be only in V11 Levels as i moved away from V10 updates for quite a while now. Downgrade MATT to 10.20 if you are on V10

**Comment by ironmonk88** [comment]
Closing this as the code has moved on to v11.
