### ISSUE TITLE
[BUG] JS conflict with libWrapper

### ISSUE THREAD

**Issue by Axblade** [ironmonk88/monks-active-tiles#535]
**Describe the bug**
Monk Active Tiles stops working once libWrapper module is active

**To Reproduce**
Install V 11 +
Install Monk Active Tiles Module
Install libWrapper

**Expected behavior**
no JS conflict.

**Please complete as much of the following information as possible:**
 - Foundry Version [11+]
 - System [ D&D5e]
 - Module version: 10.21
 - Are there any errors in the console: foundry.js:67434 Monk's Active Tile Triggers: Error detected in module. It is likely this module has not been updated for FVTT Version 11 Stable. (See JS Console)
fetch @ foundry.js:67434

**Comment by WizardForHire123** [comment]
Active tiles is not v11 ready.
