### ISSUE TITLE
[Feature Request] Chat Message & Roll Mode Options

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#538]
Now that all value fields accept dice notation, could they could be expanded to include the chat message & roll mode options that Alter & Hurt/Heal have?
![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/62cec879-a0a9-4604-bf9b-952b8c7b7fed)

**Comment by ironmonk88** [comment]
The extra fields are there with a purpose... the other actions don't technically need them.
But... you can do the exact same thing with the dice notation. `[[/publicroll 1d4]]{label}`.
So the functionality already exists, but the fields don't.

**Comment by Crowguard** [comment]
Noted; thanks.
