### ISSUE TITLE
FEATURE REQUEST: Create macros to apply presets, copy and paste

### ISSUE THREAD

**Issue by baileywick** [ironmonk88/monks-active-tiles#54]
I would like macros in my hotbar that could:

1. Apply a preset. This would imply a way of generating that macro from the tile config screen. This would help me quickly apply often-used functionality to a tile: traps, teleport, teleport+elevation, stop/pause gameplay w/ chat message, etc

2. Copy the configuration of a selected tile.

3. Paste the configuration of the copied tile onto a new selected tile

**Comment by ironmonk88** [comment]
Closing this as Active Tiles now has the Tile Template browser and no longer uses Macros.
