### ISSUE TITLE
[BUG] V11 - token conditions use label instead of name leading to incomplete list

### ISSUE THREAD

**Issue by BrutalBirdie** [ironmonk88/monks-active-tiles#540]
**Describe the bug**

List of Effects only partially filled.

**To Reproduce**
1. Try to add an Active Effect trigger action

**Expected behavior**
Should display a full list of effects.

**Screenshots**
![image](https://github.com/ironmonk88/monks-active-tiles/assets/20840012/db8f632b-2c36-4c7a-8cda-29ef4c75052f)

**Please complete as much of the following information as possible:**
 - Browser Version Google Chrome 114.0.5735.134 (Official Build) (64-bit) and Firefox 114.0.1 64-bit
 - Foundry Version v11.302
 - System [dsa5-foundryVTT](https://github.com/Plushtoast/dsa5-foundryVTT)
 - Module [5.0.5](https://github.com/Plushtoast/dsa5-foundryVTT/releases/tag/5.0.5)

---

Proposed solution:

After some debugging, testing and reading.
https://github.com/Plushtoast/dsa5-foundryVTT/blob/37a27b670544632076639fa97d711e394387e061/modules/system/config-dsa5.js#L3

```
//TODO label should not be required anymore, but foundry11 bug?
```

I identified: https://github.com/ironmonk88/monks-active-tiles/blob/8bf0750996d32d7012c7822c06791a296021841f/actions.js#L3030-L3032

When changing this the references `.label` to `.name` it looks like this:

![image](https://github.com/ironmonk88/monks-active-tiles/assets/20840012/523716d5-36ae-4a04-9c49-1244d4595b42)

But I am unsure what the right path here is right now since - [11.302 - patch notes](https://foundryvtt.com/releases/11.302)
> Status effect toggles now use the label attribute instead of the name attribute as expected. [(9618)](https://github.com/foundryvtt/foundryvtt/issues/9618)

I just started working with VTT and everything, but I hope my findings helps you update this awesome module :)

**Comment by ironmonk88** [comment]
Fixed in the latest release.
