### ISSUE TITLE
[BUG] V11 clicking a tile using _click to change to inacative scene from active and back not working.

### ISSUE THREAD

**Issue by Rubengam3r** [ironmonk88/monks-active-tiles#541]
**Describe the bug**
I have a landing page that is using a menu system using MATT. I have titles that when clicked go to another scene but I do not set it to active.  In the tile set up I am using the chat command for _click to change scence but not make it active so that my other players only see the scene and not everyone else. When I navigate back to the active tile using another tile to go back the tile is then not clickable.

**To Reproduce**
1. create a landing page with a travel party scene
2. set the landing page to be active and using MATT change scene to the travel party scene but don't check the active box
3. on the travel party have a MATT title to change the scene back to the landing page but don't check the active box
4. from the landing page which should be still active try step 2 agin. In my case the scene doesn't change.

**Expected behavior**
It should change the scene for the player and not make the scene active. Then they should be able to navigate back when needed.

**Screenshots**
step 2
![Screenshot 2023-06-22 224959](https://github.com/ironmonk88/monks-active-tiles/assets/32652791/1936d490-4d5d-457a-8bd8-c37ea8b77a0d)
![Screenshot 2023-06-22 225051](https://github.com/ironmonk88/monks-active-tiles/assets/32652791/f31af599-1d88-4fe7-8b61-9773f1c7b781)
![Screenshot 2023-06-22 225114](https://github.com/ironmonk88/monks-active-tiles/assets/32652791/a5e6e143-e00a-4489-b0cf-0d0f4ed7cbc2)
![Screenshot 2023-06-22 225144](https://github.com/ironmonk88/monks-active-tiles/assets/32652791/ffdd7f01-8889-48e6-9800-7df0179ad9db)

**Please complete as much of the following information as possible:**
 - Foundry Version [V11 302]
 - System [ D&D5,]
 - Module version 11.01
 - Are there any errors in the console [e.g. press F12 and look for red text]
 -  I only saw one about a hook for canvas ready but it may have been for another module. Not sure.
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.

**Additional context**

**Comment by Crowguard** [comment]
Please run FTC, your report fails to mention whether you actually ran it, and Change Scene is working fine here.

**Comment by Rubengam3r** [comment]
I will try it out and see. If it does work I will close out the ticket.

**Comment by Crowguard** [comment]
Is the scene you're trying to change to the currently active scene?

**Comment by Rubengam3r** [comment]
I am going from the currently active to another scene which should not be active. Then from that scene I am going back to the active one.

**Comment by Rubengam3r** [comment]
So even with just MATT as the only active module the problem continues.

**Comment by Rubengam3r** [comment]
Interesting. I found that in the console I have to wait for the contolsLayer canvas layer to be drawn untill the MATT tile is even registered.

**Comment by Crowguard** [comment]
Are you using Firefox with AdBlocker Ultimate by chance? Just had another user report that its interfering with MATT.

**Comment by Rubengam3r** [comment]
nope I am using chrome.

**Comment by Crowguard** [comment]
so, I found the problem, but its with the click trigger, not the Change Scene action. Seems there's some kind of "cooldown" for lack of better term, and if its clicked too soon before that, it can temporarily lock up click triggers.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/81fb268e-7788-48ca-b50b-2350110f6425

**Comment by Rubengam3r** [comment]
Gotcha… which is what I was seeing with the wait of the canvas being drawn. So looks to be a foundry thing then. As I don’t think there is much monk can do with this. Unless he puts a hook to wait for everything to be ready. As when it occurs I find that I have to refresh the screen to get it fixed

**Comment by Rubengam3r** [comment]
I can report that this has been fixed in 11.02 release. Thanks Monk
