### ISSUE TITLE
[Feature Request] Right-Click Option to Insert Action

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#543]
Would be an amazing addition when trying to modify extremely long tiles sequences.

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/6848e0c4-5ee3-448d-a254-9827944c0e59)

**Comment by WizardForHire123** [comment]
Oooh I like this

**Comment by Crowguard** [comment]
Closing as it has been fixed.
