### ISSUE TITLE
[BUG] The tiles work once and then stop functioning

### ISSUE THREAD

**Issue by gaaaork** [ironmonk88/monks-active-tiles#544]
**Describe the bug**
MATT 

**To Reproduce**
Blank world, only MATT activated.
Scene A, B, C.
Configuration:
A tile to B and tile to C.
B to A and to C.
C to A and to B.
![Capture d’écran 2023-06-26 à 14 04 47](https://github.com/ironmonk88/monks-active-tiles/assets/4005033/95a93ee0-e1a7-4934-90f6-916244e598eb)
![Capture d’écran 2023-06-26 à 14 04 58](https://github.com/ironmonk88/monks-active-tiles/assets/4005033/8619b55d-eb73-4b40-80e3-f50c55fea161)
![Capture d’écran 2023-06-26 à 14 05 05](https://github.com/ironmonk88/monks-active-tiles/assets/4005033/250e8d16-824d-4b51-b8a6-f2498ccb7261)
![Capture d’écran 2023-06-26 à 14 05 16](https://github.com/ironmonk88/monks-active-tiles/assets/4005033/aa410a24-531a-4223-bc74-9332b73f068f)
![Capture d’écran 2023-06-26 à 14 05 20](https://github.com/ironmonk88/monks-active-tiles/assets/4005033/17e022c5-9cbf-438a-ad39-7e737568c6cb)
![Capture d’écran 2023-06-26 à 14 05 28](https://github.com/ironmonk88/monks-active-tiles/assets/4005033/3bbd05e9-55bc-4824-a595-396697883cbe)
![Capture d’écran 2023-06-26 à 14 05 33](https://github.com/ironmonk88/monks-active-tiles/assets/4005033/d3204f93-aa3a-4909-977d-05c641d55051)

It works initially, but as soon as we try to return to a previously seen tile, it gets stuck.
We click on the tile button (toolbar on the left) and go back to the selection. It works again."

Browser: Chrome Version 114.0.5735.133
Foundry Version: V11
System: Reve de dragon, aria, D&D, ...
Module version: 11.01
Are there any errors in the console? [e.g. press F12 and look for red text]
Have you tried using "Find the Culprit" to check if it's a module interaction? Yes, no other modules activated, I deactivated everything and created a blank world, and I still have the issue.
Additional context:
When clicking on a tile to return to a previously viewed scene, nothing happens at all. If I click on the tile button in the left toolbar, it seems to reset because then I can click on the tile and it works correctly... once. Prior to upgrading to V11, everything was functioning properly and I had no issues. The problem appeared during the transition to V11 and module migration.

**Comment by Crowguard** [comment]
Same as #541. Its a problem with the `Click` trigger.

**Comment by LadyJ25** [comment]
Same here, though my issue arises when I have tiles that are supposed to cycle through a number of images. It cycles to the next one and then stops working. If I refresh foundry with F5, it all works again and allows me to cycle one forward again. The console error that pops at the second click is this: 

monks-active-tiles.js:16 monks-active-tiles |  TypeError: Cannot read properties of null (reading 'valid')
    at set texture [as texture] (index.js:126:1)
    at new ye (index.js:126:1)
    at MonksActiveTiles.transitionImage (monks-active-tiles.js:1228:23)
    at async Promise.all (index 0)
    at async TileDocument.runActions (monks-active-tiles.js:3993:56)
    at async TileDocument.trigger (monks-active-tiles.js:3931:36)

The trigger for me as well is click, with the actions "Switch tile image to <next>" for another tile

**Comment by Kronos25** [comment]
Can confirm I have this issue as well as for today (Foundry v304) - 05/07 with all modules on the latest date. Trying to create a landing page (A screen -> B - > C and vice-versa with a return button). There seems to be an internal cooldown or something that prevents from activating a scene after the first interaction.

If you alt+tab however, it seems to reset it.

**Comment by Wokeye27** [comment]
Just encountered this bug on my landing pages using tiles for clicking between scenes.  Same (lack of) response for all types of click (right, double).
Possible workaround: When I click on a token or menu icon it seems to enable triggering via clicking again.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
