### ISSUE TITLE
[BUG] Chat Message Display

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#546]
Chat Message display on this tile is wonky.

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/2ed56e9a-3f0a-4544-b8a5-9fe672a67dbc)

[fvtt-tiledata-broken-chat-message.zip](https://github.com/ironmonk88/monks-active-tiles/files/11912449/fvtt-tiledata-broken-chat-message.zip)

MATT 10.21 & 11.01

**Comment by ironmonk88** [comment]
Technically... you have a badly closed tag in your chat message.  The `<i>` isn't closed properly.
That being said... MATT should compensate for that.

**Comment by Crowguard** [comment]
Closing as it has been fixed.
