### ISSUE TITLE
[BUG] Unable to Parse Macro Returned Data

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#549]
I've got a few macros that are failing to use the returned value from the macros.

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/f0f78f34-7228-404c-a20c-0e1e4f74a8b3)

### Macro 1

```js
return { totalPlayers: game.users.filter(u => u.active).length };
```
![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/eec1b1c6-07d2-47f3-9a62-f966f658f4fe)

### Macro 2

```js
return { combatRound: game.combat.round };
```

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/b2f022f0-44a3-48df-a83c-b218325141bd)

MATT 11.01
FTC
With & without Advanced Macros

**Comment by Crowguard** [comment]
Got this fixed with your Discord suggestion, but I'll leave this for now, since you mentioned MATT needs some new error checking.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
