### ISSUE TITLE
[BUG] Add to Combat Trigger not adding targets from multiple Tags

### ISSUE THREAD

**Issue by jendives2000** [ironmonk88/monks-active-tiles#552]
**Describe the bug**
The Add to Combat trigger does not add Targets from multiple Tags. So I use the Tagger module of course. 
It works if I duplicate the Add to Combat trigger and change the Tag, but this defeats the purpose of using multiple Tags in one trigger. 

![image](https://github.com/ironmonk88/monks-active-tiles/assets/94803007/657f7767-e915-4ff6-9e68-f16b80d6cf64)
I tried writting the 2nd tag with and without a space after the comma. Both don't work.

I installed the following modules: 
Active Modules:
----------
AceEditorVTT v;
Active Token Effects v;
Additional Metric Ruler Labels v;
Advanced Macros v;
Advantage Reminder for dnd5e v;
Allies and Antagonists v;
Always HP v;
Archon (Masked Items) v;
Argon - Combat HUD v;
Automated Animations v;
Auto-Rotate v;
Basic Rules v;
Beaver's Crafting Module v;
Beaver's System Adaption dnd5e v;
Beaver's System Interface v;
Build-a-Bonus v;
Carousel Combat Tracker v;
Chat Commander v;
Chris's Premades v;
ConversationHUD v;
DF Chat Enhancements v;
DFreds Chat Pins v;
DFreds Convenient Effects v;
DFreds Effects Panel v;
DF Settings Clarity v;
Dice Tray v;
dlopen v;
DND5E Scriplets - 5E QOL bits and pieces v;
Dungeon Master's Guide v;
Dynamic effects using Active Effects v;
Effect Macro v;
Elevation Ruler v;
Foundry Community Macros v;
FXMaster v;
Game Audio Bundle 1 v;
Game Audio Bundle 2 v;
Game Audio Bundle 3 v;
Game Audio Bundle 4 v;
GM Screen v;
Health Estimate v;
Hot Pan & Zoom! v;
Illandril's Inventory Sorter (5e) v;
Image Hover v;
Initiative Double Click v;
Innocenti's Loot v;
Invisible tokens can see too v;
Item Delete Check v;
Item Piles v;
Ivan Duch Free Music Collection (Shared Compendiums) v;
JB2A - Patreon Complete Collection v;
Journal Font Scaler v;
Less Fog v;
lib - Color Settings v;
libWrapper v;
Lock View v;
Material Components v;
Midi QOL v;
Monk's Active Tile Triggers v;
Monk's Little Details v;
Monk's Sound Enhancements v;
Monk's TokenBar v;
Monster Manual v;
Mordenkainen Presents: Monsters of the Multiverse v;
Move That for You v;
Music d20 Sampler v;
Narrator Tools v;
Ownership Viewer v;
Player's Handbook v;
Potion Crafting & Gathering v;
Quick Encounters v;
Quick Insert - Search Widget v;
Rolltable Requester v;
Sequencer v;
Sidebar Macros v;
Simbul's Athenaeum v;
Simbul's Cover Calculator v;
Smart Target v;
socketlib v;
Splatter v;
Stealthy v;
Stochastic, Fantastic! - Random Encounter Generator v;
Tactical Grid v;
Tagger v;
Tasha's Cauldron of Everything v;
Tasteful Tooltips v;
Template Macro v;
Tension Pool v;
The Forge v;
The Forge: Compendium Library v;
The Forge: More Awesomeness v;
Tidy UI - Game Settings v;
Times Up v;
Token Attacher v;
Token Magic FX v;
Torch v;
Traps, Trammels, and Triggers v;
VuePort: Let the Light in! v;
Wall Height v;
Warp Gate v;
WTF: What the Flag? v;
Xanathar's Guide to Everything v;

**Please complete as much of the following information as possible:**
 - Chrome Version 114.0.5735.199 (Official Build) (64-bit)
 - Foundry Version V11 build 304
 - System D&D5e 2.2.1
 - MATT 11.01
 - Are there any errors in the console [e.g. press F12 and look for red text]
 This is the Console after I clicked to trigger the actions from the tile
 
![image](https://github.com/ironmonk88/monks-active-tiles/assets/94803007/458eed8e-0eca-430f-9059-e387ad70867c)

 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.
 No, I didnt try.

**Additional context**

**Comment by ironmonk88** [comment]
`Exactly those terms` means the tokens have to have "show-gargoyle" **AND** "player" as they're tags.  And only those tags.
What I think you want is `Any Term`.

**Comment by ironmonk88** [comment]
Closing because it's an old ticket and there's a resolution.
