### ISSUE TITLE
[BUG] Multiple wildcard functionality in tiles not working

### ISSUE THREAD

**Issue by Durango807** [ironmonk88/monks-active-tiles#553]
I encountered a bug that affects the behavior of wildcards in the file paths when using the "Play Sound File" action. This issue prevents foundry from playing the correct sound files when multiple wildcards are used in the same tile.

**To replicate the issue:**

Set up a tile with a dialog that has few landings which play sound files.
Use wildcards in the file path for the sound files, such as "sfx_library/swords/small/shortsword*.mp3"

**Observed behavior:**
After selecting an initial sound option, subsequent selections of different sounds continue to play the initial sound until the page is reloaded. The software does not play the correct sound files based on the current selection.

Further investigation revealed that this issue specifically occurs when wildcards are used in the file path. Instead of playing the appropriate sound file, the software only plays the first wildcard sound for any other wildcard, regardless of the filepath.

I think this issue affects wildcard paths for images as well.

Discord messages link: https://discord.com/channels/862414864692281386/862421211749154816/1126515690208239636

**Comment by Crowguard** [comment]
Just confirming; requires a setup similar to this. Running the Snake landing here will still only play the Cat sound. 
![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/29f8d132-11d6-47eb-a7d9-64ab3cbf4f7d)

MATT 11.01
Foundry 11.304

**Comment by Durango807** [comment]
@Crowguard technically whichever sound it played first (upon loading the page) will continue to be the sound played until the page is reloaded, regardless of dialog selection.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
