### ISSUE TITLE
[BUG] Tiles that configured to be triggered on click should be activated by touching as well

### ISSUE THREAD

**Issue by ZwS** [ironmonk88/monks-active-tiles#557]
**Describe the bug**
Tiles that configured to be triggered on click should be activated by touching as well. 

**To Reproduce**
1. Create new tile with When = 'Click'
2. Login into a game from any device with touch screen (phone/tablet).
3. Touch the tile

**Expected behavior**
On touch tile should be triggered just like it happens on regular click.

**Screenshots**
N/A

**Additional context**
Seems to be a regression, Triggering tiles by touch worked in 10.x branch.

**Comment by ironmonk88** [comment]
Added to the latest release.
