### ISSUE TITLE
[BUG] "Switch Tile Image" transitions deletes image client-side

### ISSUE THREAD

**Issue by GSBicalho** [ironmonk88/monks-active-tiles#558]
**Describe the bug**
When trying to change the image of a token using the Switch Tile Image action, if a transition is set it will cause an error and the target token will disappear

**To Reproduce**
1. Use Tile Controls
2. Create tiles A, B and C with different images
3. On C, go to Triggers > Images and add two images
4. On A, go to Triggers > Actions > Add, set Action to "Switch Tile Image", select C as the target, set "Change To" to 1, set Transition to "Fade". On Setup, set it to trigger on click
5. On B, do the same as A, but set "Change To" to 2
6. Use Token Controls, so you can interact with the tokens
7. Click on B, observe the image fading and changing
8. Click on A, image wont change, error will be output to console
9. Click A again, no error, but no change to image
10. Use Tile Controls, C will disappear
11. Refresh the page and see that C is back

This occurs with other transitions, but not None. This was from a setup I had in v10 which stopped working when I updated to v11.

**Expected behavior**
Tile should simply transition into the new image

**Screenshots**
Console output of steps 7, 8 and 9, with each line corresponding to a click
![image](https://github.com/ironmonk88/monks-active-tiles/assets/5908933/e2545bd1-e880-4f5e-8196-83d0d2331708)

**Please complete as much of the following information as possible:**
 - Chrome, Foundry client
 - Foundry Version v11 305
 - System D&D5e
 - Module version 11.01
 - **Are there any errors in the console?** Yes, in the screenshot above
 - **Have you tried using `Find the Culprit` to make sure it isn't a module interaction?** Ran the steps above with only this module installed

**Comment by Crowguard** [comment]
Transitions have been broken ever since V10 rolled out. Foundry deleted some of the code that was being used for them, and Monk hasn't found a workaround yet.

See

#324 
#336 
#342 
#355 
#544 

Probably others.

**Comment by Bekradan** [comment]
Very strange then as V10 used to work perfectly for me.  It sort of does in V11 as well... First transition works perfectly, second tranisition fails, but if you go to another scene and then back again the next transition works again.

**Comment by ironmonk88** [comment]
I'm unable to replicate it, but from what I can tell in the code, the second image isn't valid for some reason.
I've added error checking to make sure that invalid images are handled gracefully, but it's not going to fix whatever is happening, only show better error messages.

**Comment by Bekradan** [comment]
Hi Monk,  Found the problem my end.  It was Multiface tiles.  The moment I turned it off switch tile image worked perfectly.  I'll add a post in discord in case others come across the same issue.
Thanks for all your hardwork and can't wait to see your next video with BW.

**Comment by ironmonk88** [comment]
Closing this as it was another module causing interference.
