### ISSUE TITLE
[BUG] Passive skills check tile seems to hit twice.

### ISSUE THREAD

**Issue by Rubengam3r** [ironmonk88/monks-active-tiles#559]
**Describe the bug**
I have a tile that filters by attribute for passive perception >= 13 when a player token enters the title the console is showing that the tile hit multiple times. The first looks like it is supposed of continued and then the second time the continue is false.

**To Reproduce**
1. Have tile created with a passive check with enter
2. Have a token with a 15 or higher passive perception

**Expected behavior**
I would think that the first hit of the token that shows true on continue would have revealed the other tile for the door.
**Screenshots**

![tile](https://github.com/ironmonk88/monks-active-tiles/assets/32652791/e29eb425-56c8-4c05-8594-bcd870925aad)
[unknown_2023.07.18-16.49_1.zip](https://github.com/ironmonk88/monks-active-tiles/files/12089503/unknown_2023.07.18-16.49_1.zip)
**Please complete as much of

 the following information as possible:**
 - Browser Chrome
 - Foundry Version 11 Build 305
 - System D&D 5E
 - Module version 11.02
 - Are there any errors in the console [e.g. press F12 and look for red text]
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.  yes
**Additional context**

**Comment by Rubengam3r** [comment]
The zip file is a video clip of the problem

**Comment by Crowguard** [comment]
Your `enter` thread has no way to continue, the ShowUnderDark landing is set to `Stop When Reached`, preventing it from continuing.

**Comment by Rubengam3r** [comment]
I see. That did fix it thanks.
