### ISSUE TITLE
[BUG] Filter by Name

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#560]
Filter by `name` is always returning false. Its not a problem with other strings that I've tested with; `texture.src` & the Tagger flag.

The attribute is still `name` according to the console, so I'm stumped.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/dcbef827-672d-4dc2-b561-1e10caf7af25

MATT 11.02
Foundry 11.305

**Comment by ironmonk88** [comment]
Fixed in the latest release.
