### ISSUE TITLE
[BUG] Show/Hide & Position in List, Current Tiles

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#561]
Displays as `Current Tokens` in the action list.

edit: so does Position in List actually, just noticed it in the screenshot. Its actually `current tiles` in the action configuration.

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/af1dc8d3-8a28-4e24-b716-f4e5cab0c457)

MATT 11.02

**Comment by ironmonk88** [comment]
Fixed in the latest release.
