### ISSUE TITLE
[BUG] Tile with webm as Tile Image plays upon scene change.

### ISSUE THREAD

**Issue by jacksda0240** [ironmonk88/monks-active-tiles#562]
**Describe the bug**
Upon update to Foundry v11, MATT tiles with the tile image set as a webm file partially play the tile animation upon scene change instead of waiting for manual activation as configured.

**To Reproduce**
1. Create MATT tile with webm file as tile image.
2. Change to different scene.
3. Change back to original scene.

**Expected behavior**
That the tile animation not play until triggered in accordance to tile settings.

**Screenshots**

**Please complete as much of the following information as possible:**
 - Browser: checked both on Firefox and Edge
 - Foundry Version v11 Stable Build 305
 - System PF2E v5.1.2
 - Module version v11.02
 - Are there any errors in the console: No errors, but it does show webm asset as loading to a partial percentage (11%-15%) upon scene load.
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: Yes and there is no change.

**Additional context**
I have tried changing the tile image to a static image, saving the tile, and then reverting back to the webm file.  I have also tried creating a brand new tile using a webm file and have the same issue.

**Comment by jacksda0240** [comment]
Upgraded to FVTT v11 Stable Build 306 and problem still exists.

**Comment by ironmonk88** [comment]
It's working as expected for me.
![image](https://github.com/ironmonk88/monks-active-tiles/assets/75920956/da3ab44c-988d-48e2-bbf5-94a03bf8ad32)
You wouldn't happen to have autoplay turned on would you?

**Comment by jacksda0240** [comment]
No, the "Autoplay Video" option isn't selected.

I run into the same problem if I create a brand new world that only has the PF2E setting and Monk's Active Tile Triggers as the only module active.

Here are the tile property options from the basic, brand new world:

![image](https://github.com/ironmonk88/monks-active-tiles/assets/102395056/0e7c6b5b-e549-46f6-ad40-5a92dc042013)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/102395056/fd452239-367a-423e-b204-e621735d42c8)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/102395056/6492d6e3-8ac5-4664-8806-bc91fb9fae70)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/102395056/d6aca753-340e-41fe-99f9-f7350edcf232)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/102395056/f96dcf77-2512-40a2-bee1-e23de9ac9ee5)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/102395056/4bb4c5dd-7f45-4596-adc8-daa46d6a44f6)

As you can see, the only changes from the default settings are the deselection of "Loop Video" and "Autoplay Video" under the "Animation" property settings.

For reference, this is now under PF2E version 5.3.1 and Foundry version 11 Stable build 307.

**Comment by ironmonk88** [comment]
I've matched those settings and I still can't replicate the issue.

**Comment by Crowguard** [comment]
I also cannot replicate this issue with these settings.

**Comment by Crowguard** [comment]
Not a MATT problem, its a core problem.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/4771ce22-b383-4c5d-ba6c-9fa2296c83c4

**Comment by Crowguard** [comment]
This is a core issue, and its intentional. Not a MATT problem.

https://discord.com/channels/170995199584108546/494726439263010826/1152688634491838566

**Comment by jacksda0240** [comment]
My apologies for the delay in responding.  I ran testing on my test setup and can confirm that it is an issue with the core functionality of FoundryVTT.

I would like to apologize for taking up your time with troubleshooting this issue.  Thank you for taking the time.
