### ISSUE TITLE
Add _rotate to the list of auto populated landings in the landing title box

### ISSUE THREAD

**Issue by WizardForHire123** [ironmonk88/monks-active-tiles#564]
Just a minor upgrade for _autolandings 
_rotatation is missing from the auto populated list

**Comment by ironmonk88** [comment]
Also added darkness and time

**Comment by ironmonk88** [comment]
That.... sounds like the lyrics to a rock anthem.

**Comment by ironmonk88** [comment]
Added to the latest release.
Also added `_elevation##` to trigger when a token changes elevation to that height.
