### ISSUE TITLE
[BUG] Active tiles only selecting one token as objective 

### ISSUE THREAD

**Issue by Dengacuman** [ironmonk88/monks-active-tiles#565]
I'm using a tile as a trap,
Using a token actor and a weapon to trigger the effect
![Captura de pantalla 2023-07-25 190046](https://github.com/ironmonk88/monks-active-tiles/assets/140530894/b88a2050-0d19-4322-a63d-3f23270d9933)

When the tile gets triggered, even thoug the entitiy selected is set to "player tokens" or "tokens within this tile" the 
message of the attack is shown 3 times, but if I roll the damage it only selects as target one of them.
![Captura de pantalla 2023-07-25 181746](https://github.com/ironmonk88/monks-active-tiles/assets/140530894/149a30a5-ab4d-49b7-b9ad-09953f74cdbd)

I'm using Midi QOL 10.0.41, MATT 10.15 and Foundry 10.291 and Browser is chrome
Sorry the capture is in spanish, I can add another one in english if you need

**Comment by ironmonk88** [comment]
Is this still an issue in the latest Active Tiles?
The attack action has changed since then and I'm unable to replicate.

**Comment by ironmonk88** [comment]
Closing this as there's been changes, I'm unable to replicate and there's been no response to the question.
