### ISSUE TITLE
[BUG] Brief description of your issue

### ISSUE THREAD

**Issue by Zarhog** [ironmonk88/monks-active-tiles#568]
<img width="640" alt="image" src="https://github.com/ironmonk88/monks-active-tiles/assets/76391362/de3c6ce5-4e9e-4dba-8386-fcc1b9b4146c">

this option dose not work

**Comment by ironmonk88** [comment]
Closing this as the ticket doesn't have a proper header, didn't include enough information.
And ultimately, the example provided does not indicate that there is an issue.
