### ISSUE TITLE
[Feature Request] Clear Variables Action

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#571]
An action to clear all variables on tiles with the usual targeting options.

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/59411bed-148c-4c37-95ad-e45ca3ae28fb)

**Comment by ironmonk88** [comment]
Added to the `Set Variable` action.  Setting the variable to `_null` will clear it.
You can also use wildcards to affect variables now.
