### ISSUE TITLE
[BUG] Attack Error

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#572]
Showed up in the console when testing another ticket. Results when one of the targets is PF2's `Loot` type tokens. Assuming its because there's no values to check the attack against.

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/45d2dde4-076c-44d2-8099-4693749aeb1b)

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/8d4654c9-6d36-4c74-bf87-43a14c582e4a)

MATT 11.02
PF2 5.3.1

**Comment by ironmonk88** [comment]
Fixed in the latest release.
