### ISSUE TITLE
Set flex: 0 on dialog buttons for Show Dialog action

### ISSUE THREAD

**Issue by RHeynsZa** [ironmonk88/monks-active-tiles#574]
**Is your feature request related to a problem? Please describe.**
Yes. Since both `dialog-content` and `dialog-buttons` is set to flex: 1, you get this type of behaviour:

![image](https://github.com/ironmonk88/monks-active-tiles/assets/58415372/546532de-2c82-4749-94ae-33ab28b60945)

**Describe the solution you'd like**
Setting `flex: 0` on `dialog-buttons`, gives this behaviour

![image](https://github.com/ironmonk88/monks-active-tiles/assets/58415372/24d89a38-9bc7-4d87-a99e-1e6abc728c88)

**Additional context**
Thanks

**Comment by ironmonk88** [comment]
Fixed in the latest release.
