### ISSUE TITLE
[BUG] Check Entity Count, Current Users

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#576]
Check Entity Count lacks a `current user collection` to be able to use the new Filter by Attributes ability.
![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/d41733a9-9039-42d3-9f37-d9cc4bf6772a)

MATT 110.6

**Comment by ironmonk88** [comment]
Added to the latest release
