### ISSUE TITLE
[BUG] Active Effect action

### ISSUE THREAD

**Issue by rintiny2k** [ironmonk88/monks-active-tiles#577]
When trying to remove an active effect e.g Dead, Asleep. Using an active tile, nothing happens, also the add option seems to work the same as toggle.

**Comment by Crowguard** [comment]
@rintiny2k Please include the following information that the ticket form already asked for:

* Module version
* Foundry version
* System version
* Whether you ran Find The Culprit.

This action is working for me as expected in PF2E 5.3.2.

**Comment by rintiny2k** [comment]
Module version = 11.06
Foundry version = 11 (Build 307)
System version = dnd5e 2.3.0
Whether you ran Find The Culprit. = is that a module?

![Screenshot 2023-08-17 062144](https://github.com/ironmonk88/monks-active-tiles/assets/1035957/3fee7b13-e76f-4273-88e9-7c698e8e0a10)
![Screenshot 2023-08-17 062227](https://github.com/ironmonk88/monks-active-tiles/assets/1035957/d7589386-583d-4a55-9222-fdcf13c18548)
![Screenshot 2023-08-17 062639](https://github.com/ironmonk88/monks-active-tiles/assets/1035957/b16ad2bc-1e2e-4a6e-9c07-ac5c5c0c5944)

**Comment by ironmonk88** [comment]
Fixed in the latest release.
