### ISSUE TITLE
[BUG] Chat Message, Polyglot

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#580]
Messages aren't created using Polyglot rules. Several errors.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/81c378b8-f051-4faf-8257-0d7091cecb7e

MATT 11.06
Polyglot 2.1.0

**Comment by ironmonk88** [comment]
I can no longer replicate this... and I think this is probably a Polyglot issue.

**Comment by Crowguard** [comment]
Working as expected for me again with Polyglot 2.1.7.
