### ISSUE TITLE
[BUG] Click is Triggering on Right-Click

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#581]
Click triggers are going off on right-click; double-click seems fine.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/a34fb1e4-175b-44cd-8a3a-7382fc7a1224

Foundry 11.308 (edited cause I forgot this)
MATT 11.06

**Comment by ironmonk88** [comment]
Fixed in the latest release.
