### ISSUE TITLE
[BUG] Current Wall getting lost across jumps

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#584]
The `current wall collection` seems to be getting lost across jumps now; this tile used to work as a template, but it's no longer changing the door state on the Break or Lockpick success threads.

[fvtt-tiledata-ultimate_door.zip](https://github.com/ironmonk88/monks-active-tiles/files/12412497/fvtt-tiledata-ultimate_door.zip)

MATT 11.06
Foundry 11.307
PF2 5.3.2

**Comment by ironmonk88** [comment]
Fixed in the latest release.
