### ISSUE TITLE
[BUG] Trigger Tile Requires GM on Scene

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#586]
The `Trigger Tile` action no longer runs at all without the GM on the same scene. No errors.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/76ba6911-91d0-4786-8c1b-c42a6c372991

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/b31c0767-a786-4815-8492-5cd77ef42b44)

MATT 11.06
Foundry 11.308

**Comment by Grandsome** [comment]
Can confirm the bug happened to me too.

**Comment by ironmonk88** [comment]
You're using tagger for the other Tile... did you happen to specify `All Scenes`?
![image](https://github.com/ironmonk88/monks-active-tiles/assets/75920956/7b2c001f-b411-41aa-9582-e1a8559e910f)

**Comment by ironmonk88** [comment]
Is this still an issue?  I can't replicate on the latest version.  The tile is triggered while the GM is off the scene, so it might be a tagger set up issue instead?

**Comment by ironmonk88** [comment]
Fixed in the recent release.
