### ISSUE TITLE
[BUG] Html upload on Show Dialogue

### ISSUE THREAD

**Issue by WizardForHire123** [ironmonk88/monks-active-tiles#587]
HTML not working. 
![image](https://github.com/ironmonk88/monks-active-tiles/assets/98988680/0e98a5cc-f349-4da1-a01f-129dd99b9da9)

**To Reproduce**
1. Go to a custom dialogue
2. upload an html file
3. run the tile
4. it doesn't run 
**Expected behavior**

**Please complete as much of the following information as possible:**
 - Browser chrome
 - Foundry Version 11.308 
 -  - System PF2e
 - Module version 11.06
 - Are there any errors in the console [e.g. press F12 and look for red text]
 - 
![image](https://github.com/ironmonk88/monks-active-tiles/assets/98988680/0c535cef-a3c6-4400-9db0-dec959892319)

 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. no works when you copy the html in. was discovered on the discord by Red Duke

**Comment by ironmonk88** [comment]
That looks like a Foundry issue.
Their `getTemplate` function is expecting a relative link, not a static link.  So trying to get data from your Forge directory is going to fail.
I'm adding this as a note to myself to see if there's anything I can do to compensate.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
