### ISSUE TITLE
Hurt action does not apply damage to token.

### ISSUE THREAD

**Issue by Raezenkane** [ironmonk88/monks-active-tiles#591]
**Describe the bug**
A tile with the Hurt action does not apply damage to a triggering token.
MATT throws this error in the console:
`monks-active-tiles.js:16 monks-active-tiles |  Error: One of original or other are not Objects!
    at mergeObject (commons.js:2359:13)
    at ActorCharacterPF.applyDamage (actor-pf.mjs:3024:7)
    at TileDocument.fn (actions.js:1878:49)
    at async TileDocument.runActions (monks-active-tiles.js:4043:56)
    at async TileDocument.trigger (monks-active-tiles.js:3981:36)`

**To Reproduce**
1. Create tile
2. Add Hurt action at -15
3. Drag token onto tile
4. See error in console

**Expected behavior**
Hurt action should have applied damage to token

**Screenshots**
![MATT Tile 1](https://github.com/ironmonk88/monks-active-tiles/assets/129948578/b2b560ce-492e-4238-881e-ac1ae999f13e)
![MATT Tile 2](https://github.com/ironmonk88/monks-active-tiles/assets/129948578/c7c49ec8-d4e1-4f47-b5d2-f1ed5ec152a2)

**Please complete as much of the following information as possible:**
 - Chrome Version 116.0.5845.140 (Official Build) (64-bit)
 - Foundry Version 10 303
 - System Pathfinder 1e, version 9.4
 - Module version 10.21
 - Are there any errors in the console [e.g. press F12 and look for red text] - Yes, listed
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.  Not yet!

**Additional context**

**Comment by Crowguard** [comment]
Confirming this is still an issue with 

MATT 11.06
Foundry 11.308
PF 9.4 Doesn't look like they've actually done any update to v11 yet.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
