### ISSUE TITLE
[BUG] Tile Templates, Create Folder

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#593]
Seems to be something weird going on with folders. Subfolders are not being created inside their folder, and some folders don't display until another folder is created, or a newly created folder is displayed over the last created one.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/774d9634-952d-4514-8153-dd47ee7b51a7

MATT 11.06
Foundry 11.308

**Comment by ironmonk88** [comment]
Fixed in the latest release.
