### ISSUE TITLE
[BUG] Delay & Stop Remaining Actions, No GM

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#598]
It seems Delay & Stop Remaining Actions are attempting to run without a GM present, and causing various permission errors.

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/88cac68d-8a8d-458f-8d16-993fbd6347be)

MATT 11.06
Foundry 11.308

**Comment by ironmonk88** [comment]
Stop Remaining Actions is fixed.
But... Delay doesn't cause the issue, it just runs all the current batch actions.  Which means something was put into the batch that was causing issues.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
