### ISSUE TITLE
"Error: Syntax error, unrecognized expression:"

### ISSUE THREAD

**Issue by jocolamarco** [ironmonk88/monks-active-tiles#6]
**FVTT version:** 0.8.7
**Module version:** 1.0.9 (latest)

Token moves through the tile and triggers the message (trigger events work without issue) however, the following error message is logged in the console:

![image](https://user-images.githubusercontent.com/45291719/123081432-dbaecd80-d415-11eb-8fad-2ea65734b7d4.png)

**Comment by ironmonk88** [comment]
I have a feeling there's another module running interference.
Can you test with just active tiles enabled?

**Comment by ironmonk88** [comment]
Closing this as there's been no response and I'm tidying up tickets.
