### ISSUE TITLE
Traps on ground layer trigger even when token has elevation and would/should not trigger

### ISSUE THREAD

**Issue by ArchiusPendragon** [ironmonk88/monks-active-tiles#60]
Example:
Beartrap - clearly on the ground, clearly requires being stepped on - Tile is marked as an underfoot tile as a result.
Aarakocra flying 20 feet above the ground still triggers the trap.

Something to stop activation if token is above set elevation (or below set elevation) would be an ideal solution for this (to prevent a creature who's already been elevated by another source being elevated higher by ground based systems)

**Comment by ironmonk88** [comment]
You should be able to add an action to filter by token attribute.  If you check elevation > 0 then you can prevent it from triggering for tokens that are flying.
