### ISSUE TITLE
[BUG] Set Active Tiles Collection

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#600]
Error shows up when `Owners` is checked. Also, what does this do exactly? Based on this changelog `Added the option to set the current collection based on users.` I believe it adds the users that own the tokens being targeted, but I thought I'd check.

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/92334d58-6d52-4830-aaf2-649447983472)

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/ef6dd7fd-ccba-492d-8aee-f5ea029ec60b)

MATT 11.06
Tagger 1.4.5

**Comment by ironmonk88** [comment]
It gets the owners of the entities retrieved.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
