### ISSUE TITLE
[BUG] Change scene not working

### ISSUE THREAD

**Issue by alexpouteau** [ironmonk88/monks-active-tiles#603]
**Describe the bug**
I've just updated the module to 11.07 and the tiles with the "change scene" no longer work on the foundry application, but seem to work on the browser I use: Opera.

**To Reproduce**
1. Make a tile with the "change scene" action
2. Click on the tile from the foundry app
3. Nothing happens
4. When I click, this error is displayed in the console:
![image](https://github.com/ironmonk88/monks-active-tiles/assets/34100229/0419aaf4-28b6-4a38-b192-171c79f3fb26)

**Expected behavior**
Yesterday, before the update, when I clicked on the tile, it transported me to a different scene, even from the Foundry application.

**Please complete as much of the following information as possible:**
 - Browser [Foundry app]
 - Foundry Version [v11.309]
 - System [Symbaroum]
 - Module version : 11.07

**Comment by ironmonk88** [comment]
Fixed in latest release.
