### ISSUE TITLE
[Feature Request] Random Number Handlebars Support

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#605]
I think this may be the last field that doesn't accept handlebars. Was attempting to set this tile up with handlebars and noticed it.

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/99f1d9e0-ab74-4ea8-945e-8d3910acbe3f)

**Comment by Crowguard** [comment]
Field still doesn't seem to accept any characters besides numbers or the letter `e`.
https://github.com/ironmonk88/monks-active-tiles/assets/99844555/42801013-8ff4-4771-a059-3a641b8f8458

MATT 11.11
Foundry 11.311

**Comment by ironmonk88** [comment]
Added to the latest release
