### ISSUE TITLE
Add tag option for "Stop sound"

### ISSUE THREAD

**Issue by Shayulghul** [ironmonk88/monks-active-tiles#608]
**Is your feature request related to a problem? Please describe.**
The "Stop sound" option only has two options: "select an entity" or "use this tile." 

**Describe the solution you'd like**
I'd like to be able to use tagger to stop the sound for multiple tiles without having to list each tile in the actions.

**Additional context**
My current use case is a village with trigger tiles that let players go to shops and locations on their own. Each location has its own playlist sound that's set to trigger only for that triggering player. The overview village map has its music as well. The effect is that each player only hears the music for the current scene they are on.

**Comment by ironmonk88** [comment]
Added to the latest release
