### ISSUE TITLE
[BUG] Teleport/move assumes that the destination is the GM's viewed scene

### ISSUE THREAD

**Issue by VulpTheKangaFox** [ironmonk88/monks-active-tiles#613]
**Describe the bug**
It appears that when a player token moves onto a tile to teleport, if the GM is on another scene it will assume that the token is being teleported to that same scene. Leads to the original getting deleted on the scene the player **should** be on, and them being put practically anywhere on the scene the GM is on.

The tile seems to trigger on the GM side with the GM's variables regarding scene and whatnot. I'd want to trigger it for the player's side.

**To Reproduce**
1. Make a teleport trigger.
2. Have a player trigger it with their token while the GM is on a different scene.
3. Likelihood is that the token is teleported to the GM's currently viewed scene.

**Expected behavior**
Well I'd expect for the token to teleport relative to the scene that the teleport is triggered in.

**Please complete as much of the following information as possible:**
 - Foundry Application. Players using various browsers.
 - Foundry v11
 - D&D 5e
 - Monk's Active Tile Triggers v11.6
 - I feel that errors aren't applicable here, since it seems to just be a logic issue more than anything. I wish for the tile to trigger relatively to the player not the GM.
 
 Let me know if I'm just being an idiot and there's already a solution for this.

**Comment by ironmonk88** [comment]
Please update to the latest Active Tiles, 11.11 and try again.  There's been some fixes to the teleport actions since 11.6

**Comment by ironmonk88** [comment]
Closing this as there's been no response and there have been updates tot he code.
