### ISSUE TITLE
[BUG] Attack

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#616]
Running two attacks in the same thread seems to be causing this issue with one of the attack items being replaced (clicking the former Lay On Hands displays the Light spell in chat) until the attackers's sheet is edited again.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/5b941e21-1ab1-480b-90ca-e7ad7706c401

Foundry 11.313
MATT 11.11

**Comment by Crowguard** [comment]
Update: it's now rendering the item that was changed un-openable; attempting to do so results in this error.

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/7bccebbe-c959-4604-9900-f010732fb84e)

MATT 11.17
Foundry 11.315
Pf2 5.10.3

**Comment by ironmonk88** [comment]
Fixed in the recent release.
