### ISSUE TITLE
Open a Journal/Show Image  to Varying Targets

### ISSUE THREAD

**Issue by BarovianBadass** [ironmonk88/monks-active-tiles#617]
As per the [discussion on discord](https://discord.com/channels/862414864692281386/862421211749154816/1161712347816136734), can the target of whom the journal/image is being shown to be more comprehensive than the dropdown menu currently presents. Having a wider range of possibilities would be very helpful when trying to share information and images with only certain players.
![image](https://github.com/ironmonk88/monks-active-tiles/assets/112812283/b71cbb29-3a97-4f5d-966e-74383b033880)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/112812283/c2313df9-26c6-4254-8222-b141e48d27bb)

**Comment by ironmonk88** [comment]
Added to the latest release
