### ISSUE TITLE
[BUG] "Change Scene" causes camera to briefly "lock" and doesn't allow to pan.

### ISSUE THREAD

**Issue by NikolaSama** [ironmonk88/monks-active-tiles#618]
**Describe the bug**
Using the "Change Scene" action on a Tile will change the Scene, but the camera becomes locked up (Unsure if it's time based or "mouse-click' based for the duration), not allowing you to move the camera. As a side-effects, it's not possible to Change Scene and then Pan to location.

**To Reproduce**
1. Setup a Tile to Change Scene
2. Activate

**Expected behavior**
Changing Scene used to allow immediate movement, and we would use it to pan to the current location on a world map.

**Please complete as much of the following information as possible:**
 - Chrome Version 118.0.5993.70 (Official Build) (64-bit)
 - Foundry Version v11.313
 - System D&D5e 2.3.1
 - Module version 11.11
 - No Errors
 - Error persists with just Active Tiles enabled

**Comment by ironmonk88** [comment]
This is unfortunately a Foundry bug.
I can get this to trigger by having the GM activate a scene while the player clicks as fast as they can while not moving the mouse.
It'll then lock up for the player.
While that scenario might not happen that often, I think MATT has unfortunately made it so it happens nearly every time.
You can prevent the lock from happening if you move you mouse just a bit while clicking.
And you can release the lock by literally doing anything outside of the canvas, hover over a token, or the toolbar or the scene menu, or the side menu, or moving the mouse off the browser and back on.
I've tried a bunch of things to try and make it work... but nothing I do seems to help.

**Comment by ironmonk88** [comment]
Closing this as Foundry has fixed the bug.
It's not 100% working, it can still lock up, but after the first mouse event not working, the second one begins working again.
