### ISSUE TITLE
Feature Request: Add Global Default - Restricted Tokens

### ISSUE THREAD

**Issue by SoilentBrad** [ironmonk88/monks-active-tiles#619]
It would be great to have a global default in Settings to be able to set the Restricted Tokens. Generally, I only want player tokens to trigger tiles. Especially since I use Item Piles, and the Pathfinder 2e system has a "Loot" actor type - both of which tend to trigger tiles when I'm placing them because I forgot to set the restricted tokens.

**Comment by ironmonk88** [comment]
Added to the latest release
