### ISSUE TITLE
Show Tile error

### ISSUE THREAD

**Issue by rinnocenti** [ironmonk88/monks-active-tiles#62]
A few updates ago the bug had been fixed but has now returned.

https://user-images.githubusercontent.com/3178127/133940786-abf2ae41-f3ce-4926-97e8-bd8e4b35082a.mp4

_Originally posted by @rinnocenti in https://github.com/ironmonk88/monks-active-tiles/issues/55#issuecomment-922525578_

**Comment by ironmonk88** [comment]
As far as I can tell... that's an issue with Levels.  Checking with my code and it's after I've updated the Tile in question and Active Tiles has done what it needed to do.

**Comment by ironmonk88** [comment]
Closing this as I believe it was an issue with Levels and the code has changed so much since then, that it may no longer be an issue.
