### ISSUE TITLE
[BUG] Use Tagger Handlebars

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#621]
11.07 update notes includes the following line:

```Added the option to use handlebar notaion with tagger tags```

Attempting it with this setup results in this error in the console

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/7f344e6f-e226-4ef1-8b01-bad178f9eae2)

I'm not sure if I'm reading the notes wrong and the handlebars only work with the Alter Tag action, or this is broken.

MATT 11.11
Foundry 11.313

**Comment by ironmonk88** [comment]
I can't replicate it... but I might have already fixed it.

**Comment by Crowguard** [comment]
Confirmed its fixed as of 11.17.
