### ISSUE TITLE
[BUG] % Chance to Trigger

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#624]
While it isn't actually triggering, it is producing console messages whenever a token moves outside the tile. Notably, the tile doesn't even have the movement trigger. It only occurs if the % chance is less than 100.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/194fb9e0-aafd-4c29-85db-1b31ffeb9125

MATT 11.11
Foundry 11.313

**Comment by ironmonk88** [comment]
Added to the latest release
