### ISSUE TITLE
[Feature Request]Play only one track in the playlist once.

### ISSUE THREAD

**Issue by asanginxst** [ironmonk88/monks-active-tiles#628]
Try to play only a single track in the list once when tile is triggered, instead of looping/randomly/simultaneously playing the entire list.

This will be used for some random sounds (footstep) of token movement(stop/end).

**Comment by ironmonk88** [comment]
It already does that.  Just click on the track you want to play instead of the playlist.

**Comment by ironmonk88** [comment]
Also, make sure your playlist is set to `Soundboard`

**Comment by asanginxst** [comment]
> Also, make sure your playlist is set to `Soundboard`
My bad，thank you for your reply :D
