### ISSUE TITLE
[BUG] Set Active Tiles Current Collection

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#629]
Does not seem to be currently adding any entities; the tile in the video does not work, with or without the limit in place. The scrolling text works as expected on it's own.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/d6d5ab3c-3bcb-4481-bf0d-6537868423fe

MATT 11.11
Foundry 11.313

**Comment by ironmonk88** [comment]
Added to the latest release
