### ISSUE TITLE
[BUG] 5e Attributes

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#630]
It may be possible attribute paths may have changed and broken some actions. Or something else weird is going on.

### Set Variable
![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/fdd7e66c-4d13-4e4f-9335-a52b38b37c35)
Works like this in PF2

Same setup in 5e 2.3.1 results no value being saved.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/fb3e153c-a684-4667-a181-1e450fc0b773

Altering `attributes.hp.value` works however, so I'm not entirely sure what's going here at the moment.

MATT 11.11
D&D 5e 2.3.1
Foundry 11.313

**Comment by ironmonk88** [comment]
It's `actor.system.attributes.hp.value`.
Not sure what PF2E is doing to make that work... but there always needs to be a system in there to access system values.

Alter is special in that it knows to test without having to specify system.  But no where else is going to do that.

**Comment by Crowguard** [comment]
Noted; thank you and sorry for the confusion.
