### ISSUE TITLE
[BUG] Only global volume tiles triggered by GM.

### ISSUE THREAD

**Issue by asanginxst** [ironmonk88/monks-active-tiles#631]
**Describe the bug**
Only global volume tiles triggered by GM,players cannot trigger.

**TO Reproduce**
-Version: FVTT Version 11 Stable 314.
-System: DND5e - Fifth Edition System 2.3.1.
-Mods: Monk's Active Tile Triggers.
1.Create tile.
2.Trigger condition: Any.
3.Tile action: Global volume.

**Expected behavior**
Players should trigger the action to lower the volume when entering the global volume tiles.
It will be used to simulate the effect of some walls reducing sound volume.

GM:<img src="https://i.ibb.co/RTq84m9/Honeycam-2023-11-05-01-40-29.gif" alt="Honeycam-2023-11-05-01-40-29" border="0" />
Teste:<img src="https://i.ibb.co/P4FMfKy/Honeycam-2023-11-05-01-39-57.gif" alt="Honeycam-2023-11-05-01-39-57" border="0" />

**Comment by asanginxst** [comment]
New discovery: Players can trigger global volume actions to lower/increase my volume (GM) ;D

**Comment by ironmonk88** [comment]
Added to the latest release
