### ISSUE TITLE
[BUG] Teleport will not trigger 'enter/exit' actions.

### ISSUE THREAD

**Issue by asanginxst** [ironmonk88/monks-active-tiles#632]
**Describe the bug**
Teleport will not trigger 'enter/exit' action.

**To Reproduce**
1. Create an tile,Trigger any action when ‘Enter'.
2. Create a Teleport tile.

**Expected behavior**
I'm not sure if this is a bug or a  enhancement request.
For GM, this is indeed a teleport, and I have applied it to some multi-level battle maps.
But for players, they did indeed 'Enter' another tile through this teleport tile.
I can bypass this issue by adding actions to the teleport tile, but for some battle maps with multiple teleport tiles, this is difficult.

**Screenshots**
<img src="https://i.ibb.co/vVJc2mG/IMG-1.png" alt="IMG-1" border="0" />

Enter SAY TILE:
<img src="https://i.ibb.co/3kFZgn4/IMG-2.png" alt="IMG-2" border="0" />
<img src="https://i.ibb.co/yk9N0tj/Honeycam-2023-11-05-14-38-40.gif" alt="Honeycam-2023-11-05-14-38-40" border="0" />
Teleport:
<img src="https://i.ibb.co/wcV2hpS/IMG-3.png" alt="IMG-3" border="0" />
<img src="https://i.ibb.co/rmQmz7V/Honeycam-2023-11-05-14-39-00.gif" alt="Honeycam-2023-11-05-14-39-00" border="0" />

**Please complete as much of the following information as possible:**
-Version: FVTT Version 11 Stable 314.
-System: DND5e - Fifth Edition System 2.3.1.
-Mods: Monk's Active Tile Triggers.

**Comment by Crowguard** [comment]
Post a screenshot the action config and teleport action please.

**Comment by asanginxst** [comment]
> @asanginxst Post a screenshot of the action config and teleport action please.
OKAY :D

**Comment by Crowguard** [comment]
Re-reading it, that isn't a bug, it's intended. Otherwise you would have teleporting between multiple teleportation tiles triggering an infinite loop.

**Comment by ironmonk88** [comment]
That's working as intended for the reasons stated above.  But also... it's not really "entering" the Tile, so much as suddenly appearing within the Tile.

You could potentially work around it by adding a `Movement` action immediately afterwards with the option to trigger tiles on movement.

**Comment by asanginxst** [comment]
> Re-reading it, that isn't a bug, it's intended. Otherwise you would have teleporting between multiple teleportation tiles triggering an infinite loop and crashing Foundry.

I see. Thank you for the answer^^
