### ISSUE TITLE
Clear @all Temp Effefects on Triggering Token

### ISSUE THREAD

**Issue by Zarhog** [ironmonk88/monks-active-tiles#634]
**Is your feature request related to a problem? Please describe.**
I want to have it so that when a thing happens it clears the Temp effects on a triggering token

**Describe the solution you'd like**
add a value for  "Clear all Temp Effects"

**Additional context**
This will allow me to clear temp effects that have not yet ended at the end of a game

**Comment by ironmonk88** [comment]
Added to the latest release
