### ISSUE TITLE
[Feature Request] Playlist Function Expansion

### ISSUE THREAD

**Issue by asanginxst** [ironmonk88/monks-active-tiles#636]
**Is your feature request related to a problem? Please describe.**

Add a feature to the playlist that allows tokens to play the selected playlist in a sequential, random, or looping manner when triggering tile conditions.
It should be noted that this trigger will only play one track in the playlist. When the track stops playing, the next track will not play until the token triggers the tile again.

It will be used to create some rhythmic footsteps. Or the sound effect of certain doors being damaged.

I have tried the solution you provided earlier - it seems that it cannot achieve this effect...
Because it always plays the selected track.

**Comment by ironmonk88** [comment]
You can just use the Alter action to changes the Playlist mode.
![image](https://github.com/ironmonk88/monks-active-tiles/assets/75920956/878b712d-9f1f-4f12-80c5-95e0083f97fc)

**Comment by ironmonk88** [comment]
If you have Discord, here's a link to my server.  https://discord.gg/mBvZcvWe
I think some of these questions on how to do things could be answered there.

**Comment by asanginxst** [comment]
> If you have Discord, here's a link to my server. https://discord.gg/mBvZcvWe I think some of these questions on how to do things could be answered there.

Thank you for your reply, it has helped me!
