### ISSUE TITLE
Feature Request: Open combat window

### ISSUE THREAD

**Issue by Mjb141** [ironmonk88/monks-active-tiles#64]
Adding to combat is excellent but if we could pop the combat window (right-click on combat window) for everyone once we've done so that'd be perfect.

**Comment by ironmonk88** [comment]
Adding the option to start the combat.
Popping open the combat window heads into the territory of ui changes, and I think is outside of what Active Tiles should do.
That being said... it is something that Monk's Little Details already does.  So using that module plus the new option to begin combat should provide the effect you're looking for.

**Comment by ironmonk88** [comment]
Closing this ticket as there is a workaround for all the requests.
