### ISSUE TITLE
[BUG] Loop Through Entities

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#644]
Does not seem to be passing the tokens I believe.

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/73e3669f-5a0e-49d2-945a-c8d7e15d0d8f)

^ I tested with 3 Tagged tokens, and it seems to counting them properly; they just aren't getting added to the list.

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/3126e55a-2e68-4e26-88fe-ddb7fbba94f4)

MATT 11.12
Foundry 11.315

**Comment by ironmonk88** [comment]
Fixed in recent release
