### ISSUE TITLE
[BUG] Change Permissions

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#645]
Action fails to change permissions and results in warnings; a lot of warnings if the target is an actor.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/5397c9d9-137e-418a-8db9-d4f531c9351f

Foundry 11.315
PF2 5.8.3
MATT 11.12
MEJ 11.07

**Comment by ironmonk88** [comment]
Fixed in recent release
