### ISSUE TITLE
[BUG] Open Journal, Check Permission

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#646]
The Check Permission settings seems to be doing nothing ATM; it seems it always checking regardless. Giving a player observer or owner of the journal works as expected.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/baddf0a0-ce4b-4e3c-9173-6c7c6213428e

Foundry 11.315
PF2 5.8.3
MATT 11.12
MEJ 11.07

**Comment by ironmonk88** [comment]
Fixed in recent release
