### ISSUE TITLE
[BUG] "Remove Target" from tagged entity actually targets every entity WITH tag

### ISSUE THREAD

**Issue by Janner3D** [ironmonk88/monks-active-tiles#651]
![image](https://github.com/ironmonk88/monks-active-tiles/assets/35965176/5fcd826d-7df0-4143-be55-b0cd3ada7640)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/35965176/5faf0454-d7f4-498f-adac-377a47d1dc83)

For some reason, attempting to remove players' targets from every entity with a certain tag actually seems to force them **_to_** target every entity with the tag.

**_MATT Version:_** 11.15
**_Foundry Version:_** 11, build 315
**_DnD5e Version:_** 2.3.1

**Comment by ironmonk88** [comment]
Fixed in the latest release
