### ISSUE TITLE
[BUG] Change Scene, Activate Scene

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#653]
Using `Activate Scene` now causes a 3-5 second delay between the tile being triggered and the action running. Any following actions are run before the Change Scene actually occurs. The user who reported it believes it started at some point after updating from 11.11, but isn't sure which of the following versions it actually started with.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/e3335b8f-6d79-4b5f-b14d-1d2fc9554222

MATT 11.16
Foundry 11.315

**Comment by ironmonk88** [comment]
That would be a 3 second delay.  :-(
Debug code

**Comment by ironmonk88** [comment]
Fixed in the latest release
