### ISSUE TITLE
[BUG] Add Item, PF2 Effects

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#657]
Seems to be an issue removing Effects that were not added by MATT; removing ones added by dragging from the sidebar errors. It does not seem to be an issue with equipment item types that I've tried so far.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/63f2f44f-321f-43b0-9f71-df8a80a702a7

MATT 11.17
Foundry 11.315
PF2 5.9.4

**Comment by ironmonk88** [comment]
Fixed in the recent release.
