### ISSUE TITLE
Request Roll pass/fail doesn't work

### ISSUE THREAD

**Issue by Gingyivitis** [ironmonk88/monks-active-tiles#66]
Hey, I've found that the Continue on pass/fail option doesn't work, it will just do the next action before anyone rolls, even with a delay it will go ahead. If it's set to autoroll the check, it seems to work fine. I'm using the PF2E system, so I don't know if that affects it

**Comment by ironmonk88** [comment]
It's working as expected.
Currently it can only continue if it does all the rolling because it doesn't know how to wait.
It's on the list of things to do.

**Comment by ironmonk88** [comment]
The last release should have added the option to wait for the rolls to complete.
