### ISSUE TITLE
[BUG] Change Wall/Door, Proximity

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#660]
Changing a wall from Proximity to Normal instead makes it behave as Reverse Proximity until the GM opens the wall configuration.

I suspect this is a core Foundry bug, but I don't know how to confirm this.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/d9443e12-d781-4b23-9e18-a56a853df2cb

MATT 11.17
Foundry 11.315

**Comment by Crowguard** [comment]
Update: user who reported it has a logical theory regarding it here.

https://discord.com/channels/862414864692281386/862421211749154816/1179502486327930920

**Comment by ironmonk88** [comment]
Fixed in the recent release.
