### ISSUE TITLE
[BUG] Chat card appears twice when locked door with trap is activated with right-click

### ISSUE THREAD

**Issue by Geektasticdad** [ironmonk88/monks-active-tiles#665]
**Describe the bug**
When a character right-clicks on a locked door that is trapped with a single attack action, it duplicates the attack card in the chat. 

**To Reproduce**
1. Create tile with door trigger
![image](https://github.com/ironmonk88/monks-active-tiles/assets/73676044/095675ff-7282-4925-90d5-fafbc144bab5)
2. Add "Attack" action to tile
![image](https://github.com/ironmonk88/monks-active-tiles/assets/73676044/9335cbf5-2343-4634-8b16-28151d6acd6e)
3. Log in as player, and right click a locked door.
4. See duplicate tiles
![image](https://github.com/ironmonk88/monks-active-tiles/assets/73676044/f13da69b-55a0-4fae-9eb5-9afbba8a3d05)

**Expected behavior**
I would expect that the chat card would only appear once.

**Screenshots**
See above

**Please complete as much of the following information as possible:**
 - Browser chrome
 - Foundry Version v11 build 315
 - System D&D5e
 - Module version 11.17
 - Are there any errors in the console: No errors, just a duplicate chat message 
![image](https://github.com/ironmonk88/monks-active-tiles/assets/73676044/dc2dac29-498c-405e-a1e7-4b2e057744f7)
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. No

**Comment by ironmonk88** [comment]
I can't replicate this.  Try running Find the Culprit to see if there's another module causing interference.

**Comment by ironmonk88** [comment]
Fixed in the recent release.
