### ISSUE TITLE
[BUG] Redirect Request Results always fails

### ISSUE THREAD

**Issue by gludington** [ironmonk88/monks-active-tiles#667]
**Describe the bug**
When using Redirect Request Results, all results fail

**To Reproduce**
1. Create a tile with a roll, and a redirect based on results.  If in a 5e game, using the one from the wiki: https://github.com/ironmonk88/monks-module-wiki/wiki/ST-Request-Roll-Basic-Success-and-Failures is sufficient to illustrate the issue
2. Trigger the tile
3. Succeed on the roll.  
4. "Failure stuff" from the Fail landing will be sent to the chat window

**Expected behavior**
When a roll succeeds, the Pass landing will be 

**Screenshots**
Tile setup:
<img width="567" alt="image" src="https://github.com/ironmonk88/monks-active-tiles/assets/87745/17014dd4-2f0b-40a8-8fb6-626975eac23c">
Chat results:
<img width="316" alt="image" src="https://github.com/ironmonk88/monks-active-tiles/assets/87745/36e9fb3a-0822-4c65-83ee-f395226cef53">

**Please complete as much of the following information as possible:**
 - Browser chrome on OSX
 - Foundry Version 11.315
 - System D&D 5e 2.4.1
 - Module version 11.17
 - Are there any errors in the console: No
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. No, but I have created a new world with only MATT, Monk's Player Settings, and Monk's Token Bar as active modules and the problem persists
<img width="739" alt="image" src="https://github.com/ironmonk88/monks-active-tiles/assets/87745/4ad0d52a-3ff8-449b-837e-5f52c894beb4">

**Comment by gludington** [comment]
May be same as https://github.com/ironmonk88/monks-tokenbar/issues/432

**Comment by gludington** [comment]
Filed this pull request over in tokenbar project:

https://github.com/ironmonk88/monks-tokenbar/pull/433

**Comment by ironmonk88** [comment]
Closing this, it's a Tokenbar issue and has been fixed.
