### ISSUE TITLE
GM Actions don't only require a GM to be logged in, but he has to bei in the same Scene and have the Window in View

### ISSUE THREAD

**Issue by Muwak77** [ironmonk88/monks-active-tiles#669]
I Have a Trap-Tile that reveals the Trap when a player steps on in. As long as the GM is present in the Scene, this works fine, but if he leaves the scene the Image does not change. Same Problem when he is present in the scene but the Foundry-Window is minimized.

**Comment by Crowguard** [comment]
@Muwak77 Please take the time to read the ticket formatting and include the information that was asked for:

Foundry version
MATT version
Whether FTC was ran. 
Whether the console had errors.
And generally, posting a screenshot of your tile setup. 

I can replicate the first issue, but not the second. Tiles are running regardless of the GM's Foundry being minimized or not.

### GM Not on Scene


https://github.com/ironmonk88/monks-active-tiles/assets/99844555/7465a292-d5ea-4c9b-b74d-67683be79115

**Comment by Muwak77** [comment]
Sorry, i was kinda busy that day, here is the requested information:

Foundry Version 11 Build 315
MATT 11.17
I was not using FTC and there were no errors in the Console


Here is the Tiles Setup:
![image](https://github.com/ironmonk88/monks-active-tiles/assets/64545711/e6f7c19f-169f-4627-aba0-02ae398b2e24)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/64545711/e5715d61-8108-4bb2-88cb-a8a932fcfb2b)

Here is the issue in video:

https://github.com/ironmonk88/monks-active-tiles/assets/64545711/b25e2547-551e-4540-aff7-542312a70b18

**Comment by Crowguard** [comment]
@Muwak77 With your issue, are both the GM & the player logged in using browsers and not the electron app?

I suspect this may be a browser issue; I was able to replicate it from my Forge game on Chrome.

**Comment by Muwak77** [comment]
@Crowguard as you can see in my video, the GM is using Chrome while the Player is using Edge, as Foundry only allows one instance per Browser. 
I Also tested with chrome on different Computers with the same result. Server is Node.js on Ubuntu 22.04. 
All Browsers where updated to the latest Version before testing.

**Comment by ironmonk88** [comment]
Fixed in the recent release.
