### ISSUE TITLE
Request: Integration with "Stories" from Storyteller Mod

### ISSUE THREAD

**Issue by abominablerob** [ironmonk88/monks-active-tiles#67]
This is not a game changer or need, just a nice to have. 
Stories from the Storyteller Mod appear under the Journals heading in a separate tab. They function the same as journal entries, but provide a nicer layout, and easier interface to use than Journal Notes.
Thanks for the great work on all of you modules.

**Comment by ironmonk88** [comment]
Closing this... as I'm not sure what integration was being suggested.
Assuming this was just an old ticket and functionality has been changed, because you can easily open a Storyteller Journal using the Open Journal action now.
