### ISSUE TITLE
[BUG] Action Config Error

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#670]
Attempting to update an action configuration window after the tile has been closed results in this error.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/1f7f0ebe-7241-4716-a5eb-382eead24889

Foundry 11.315
MATT 11.17

**Comment by ironmonk88** [comment]
I'm guessing it should probably close the action config at the same time the Tile config is closed.  Makes no sense to keep it open.

**Comment by ironmonk88** [comment]
Fixed in the recent release.
