### ISSUE TITLE
[BUG] Stop Within Tile + Stop Token Movement

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#671]
Having multiple tiles with this combination next to each other results in the token getting moved to 0,0 when triggering, or even when just stopping outside the intersection where the tile edges meet.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/2e1de7ce-0930-4b93-b942-2a53a6054e32

MATT 11.17
Foundry 11.315

**Comment by ironmonk88** [comment]
Fixed in the recent release.
