### ISSUE TITLE
[Feature Request] Redirect Player Type Handlbars

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#672]
Found one more that does not accept handlebars; use case would allow more granular control over player vs gm interactions than auto-landings allow on their own.

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/1864ddc4-d0ab-450f-baec-7bdfb5db321f)

**Comment by ironmonk88** [comment]
Added to the latest release
