### ISSUE TITLE
[BUG] Loop Through Entities

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#675]
This action seems to be having two issues:

1. It does not seem to set the initial collection. First tile shown in the video. Not shown, but the variables are not being set because there is no token, so it seems the token is defaulting to 0,0. 
2. It does not seem to be looping through the collection; it just picks one. Second tile.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/d22339d2-654b-4392-9c49-195f8e91f989

Foundry 11.315
MATT 11.17

**Comment by ironmonk88** [comment]
Not really a bug. Should be `value.tokens.0.x`
This may have been a change?
But loop should now be putting the entities into their respective groups.

**Comment by Crowguard** [comment]
That works, my bad. Closing as completed.
