### ISSUE TITLE
Add a Handlebar expression to 'Write to Journal' action to add timestamp of the game world time. 

### ISSUE THREAD

**Issue by Mozmonar** [ironmonk88/monks-active-tiles#677]
**Is your feature request related to a problem? Please describe.**
Playing Call of Cthulhu 7e with Simple Calendar module, I have the game world time set to the time and date the game takes place, rather than real world time. When I add a trigger to give an item to a player I also have it write a note to the journal indicating who acquired the item and where using {{token.name}} and {{scene.name}} but when I added {{timestamp}} to indicate when they acquired it, the timestamp is real world time.

**Describe the solution you'd like**
Current behavior is shown in dummied up tile below. Ideally, I'd like to be able to add a timestamp that corresponds to the game time shown in the calendar.

**Additional context**
![write_ to_journal_timestamp](https://github.com/ironmonk88/monks-active-tiles/assets/20689320/4fb8990f-1ce6-4376-be3a-8021551514c7)

**Comment by Mozmonar** [comment]
For additional, perhaps relevant, information I have this setting checked in the Simple Calendar Global Configuration settings.
![simple_calendar_config](https://github.com/ironmonk88/monks-active-tiles/assets/20689320/c05e009e-d2ff-4802-b97f-c4e938378cd0)

**Comment by ironmonk88** [comment]
Added to the latest release.  Use `datetime`.
