### ISSUE TITLE
[BUG] Create Token, Use Tagger

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#678]
Attempting to create a token cross-scene using Tagger results in the token being created on the triggering scene in the location it would have been created at on the target scene.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/881811ce-c692-440c-96e4-74155bf9983c

Foundry 11.315
MATT 11.17
Tagger 1.4.5

**Comment by ironmonk88** [comment]
Fixed in the recent release.
