### ISSUE TITLE
[BUG] Teleport & Streamer

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#679]
1. The teleport wash is only rendering for the triggering player and not all token owners on the scene.
2. The streamer user is not changing scenes, only the triggering player.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/c0f35c55-bdde-45d7-9dc2-997cdb3e7337

Foundry 11.315
MATT 11.17

Also Common Display 11.05. User reported the same issue with Stream View. Not sure these are actually relevant here, but I'll include them.

**Comment by ironmonk88** [comment]
Fixed in the recent release.
