### ISSUE TITLE
[BUG] Show Dialog Templates

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#680]
New templates being saved with Show Dialog are having their "For" field reset to Triggering Player. Old templates seem to be fine.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/0f0d9640-d862-4f73-a4ce-1fdba481948a

Foundry 11.315
MATT 11.17

**Comment by ironmonk88** [comment]
Fixed in the recent release.
