### ISSUE TITLE
[BUG] Simple Calendar Handlebars

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#684]
Results in this error and no timestamp; at least in D&D 5e. No timestamp in PF2 either, but also doesn't error at all there (might be a conflict between Simple Calendar and PF2 there).

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/a37de775-97e4-47d1-a5da-253a369c9812

Foundry 11.315
MATT 11.19
Simple Calendar 1.3.75
D&D 5e 2.4.1
PF2 5.11.5

**Comment by ironmonk88** [comment]
My simple calendar is 2.4.3, do you have that module up to date?

**Comment by Crowguard** [comment]
Closing. Didn't realize there was a newer branch of Simple Calendar that required a clean install.
