### ISSUE TITLE
[Feature Request] / [Bug] Reset Tile History

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#686]
Reset Tile Trigger History doesn't seem to currently have a way to completely reset the history for all tokens due to the various `Current Token Collection` changes. At least not without the GM selecting the tokens to add them to the `Current Token Collection.`

Maybe add a checkbox option to completely wipe the tile history?

MATT 11.19

**Comment by ironmonk88** [comment]
Fixed in the latest release
