### ISSUE TITLE
[BUG] Token Requires Sight

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#689]
The issue where this doesn't function properly from the top/left side of the tile. Viewpoint is from the player. 

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/4cfae05f-611a-4dfd-afc1-44efcee8d945

MATT 11.19
Foundry 11.315

**Comment by ironmonk88** [comment]
Are the walls right on the edge of the Tile?
In which case... this is a Foundry issue not a MATT issue.

**Comment by Crowguard** [comment]
Yeah; they're all aligned to grid perfectly. Noted.
