### ISSUE TITLE
Request: Name/Notes field

### ISSUE THREAD

**Issue by IcyLemonZ** [ironmonk88/monks-active-tiles#69]
QOL Improvement

**Issue**: When active-tile Actions link to another object (tiles, tokens, lights, walls etc), it refers to the target by its internal Foundry ID. This can make it hard to see at a glance what a set of commands are doing to other objects. 

![image](https://user-images.githubusercontent.com/73080231/141516280-b2a9d47d-b218-4002-a8b7-bc6ad38d1111.png)

**Proposed Solution**: Each tile can be given a name by the user. If active-tiles ever refers to another object and needs to display it to the user (such as in the Actions list for a tile), it first checks for the presence of this name field, and if one is found it displays that value instead of the raw id. Else it displays the raw id as normal.

![image](https://user-images.githubusercontent.com/73080231/141515216-1b648c22-dfea-4129-80df-d3a95f90dba8.png)
E.g. This tile covers the area around a trap. It rolls perception rolls for anyone who enters. If they pass, it displays the PitTrap1 tile.

**Comment by ironmonk88** [comment]
Closing this, as I think it's a bit beyond what I want to do with Active Tiles.
Active Tiles will use a tagger value that has been added in the action description.  So you can use that module to achieve this effect.
