### ISSUE TITLE
[BUG] Filter by Convenient Effect Target

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#690]
This one seems to be missing `Triggering Token` now for some reason.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/b434ed1f-c67f-4483-87ac-b70eea41b475

MATT 11.20
Foundry 11.315
D&D 5e 2.4.1
DF Effects 6.0.0

**Comment by ironmonk88** [comment]
Fixed in the latest release
