### ISSUE TITLE
[BUG] Filter by Condition & DF Convenient Effects

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#691]
I'm not sure of the steps I took to cause this to occur; the action configuration was normal for a while. I believe it had to do with right-clicking a convenient effect, toggling it as a condition, and then reloading. But reversing that did not seem to fix it.

Error and messed up action configuration.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/bd1f9e36-bda0-4374-83a1-27255a803ae1

MATT 11.20
Foundry 11.315
D&D 5e 2.4.1
DF Effects 6.0.0

**Comment by ironmonk88** [comment]
I can't replicate it... but I added code to make sure it doesn't break loading the page.
The data will still be wrong, but at least the page won't be weird.

**Comment by Crowguard** [comment]
Steps to recreate.

1. Make new world.
2. Turn MATT & DF Effects on.
3. Go to DF Effects settings, set Modify Status Effects to `Replace`. 
4. Open the Convenient Effects window; right-click an effect and and "Toggle Status Effect". Reload.
5. Open "Filter by Condition" in a MATT tile.

**Comment by ironmonk88** [comment]
Fixed in the latest release
