### ISSUE TITLE
[BUG] DF Convenient Effect Warning

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#692]
Warning that occurs when accessing the two DF Effects actions.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/412b2067-2ccd-41ba-b584-1eb489535407

MATT 11.20
Foundry 11.315
D&D 5e 2.4.1
DF Effects 6.0.0

**Comment by ironmonk88** [comment]
Fixed in the latest release
