### ISSUE TITLE
[BUG] Show Dialog & Set Current Collection

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#696]
A `Set Current Collection` following a `Show Dialog` will result in the Set Collection action stopping the action flow.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/4091a996-8d43-45ab-a408-d515d8bf16c6

MATT 11.21
Foundry 11.315

**Comment by Crowguard** [comment]
Turns out this is also an issue with a `Set Current Collection` that follows a `Delay Actions. 


https://github.com/ironmonk88/monks-active-tiles/assets/99844555/e5dcc8f3-3e70-4e1d-800f-1aa9a3809006

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
