### ISSUE TITLE
[BUG] Door targeting tiles under door throws error when multiple tiles listen for door trigger

### ISSUE THREAD

**Issue by DreadDuchess** [ironmonk88/monks-active-tiles#699]
**Describe the bug**
When a door is set to trigger tiles under it, an error is thrown when more than one listening tile is underneath that door.

**To Reproduce**
1. Create Door.
2. Set tile target to "Tiles under door".
3. Set "On Open Door" and/or "On Close Door".
4. Create two tiles set to react "Door Trigger" events .
5. Set tiles to active.
6. Create an arbitrary trigger action (ex: flip entity.alpha between 0 and 1).
7. Place both tiles under door.
8. Open/close door.

**Expected behavior**
Each tile under the door listening for door triggers reacts appropriately when the door is triggered.

**Screenshots**
![image](https://github.com/ironmonk88/monks-active-tiles/assets/17040793/4d9d44d8-f61a-433a-9ad7-7f1e723342f7)

**Please complete as much of the following information as possible:**
 - Browser: Firefox
 - Foundry Version: 11.315
 - System: Pathfinder 2e v. 5.12.7
 - Module version: 11.21
 - Are there any errors in the console: See screencap
 - Have you tried using `Find the Culprit`: Yes; Issue persists.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
