### ISSUE TITLE
Doors "break" after triggered

### ISSUE THREAD

**Issue by huskyskins** [ironmonk88/monks-active-tiles#7]
Ran into an issue when using a tile to trigger opening doors.  If tile is set to open door and then deactivate itself, you cannot close the door by any means other than deleting the wall segment and recreating it.

![image](https://user-images.githubusercontent.com/86129117/123162576-9f836900-d425-11eb-9787-6b0c163db0d2.png)

**Comment by huskyskins** [comment]
Further investigation, and it looks like if there are two or more actions there is about an 85% chance that the door will get stuck.  If the actions are both doors, then one may get stuck.  If it is open/close door with pause or play sound or show/hide - eventually, the door will get stuck.

**Comment by ironmonk88** [comment]
Darn it.  I was hoping to get that change in before someone caught it.  Lol.
It's fixed.  Just waiting on some other code before the next release.

**Comment by ironmonk88** [comment]
Latest release should have fixed this issue.
