### ISSUE TITLE
Remove "all" Temporary Effects

### ISSUE THREAD

**Issue by Zarhog** [ironmonk88/monks-active-tiles#702]
**Is your feature request related to a problem? Please describe.**
i often find that some spells are not properly set up or somtimes an effect dose not expire. it would be nice to have something to clear all effects on an actor when they walk through a square or area,

**Comment by Crowguard** [comment]
![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/e21c2aa8-a409-4e5e-9551-25318c797b44)


This is already available.

**Comment by ironmonk88** [comment]
Closing ticket because this already exists
