### ISSUE TITLE
[BUG] Play Sound, Restrict to Scene

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#703]
This option isn't working again.

Video shows the GM with all their sound muted on the left, and the player is on a different scene on the right side. Player is the one hearing the sound from the other scene.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/1d772e1f-3dcf-4d12-8feb-b71f4c126697

Foundry 11.315
MATT 11.21

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
