### ISSUE TITLE
[BUG] Door Trigger getting error trying to trigger multiple tiles.

### ISSUE THREAD

**Issue by ChobitsCrazy** [ironmonk88/monks-active-tiles#704]
**Describe the bug**
When a door trigger is assigned multiple tags for tagger throws and error message.

**To Reproduce**
Single tag tagger is working as shown:
![image](https://github.com/ironmonk88/monks-active-tiles/assets/21301107/54db3387-bfe0-4e37-afeb-84a500fa3fbd)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/21301107/cfbf3a7e-fd6d-4a59-ac52-f3315b094259)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/21301107/f199dae3-928e-49bc-84f7-e7c2cfe1ba15)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/21301107/7b1884bf-ca6a-452f-8e08-affb61622cff)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/21301107/3859eab0-f2f4-4c5b-a35c-d7f4227e1831)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/21301107/934e2e29-3a9f-4e08-8894-edf6d4de7c29)

However if putting multiple tags on the door it gets an error message:
![image](https://github.com/ironmonk88/monks-active-tiles/assets/21301107/13c41afd-2193-4d38-962e-5ebb91918a08)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/21301107/ede74281-92cb-4ede-a588-fb2e39080cfb)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/21301107/f0ee00e5-b0a4-40d7-bb8f-c63541cf9a7f)
![image](https://github.com/ironmonk88/monks-active-tiles/assets/21301107/d545c87c-83a5-4a52-91ad-bac56425033c)

**Expected behavior**
It appears that the input allows for multiple tags based on the text. So it should trigger all tiles with any of the tags.

**Please complete as much of the following information as possible:**
 - Browser - Foundry Application
 - Foundry Version - 11.315
 - System - DnD5e v2.4.1
 - Module version - 11.21
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. Yes

**Comment by ChobitsCrazy** [comment]
Just tested this a bit further as well. It seems that it is not able to trigger multiple tiles even when "Tiles Under This Door" is selected. As soon as I move the other tile away from the door it works correctly triggering a single tile.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release

**Comment by DrMcCoy** [comment]
This bug is back in Foundry VTT 12
