### ISSUE TITLE
[BUG] Chat Message, PF2

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#707]
Some of PF2's inline rolls apparently are formatted slightly different from vanilla Foundry, and when copying their text into Chat Message, the action fails. Probably other actions too, Chat Message was the only action I tested.

PF2: [[/r {1d4+1} #rounds]]{1d4+1 rounds}

Core: [[/r 1d4+1]]{1d4+1 rounds}

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/41b0cc7a-c92a-42fa-9986-2cb937483b2b)

Hazard the example is from is `Smoke-Filled Room`.

Foundry 11.315
MATT 11.315
PF2 5.13.1

**Comment by Crowguard** [comment]
Further testing, this doesn't seem to be a PF2 specific formatting. It works in D&D 5e too. Just not sure what to call it ATM.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
