### ISSUE TITLE
[BUG] Stop Tiles Triggering

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#708]
Not sure if this is 100% a bug since I'm working on figuring out priority with this, but I seem to have found one setup that doesn't work properly.

An `Exit` trigger with Stop Tiles Triggering doesn't stop another tile with `Movement` when they overlap and both would be triggered be triggered at the same time. Swapping the `Movement` Trigger to `Stop Within Tile` works as expected.

Also, wondering if I could get the Trigger Type priority for the wiki. 

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/faec29a2-44f8-473c-888d-83c5b7e7ec14

Foundry 11.315
MATT 11.21

**Comment by ironmonk88** [comment]
I don't believe this is a bug.  The movement is going to fire as soon as the token starts to move, and the exit would fire after that when the token exits the tile.

Trigger priority is determined by distance to when they were triggered.
So they're ordered by when they get triggered.  Then, (elevation, rotation, movement, exit, enter, stop).  Then z-index.
