### ISSUE TITLE
Being able to "move" or "teleport" an active tile (Feature Request)

### ISSUE THREAD

**Issue by Darkiller25** [ironmonk88/monks-active-tiles#71]
It would be nice to be able to use the "'Move" or "Teleport" action on the active tile itself.

For example, I have a rock placed somewhere blocking a passage, the player clicks on it and it triggers a roll. If he succeeds, the rock (active tile) would then move to where you want it (right now it seems only possible with tokens).

Thanks!

**Comment by ironmonk88** [comment]
You can use the Alter action to achieve this.
Move is used for Tokens because they have the option of animated movement.  Tiles unfortunately don't.

**Comment by Darkiller25** [comment]
Thanks for the reply! Yeah that's what I was trying to do at first. Use the Move action and select the "entity" as the tile... but it won't select it (it seems to only work with tokens).

**Comment by ironmonk88** [comment]
Closing this as it should be working now.
