### ISSUE TITLE
[BUG] Add Item, New 5e Sheet

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#711]
`Add Item` fails and errors when the target actor is on the new 5e sheet. Works as expected with the legacy sheet.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/6efd19dc-1c96-4231-8c39-c98dc29e04b1

Foundry 11.315
MATT 11.21
D&D 5e 3.0.1

**Comment by notQuiteTrash** [comment]
I am having this same issue, praise be I found someone else with this problem. I had no idea what I was doing wrong. Hopefully we can get an update.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
