### ISSUE TITLE
[BUG] Filter attributes gives weird error and hides token

### ISSUE THREAD

**Issue by vejlin** [ironmonk88/monks-active-tiles#716]
![Skærmbillede 2024-02-19 181332](https://github.com/ironmonk88/monks-active-tiles/assets/5727375/7ba7de7c-ca99-4484-8675-a6a002bb276e)

![validation error](https://github.com/ironmonk88/monks-active-tiles/assets/5727375/c57e5585-48e5-4aad-8ee5-e3dda4b72b41)

When token moves onto tile with a passive perseption of above 15 it disapears and i get the error message from the image.

After reloading Foundry the token is stading it the tile.

**Comment by vejlin** [comment]
After remobing Stop Token Movement the error disapeard.. I see other bug report on that so this one is resolved ;-)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
