### ISSUE TITLE
[BUG] Filter by Condition, 5e

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#719]
Filter by Condition does not work in 5e 3.x.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/b8bcab1d-ceec-475b-80a3-530ccd35d55a

Foundry 11.315
MATT 11.21
D&D 5e 3.0.3

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
