### ISSUE TITLE
[BUG] Trigger at Destination

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#721]
This option isn't triggering any tiles at the destination. Tested with coordinates, select entity, and Tagger.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/7f622ca2-dd8d-46a5-8af1-872a1af600a3

Foundry 11.315
MATT 11.22

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
