### ISSUE TITLE
[BUG] Open URL opens the page to the same new tab if used on multiple tiles

### ISSUE THREAD

**Issue by kjhinds** [ironmonk88/monks-active-tiles#726]
**Describe the bug**
When you activate a tile that's using the Open URL function, it will open the URL in a new tab.  If you then activate another tile that's using the Open URL function, it will direct that URL to open in the same new tab as it previously opened.

**To Reproduce**
1. Create a tile to Open URL on click, e.g., www.github.com
2. Create a second tile to Open URL on click, e.g., www.foundryvtt.com
3. Click one of the tiles to open the URL
4. Without closing the newly opened tab, go back to Foundry and click on the second tile

**Expected behavior**
A second new tab is opened to load the URL of the second tile, resulting in three total tabs, one for Foundry, and one for each of the tiles clicked on.

**Please complete as much of the following information as possible:**
 - Browser: Tested on Firefox, Chrome, and with Foundry Lightweight Client
 - Foundry Version: 11 build 315
 - System: D&D 5E and Pathfinder Second Edition
 - Module version: 11.22
 - Are there any errors in the console [e.g. press F12 and look for red text]
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.

**Additional context**
This doesn't seem to be behavior caused by Foundry itself. I created a Journal entry with two different links. Clicking one link opens a new tab, and then clicking the second link opens a second new tab, as I'd expect.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
