### ISSUE TITLE
New Label Property

### ISSUE THREAD

**Issue by yorkshirelandscape** [ironmonk88/monks-active-tiles#729]
**Is your feature request related to a problem? Please describe.**
I often wish I could associate a label or caption with a tile, though the exact location and behavior might vary. In particular, I have wished that I could exactly replicate the appearance and behavior of a Journal Note with an active tile.

**Describe the solution you'd like**
The most grandiose version I could imagine would be a full-fledged teleprompter sort of thing. It would allow you to overlay text on the tile and play through it at rates defined in the text markup. The simplest version would be a text property that would display someplace on or near the tile. Somewhere in between you could have the ability to display text on or around the tile, appear and disappear, scroll, appear only on hover, all that sort of stuff. 

**Additional context**
If I were about to do this myself and go all-out, I'd allow the user lots of options, like this:
**Text:** [ free-entry ]
**Font:** [ various ]
**Size:** [ in pts ]
**Weight:** [ Regular, Bold ]
**Style:** [ Roman, Italic ]

**In/Out:** [ Inner, Outer ]
**H-Align:** [ Left, Center, Right ]
**V-Align:** [ Top, Middle, Bottom ]
**Orientation**: [ Horizontal, Vertical, Rotated ]
**Padding**: [ in pixels ]

**Show When**: [ Always, Hover ]
**Show Who**: [ All, GM Only ]

Here's a mockup:
```
        O          O          O
        L          C          R
        T          T          T
        V          V          V
        *OLTH    OC*TH    ORTH*
      ___________________________      
OLTH* | *ILTH    IC*TH    IRTH* | *ORTH
    O | I          I          I | O
    L | L          C          R | R
    T | T          T          T | T
    V | V          V          V | V
      |                         |
    O | I          I          I | O
    L | L          C          R | R
OLMH* | *ILMH    IC*MH    IRMH* | *ORMH
    M | M          M          M | M
    V | V          V          V | V
      |                         |
    O | I          I          I | O
    L | L          C          R | R
    B | B          B          B | B
    V | V          V          V | V
OLBH* | *ILBH    IC*BH    IRBH* | *ORBH
      ___________________________
        *OLBH    OC*BH    ORBH*
        O          O          O
        L          C          R
        B          B          B
        V          V          V
```

**Comment by ironmonk88** [comment]
This is outside the scope of this module.
You're not triggering an action... but redesigning how a Tile works.
Not saying it's not a good idea... but it should go in a different module.

**Comment by yorkshirelandscape** [comment]
Fair enough. Thanks for considering it.
