### ISSUE TITLE
[BUG] Set Variable True/False

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#734]
Setting a variable to true/false just sets an empty variable.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/b73cbf0a-6312-4947-bd0d-732d892c386f

Foundry 11.315
MATT 11.23

**Comment by ironmonk88** [comment]
That needs to be `= true`.  Otherwise it has no way to know if this is a string "true" or an actual true.
