### ISSUE TITLE
Apply random Damage to Token

### ISSUE THREAD

**Issue by TheBaronWasteland** [ironmonk88/monks-active-tiles#74]
I'm trying to use an Active Tile Trigger as follows:  When a token moves onto the area it falls to the next level and takes falling damage (say 4d6).  The change in elevation works perfectly but not the random damage.  Set up as follows:
![image](https://user-images.githubusercontent.com/90156767/143687587-c0cca135-7531-4dff-9f0f-f24b38c46ca4.png)
When there is a specific number instead of "- 4d6" the HP attribute is changed by the number as expected.  The rolling damages doesn't seem to work.  As an aside if the Add Chat Message is ticked nothing happens.

**Comment by ironmonk88** [comment]
I think this got solved on Discord.
But in case anyone else comes looking, the correct syntax is `-[[4d6]]`
