### ISSUE TITLE
[BUG] Movement & Triggering Token

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#744]
Movement trigger is currently not passing the triggering token information.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/6ee51707-e3fd-45ff-a407-a14a5818b64b

Foundry 11.315
MATT 11.26

**Comment by Zephyr2011** [comment]
I've also replicated this.

You can see tile history here that movement is providing the triggering token, but other actions will.

Triggering user/player _do_ still seem to function though.

![2024-05-08 11_41_41-Window](https://github.com/ironmonk88/monks-active-tiles/assets/85969310/7c9a81d0-18d0-4adc-811f-2bc706dca157)
