### ISSUE TITLE
[BUG] Removing Effect Bricks Actor, PF2

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#750]
Using either Active Effect or Remove Item to attempt to remove an effect from a PF2 PC results in the effect not being removed and the actor sheet no longer being able to be opened.

Various errors in the console at various steps. There was an error not shown that I cannot replicate now that occurred when editing the MATT action post-trigger.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/b6838bde-10fa-4064-b451-3b21ba2d7433

Foundry 11.315
MATT 11.26
PF2 5.15.2

**Comment by ExileofBrokenSky** [comment]
Seems specific to using remove item to remove a condition;
removing effects, equipment, spells, feats, actions all seem to work normally.

**Comment by Crowguard** [comment]
Found the error. Shows up if you create a new tile with a bricked token on the scene.

![image](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/148207f8-3c9a-4be9-82e1-2f068c69e814)

**Comment by ironmonk88** [comment]
Not sure what PF2e is doing to brick the characters, but I've added code to try and avoid it.
I've also added a Macro in the latest release that should recover the Actor, and allow you to go in and clear the affected condition.
