### ISSUE TITLE
Provide Tile ID as part of the arguments via 'Run Macro' action

### ISSUE THREAD

**Issue by Aedif** [ironmonk88/monks-active-tiles#752]
**Is your feature request related to a problem? Please describe.**

I'd like to process a triggered tile using a macro via a GM that is on another scene. When a GM is on another scene `tile` argument is null, and far as I can tell there is no way to access the tile's ID to be able to retrieve it from the `scene`.

**Describe the solution you'd like**

Provide tile ID or tile document as part of the accessible arguments for the macro ran via `Run Macro`

**Additional context**

I attempted a workaround by setting the tile variable with the tile's ID, but it seems that `variable` is not within scope of the handlebars expressions within `Run Macro`'s `Args` field.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
