### ISSUE TITLE
[BUG] Player Triggers Door, Current Wall

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#754]
A player triggering a door isn't passing that door to the `current wall collection`. Nothing in the console. Works as expected for the GM.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/fde691d3-ee82-416b-9671-16da8dc5e6e5

Foundry 11.315
MATT 11.26

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
