### ISSUE TITLE
[BUG] Attack, Player Triggered

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#755]
Attack action is not comparing AC or showing the target when the tile is triggered by a player.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/69c6c98e-decb-4332-8074-e241a363076d

Foundry 11.315
MATT 11.26
PF2 5.15.3

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
