### ISSUE TITLE
add opacity % option to show/hide

### ISSUE THREAD

**Issue by Mechanized82** [ironmonk88/monks-active-tiles#757]
**Is your feature request related to a problem? Please describe.**
I'd like to completely hide a tile as it is always visible as a GM, and annoying, then use a tile trigger button to have it fade into view. 

**Describe the solution you'd like**
Add an opacity option.  Instead of just show/hide.  Set opacity to 0, then X, with duration.  

**Additional context**
Example: I have a scene where it magically floods the whole scene and can recede. I'm using a button to have the water tile fade into or out of view, but as a GM the tile is always visible. It would be nice to set this, and other scenes up, in a manner where I see what the players see.

**Comment by ironmonk88** [comment]
![image](https://github.com/ironmonk88/monks-active-tiles/assets/75920956/0c427f7a-060e-4e6c-be99-25cc8efc0f3a)

**Comment by ironmonk88** [comment]
Show/hide doesn't work that way.  What you're changing is the `alpha` of the Tile and that needs to go through the `alter` action.
Since this is already something that can be done, I'm closing the ticket.
