### ISSUE TITLE
[BUG] Open Journal, Check Permission

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#758]
Having Check Permission enabled causes this action to not work; it always seems to work if the player immediately triggers it after the GM does; any further triggers alternate between failure and an error, or working as expected.

Action works as expected with this option unchecked.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/f4136cbb-6f71-48ea-a125-2c7c6303d659

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/991be468-feed-4508-8cb8-d0d320f5aa7d

Foundry 11.315
MATT 11.26

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
