### ISSUE TITLE
"After" option (delay) not appearing when adding new actions

### ISSUE THREAD

**Issue by JimKuhn** [ironmonk88/monks-active-tiles#76]
It looks like the culprit is:

https://github.com/ironmonk88/monks-active-tiles/blob/46f7932e095b1cd6fdc4e10c12d4badd1f0534a1/apps/action-config.js#L363

Changing it to:

```typescript
$('[data-type="delay"]', this.element).toggle(action?.options?.allowDelay && command != 'delay');
```

seems to work.

**Comment by ironmonk88** [comment]
That was done on purpose.
Delay actions has moved to it's own command.
![image](https://user-images.githubusercontent.com/75920956/146651771-3f4a03c2-444b-428d-9ca9-8e88b5c5980e.png)
Having it attached to the action itself caused a lot of sync issues, moving it to it's own action has cleared those up.

**Comment by JimKuhn** [comment]
It's somewhat confusing... editing an existing action with a delay shows it accordingly.  Adding a new one doesn't.  Is this new behavior documented somewhere?
