### ISSUE TITLE
[BUG] v12 Imageless Tile Bounding Box

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#764]
Having MATT active offsets the bounding box of any tiles with no image. Adding a tile image also fixes the bounding box. 

Also a warning in the video, not sure what triggered it.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/f9fb6df7-e3b4-403a-bbbe-9721572378e1

Foundry 12.324
MATT 11.27

**Comment by Schnix1328** [comment]
I have the same error. Additionally when I click the tiles nothing is happening.

**Comment by Cedric-the-Destroyer** [comment]
To add to this, clicking on my tiles seems to have broken in it's entirety. My landing page where I linked to scenes/character sheets/etc doesn't seem to do anything

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
