### ISSUE TITLE
Click-triggering scene-changing tiles isn't possible if the gamemaster isn't logged in.

### ISSUE THREAD

**Issue by hydrated12** [ironmonk88/monks-active-tiles#77]
I have a digitalocean server set up specifically for foundry, and I also have sort of a menu with active tiles set up that changes the scene to our main screen, short bios for characters and a screen that acts as an archive for past adventures. When I'm online on the server myself and logged into the GM's account - these tiles trigger just fine, clicking on them changes the scene for the triggering player as it should, when I log off however - it stops doing that, acting as if the tile isn't active at all.

**Comment by ironmonk88** [comment]
Did you allow players to activate triggers when the GM isn't present?
![image](https://user-images.githubusercontent.com/75920956/146987663-e70d1822-7f70-4ab7-991f-9aaf5a7e2563.png)

**Comment by hydrated12** [comment]
Somehow I missed that in the module settings, wow, now I feel very stupid. Sorry for wasting your time.
