### ISSUE TITLE
[BUG] v12 Refresh Occlusion Error

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#772]
Shows up from various things, tile history being active or the switch image action.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/5db84fab-0468-42e8-aae1-93d16f13810b

Foundry 12.325
MATT 11.27

**Comment by ironmonk88** [comment]
That's a Foundry bug.  It's in their code.
