### ISSUE TITLE
[BUG] v12 Lighting Change Error

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#778]
Whenever scene lighting is changed with the lighting trigger.

![Foundry_Virtual_Tabletop_sVQOI7vh7h](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/93319714-c090-48fa-b5d2-d78b7093164e)

Foundry 12.325
MATT 11.27

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
