### ISSUE TITLE
[BUG] v12 globalThis.duplicate Error

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#779]
Occurs when duplicating an action via right-click.

![Foundry_Virtual_Tabletop_yyfpLT26FB](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/3a4fa55b-da69-4cc6-aaff-b45162892a54)

Foundry 12.325
MATT 11.27

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
