### ISSUE TITLE
Feature Request: Only trigger highest Z tile

### ISSUE THREAD

**Issue by ianm32** [ironmonk88/monks-active-tiles#78]
This is less of a concern for tokens and battlemap-related active tiles, but much more for clickable tiles.  I've noticed that if there are several active tiles set to activate on click or double-click on top of one another, clicking on a tile will activate the entire stack.  Would it be possible to have an option (maybe even on a per-tile basis) to only trigger the highest tile in the z-order, and block the triggering of tiles below it?

**Comment by ironmonk88** [comment]
Added to the latest release
