### ISSUE TITLE
[BUG] v12 Grid Precision Warning

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#781]
![Foundry_Virtual_Tabletop_T7laF4yuxX](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/95248ab6-5571-4bb6-b6a5-fca04d4ae995)

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/6e0cf446-45bc-4e52-be61-0b4eb12c699b

Foundry 12.325
MATT 11.27

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
