### ISSUE TITLE
[BUG] v12 getSnappedPosition Error

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#782]
Same video as #781

![Foundry_Virtual_Tabletop_hiH9sF0eWK](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/3972a9e6-f7e2-4c79-9bd0-51049b8c782b)

Foundry 12.325
MATT 11.27

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
