### ISSUE TITLE
[BUG] v12 Hurt/Heal

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#784]
Having brackets breaks it entirely. 

Having a negative sign makes things interesting. 

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/fa696adc-d89d-4e4a-8fa1-2bce23204160

Foundry 12.325
MATT 11.27

**Comment by ironmonk88** [comment]
That's pretty much working as expected.  the syntax is `-[[1d4]]`.
The other warnings have been fixed.
