### ISSUE TITLE
[BUG] v12 Scene Lighting Error

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#787]
![Foundry_Virtual_Tabletop_v0dgGLBXaW](https://github.com/ironmonk88/monks-active-tiles/assets/99844555/99cab97e-9296-4e6c-befd-37695eb95fc6)

Foundry 12.325
PF2 6.0.0 beta
MATT 11.27

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
