### ISSUE TITLE
[BUG] v12? Door Trigger, Secret

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#790]
There seems to be some inconsistencies whether this triggers or not. I suspect there's some kind of timing issue; the bottom tile triggers consistently with the Delay included. 

I was seeing similar results in v11, so I'm not sure if this is a new issue or not. 

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/3a1e1729-3056-4a41-829b-57db48f80f36

Foundry 12.325
MATT 11.27
Wall Enhancements 12.01

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
