### ISSUE TITLE
[BUG] v11 cannot update: documentTypes: is not a valid sub-types configuration: 'RegionBehavior' is not a valid Document type

### ISSUE THREAD

**Issue by matjam** [ironmonk88/monks-active-tiles#792]
**Describe the bug**
When installed in v11, updating the module fails when using the "Update All" feature in Foundry.

The specific error is

```
Error: Module validation errors:
  documentTypes: is not a valid sub-types configuration: 'RegionBehavior' is not a valid Document type
    at Setup.post (setup.js:5991:21)
    at async #updateCheck (setup.js:2927:24)
    at async update (setup.js:2729:23)
```

**To Reproduce**
1. Install Foundry v11
2. Install an older version of monks active tiles
3. Click the "Update All" button

**Expected behavior**
I expect that either the module is updated, or it displays a message similar to the other monks modules. For example:

![image](https://github.com/ironmonk88/monks-active-tiles/assets/578676/5284483f-28eb-433f-bc53-223bc477d79e)

**Screenshots**
![image](https://github.com/ironmonk88/monks-active-tiles/assets/578676/38b1c6d3-49e3-40b1-9a58-184762439a1a)

**Please complete as much of the following information as possible:**
 - Browser: chrome
 - Foundry Version: v11
 - System: D&D5e
 - Module version: 11.27

**Comment by ironmonk88** [comment]
That's a Foundry issue.  Not much I can do about that.
You'll just keep seeing it until you update to v12.

**Comment by LgocialHorus** [comment]
I saw in the changelog of Baileywiki Mass Edit that they somehow managed to fix that error:
[[Changelog](https://github.com/Aedif/multi-token-edit/blob/main/CHANGELOG.md)](https://github.com/Aedif/multi-token-edit/blob/main/CHANGELOG.md)

**Comment by ironmonk88** [comment]
Pretty sure that's not related to this issue at all.  Mass Edit doesn't add any additional behaviors to the Regions.  Which is what Active Tiles does.
And... there's not really a way around it.  The updates are required in the manifest, but Foundry checks validity before checking version.  So it's up to Foundry to fix their issue.

**Comment by LgocialHorus** [comment]
I see, sorry for the mix up.

**Comment by Crowguard** [comment]
https://github.com/foundryvtt/foundryvtt/issues/11188

Link to the Foundry ticket for it.

**Comment by matjam** [comment]
closing issue as the bug is in Foundry.
