### ISSUE TITLE
[BUG] Change Permission, Players Only

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#795]
Change Permission's `Players Only` seems to only be applying changes for logged in players. Not sure if this is intended or not.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/fd782d18-7f04-434c-b5ed-87db6b234418

Foundry 12.325
MATT 12.01
FTC

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
