### ISSUE TITLE
Teleport to other scene logic problems

### ISSUE THREAD

**Issue by tagnullde** [ironmonk88/monks-active-tiles#8]
I tried to create a teleport-tile from "Scene A" to "Scene B" and vice versa.
The logic behind it doesn't quite work though.

Token steps into "Teleporter-Scene-A-To-B" and gets set to invisible.
Token "appears" on "Scene B". So far, so good.

Same Token now steps into the "Teleporter-Scene-B-To-A".
Token vanishes (not invisible but sort of "deleted") from "Scene-B" and "appears" on "Scene-A".
The initial (former invisible) token is also now gone (ie. "deleted").

If the Token now steps into the "Teleporter-Scene-A-To-B" again it doesn't get teleported to "B" but vanishes too, leaving
no actor on scene alltogether.

Now things get really weird. Trying to replicate this didn't work. A new token isn't transfered to "B" anymore - however gets set to invisible.

I'll try to replicate that and might update this issue should I be able to.

**Comment by ironmonk88** [comment]
Is this still an issue?
I've made a bunch of changes and might have fixed this.

**Comment by tagnullde** [comment]
I'll try it as soon as I find some spare later today. Thanks for the headsup.

**Comment by tagnullde** [comment]
Seems to be fixed. Couldn't find any problems.
Thank you!

**Comment by ironmonk88** [comment]
Yayyy! Thank you for checking on this.
