### ISSUE TITLE
Teleporting a token would discard temporary changes

### ISSUE THREAD

**Issue by Streyder** [ironmonk88/monks-active-tiles#80]
Hi Monk,

as discussed I create this issue about teleporting tokens.

Description:
When a token is teleported to another scene, its temporary changes are lost. This happens because a new token is created from the actor datasheet. This means it contains the data of the prototype token. Changes to vision, orientation etc. made to the current token are lost in this process. The same happened if a token for this actor already existed on the scene: instead of creating a new token with the current information, the old token was moved to the new position, keeping its old data.

I identified the issue in your codebase and tried to fix it:
https://github.com/ironmonk88/monks-active-tiles/pull/79

Neither my JS nor my Foundry API knowledge are particularly good so please have a look if my suggested change! I assume the same bug could exist in multiple other scenarios, though it does not when teleported within the same scene.

Cheers

**Comment by ironmonk88** [comment]
Closing as the code got implemented.
