### ISSUE TITLE
[BUG] Error: Module Validation Error

### ISSUE THREAD

**Issue by deciusaemilius** [ironmonk88/monks-active-tiles#803]
While still running Foundry v11, attempting to update modules gives the error: "Error: Module validation errors: documentTypes: is not a valid sub-types configuration: 'RegionBehavior' is not a valid document type"

I believe the issue is due to the addition of new regions into Foundry v12 and the latest versions of this module should be marked as requiring v12 minimum. 

![Error](https://github.com/ironmonk88/monks-active-tiles/assets/173701386/7a5259c1-d8b4-4e56-8483-60817b7dfc98)

**Comment by ironmonk88** [comment]
Closing duplicate #792
