### ISSUE TITLE
[BUG] v12 Temp Tile Image

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#804]
Temp Tile Image isn't working (the tile mesh disappears when triggered).

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/25f51bae-c45d-4c31-88b0-6e3854c1cdc5

Foundry 12.327
MATT 12.01

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
