### ISSUE TITLE
[BUG] Switch Tile Image, Range

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#814]
Currently doing nothing when a range `1-4` is entered. Likely related to #736.

https://github.com/user-attachments/assets/1312ef55-cf15-4a23-be78-c33cba27720f

Foundry 11 & 12.328
MATT 12.01

**Comment by demotech89** [comment]
I want to add, I cant switch any tile when just using two images to cycle between the two.

**Comment by Crowguard** [comment]
@demotech89 Please include your versions & a screenshot of your tile config.

**Comment by ironmonk88** [comment]
Also @demotech89 do not add to a ticket.  Start a new ticket if the behavior is different.  Because then I can't close this ticket if there are other issues within it open, and the title will no longer match what the "current" issue is.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
