### ISSUE TITLE
[Feature Request] Alter, texture.tint

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#816]
Foundry v12 changed texture.tint (& likely whatever the token tint is) from strings to...whatever they are now. This has broken people's existing tiles; adding this in hope of a workaround.

![chrome_6kC0VS1HBf](https://github.com/user-attachments/assets/6659f403-8a3e-486e-9305-0f23c52bebaa)
![Foundry_Virtual_Tabletop_iQMUVgNEVO](https://github.com/user-attachments/assets/aa5887a1-ce2e-4c82-8462-4caffee8b8c4)

Foundry 12.328
MATT 12.01

**Comment by mcdaddytalk** [comment]
tint has been converted from string to a foundry util class "Color" (https://foundryvtt.com/api/classes/foundry.utils.Color.html#fromString) which has a "fromString()" method that make migration from older versions to v12

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
