### ISSUE TITLE
[BUG] Rotation & Lights

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#821]
### Issue 1

Lights are now giving `Invalid Entity Type` when using direct select.

### Issue 2

Rotating a light via Tagger does some really weird things with the light range indicator, the rendered light, and the light's config rotation all getting out of sync.

https://github.com/user-attachments/assets/308a14ce-0388-47c7-999b-86afa18cc9a4

Also a deprecation error in this second video.
![firefox_2GSsabfFBE](https://github.com/user-attachments/assets/a1c642c8-e448-4a49-897c-39e6fae9a378)

https://github.com/user-attachments/assets/907a279e-d0c3-44db-bd1c-65383d60deaf

Foundry 12.330
MATT 12.01

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
