### ISSUE TITLE
Select a specific token for the "Alter"/"Move" options on a tile

### ISSUE THREAD

**Issue by Pibemanden** [ironmonk88/monks-active-tiles#88]
Currently it is possible to select "The triggering token", "Tokens within tile" or "Player Tokens". But it doesn't seem to be able to select a specific token in the scene, is it possible to add this feature to the module?

**Comment by ironmonk88** [comment]
![image](https://user-images.githubusercontent.com/75920956/148972745-95b3f6e8-1d8c-425f-83e2-b315acf1b0ac.png)
Click that button then switch to the token layer and click on a Token.
You should be able to select a Token.

**Comment by Pibemanden** [comment]
I tried doing that, but it only allows me to select tiles, not tokens.

**Comment by Pibemanden** [comment]
Sorry I am still new to Foundry and now I see my mistake after watching someone else to the correct thing. Switch to the token layer means pressing the token menu in the left set of menus, when I do that everything works correctly.

Thank you @ironmonk88 for developing an awesome module which allows so many fun automatization ideas to come to life in Foundry.
