### ISSUE TITLE
[Feature request] execute actions if an automated roll succeeds or fails

### ISSUE THREAD

**Issue by brian-e-haley** [ironmonk88/monks-active-tiles#9]
Currently there is no way to automate the displaying of selective information to some players. It would be very useful if actions resolved from top to bottom and if a roll failed any later actions were skipped or if there was a way to perform add conditions and triggers.

An example use case is if a character walks up to a statue and you display the information from a plaque. If that character also succeeds at a bling perception roll you also display a hidden message otherwise that information doesn't display.

**Comment by ironmonk88** [comment]
Has been added to the latest version.
Currently both macros and Tokenbar requests can stop the remaining actions from happening.
