### ISSUE TITLE
Feature Request: Toggle Secret Door

### ISSUE THREAD

**Issue by agentnos** [ironmonk88/monks-active-tiles#91]
At the moment, when it comes to secret doors, you can either set them to open or closed. It would be really great to be able to toggle the door's Secret mode for noticing a secret door, without having it automatically open it. (Unless there is already a way and I haven't found it yet)

Also, keep up the good work, it's a really, really great module!

**Comment by Gieff** [comment]
If you wanna cycle the wall status between secret/door try this: 
![image](https://user-images.githubusercontent.com/84387556/151949429-33324d64-f8ea-4ad6-9f7f-8bc54e727621.png)

In a similar way, can alter a solid wall/transparent wall:
![image](https://user-images.githubusercontent.com/84387556/151952267-47ab729d-4c9b-4290-a319-d508781c8a8c.png)


Still, a easier way to manipulate wall should be welcomed.

**Comment by ironmonk88** [comment]
Toggling a secret door should be available in the latest version.
