### ISSUE TITLE
Feature Request: Allow Pan Canvas to specify a duration

### ISSUE THREAD

**Issue by Seamonster73** [ironmonk88/monks-active-tiles#93]
If possible, could a duration field/parameter (in milliseconds) be added to the Pan Canvas action so that the pan&zoom could smoothly animate to a particular point over a user specified period of time?

This would allow GMs to trigger slow panning shots to particular areas of a scene to (for example) signify important events, draw attention to locations, or to pan across 'vista' style images in a more pleasing manner.

**Comment by ironmonk88** [comment]
Fixed in latest release.
