### ISSUE TITLE
Second "On Click" trigger after failed check automatically succeeds.

### ISSUE THREAD

**Issue by TheRudeDevil** [ironmonk88/monks-active-tiles#95]
I set up a tile that is a blocked door with some furniture behind that require the token to do a strength check to be able to open. 
I usually don't use the "On Click" trigger but I felt that it would be more fun to make the players just click the door themselves and roll for strength. 

When I tested it and clicked the tile it triggered the roll request, I rolled and I failed, no door opened - so far so good.
I clicked it again and no roll request came, instead the door opened automatically even though it states that it should only continue on success.

Is there a bug or did I make a mistake somewhere?

![Screenshot_288](https://user-images.githubusercontent.com/76971185/150397801-51965709-026c-4177-8488-a6dd45090168.png)

**Comment by TheRudeDevil** [comment]
"On Double click" doesn't trigger the Roll request at all, instead it activates the Cycle images and Change door status automatically.
Seems that the only way I can have it trigger the roll request again after a fail when "On Click" is selected is to move the token and then click again.

**Comment by TomChristoffer** [comment]
I can confirm that it doesn't like clicking twice on things, I have menu buttons that scroll through pages, and if you click them too fast after scrolling it doesn't work, and you have to move the cursor off the tile and on again in order to click it.

**Comment by TheRudeDevil** [comment]
Latest release (1.0.51) seems to have fixed the "On Click" issue. :)
