### ISSUE TITLE
Feature Request: Toggle Hidden

### ISSUE THREAD

**Issue by galaara98** [ironmonk88/monks-active-tiles#96]
currently hidden can be handled by Alter: Hidden, 0 or 1.  But there is no way to toggle.  I'd love to see Hidden its own item and allowed to be: true, false, or toggle

**Comment by ironmonk88** [comment]
Do you mean the `Show/Hide` action?

**Comment by galaara98** [comment]
oh sorry, i should have mentioned that doesn't work for Sound and Lights.

i actually forgot it was there...

**Comment by galaara98** [comment]
ok, it looks like activate/deactivate works for lights and sound (which i didnt notice before)
and Show/Hide works for tiles and actors
and Door Control works for walls

So we are good, sorry for the confusion
