### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by pesky-wobbit** [ironmonk88/monks-active-tiles#98]
![image](https://user-images.githubusercontent.com/477446/150690253-0270f2fe-95c4-46fe-9f31-5abfc2240cb0.png)

I'm configuring little info tiles to great effect. A notification text pops up when the info circle is hovered in. 

Request: a time parameter for the hover, so the trigger does NOT fire accidentally as the mouse is moving elsewhere.

**Comment by galaara98** [comment]
yeah, i'd like that also (1 second or so)
Hover In, Hover out, Hover Stop within Tile

**Comment by ironmonk88** [comment]
Closing this as you can currently achieve this with actions.
![image](https://github.com/ironmonk88/monks-active-tiles/assets/75920956/2aa57ad9-4b16-4cac-876c-9cf2a13f4a36)

![image](https://github.com/ironmonk88/monks-active-tiles/assets/75920956/4fddde43-9c79-4f9e-bbbc-26fce35a9c01)
